name: autofill_test
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_time_ago: ^1.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^6.0.1

flutter:
  uses-material-design: true
