name: autofill_test
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_time_ago: ^1.2.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^4.0.0

flutter:
  uses-material-design: true
