
var CanvasKitInit = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var r=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),fa="object"==typeof window,ia="function"==typeof importScripts;
(function(a){a.de=a.de||[];a.de.push(function(){a.MakeSWCanvasSurface=function(b){var c=b,e="undefined"!==typeof OffscreenCanvas&&c instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&c instanceof HTMLCanvasElement||e||(c=document.getElementById(b),c)))throw"Canvas with id "+b+" was not found";if(b=a.MakeSurface(c.width,c.height))b.Be=c;return b};a.MakeCanvasSurface||(a.MakeCanvasSurface=a.MakeSWCanvasSurface);a.MakeSurface=function(b,c){var e={width:b,height:c,colorType:a.ColorType.RGBA_8888,
alphaType:a.AlphaType.Unpremul,colorSpace:a.ColorSpace.SRGB},f=b*c*4,k=a._malloc(f);if(e=a.Surface._makeRasterDirect(e,k,4*b))e.Be=null,e.af=b,e.Ye=c,e.Ze=f,e.Ie=k,e.getCanvas().clear(a.TRANSPARENT);return e};a.MakeRasterDirectSurface=function(b,c,e){return a.Surface._makeRasterDirect(b,c.byteOffset,e)};a.Surface.prototype.flush=function(b){a.ae(this.$d);this._flush();if(this.Be){var c=new Uint8ClampedArray(a.HEAPU8.buffer,this.Ie,this.Ze);c=new ImageData(c,this.af,this.Ye);b?this.Be.getContext("2d").putImageData(c,
0,0,b[0],b[1],b[2]-b[0],b[3]-b[1]):this.Be.getContext("2d").putImageData(c,0,0)}};a.Surface.prototype.dispose=function(){this.Ie&&a._free(this.Ie);this.delete()};a.ae=a.ae||function(){};a.Ce=a.Ce||function(){return null}})})(r);
(function(a){a.de=a.de||[];a.de.push(function(){function b(l,p,v){return l&&l.hasOwnProperty(p)?l[p]:v}function c(l){var p=ja(ka);ka[p]=l;return p}function e(l){return l.naturalHeight||l.videoHeight||l.displayHeight||l.height}function f(l){return l.naturalWidth||l.videoWidth||l.displayWidth||l.width}function k(l,p,v,w){l.bindTexture(l.TEXTURE_2D,p);w||v.alphaType!==a.AlphaType.Premul||l.pixelStorei(l.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!0);return p}function n(l,p,v){v||p.alphaType!==a.AlphaType.Premul||
l.pixelStorei(l.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);l.bindTexture(l.TEXTURE_2D,null)}a.GetWebGLContext=function(l,p){if(!l)throw"null canvas passed into makeWebGLContext";var v={alpha:b(p,"alpha",1),depth:b(p,"depth",1),stencil:b(p,"stencil",8),antialias:b(p,"antialias",0),premultipliedAlpha:b(p,"premultipliedAlpha",1),preserveDrawingBuffer:b(p,"preserveDrawingBuffer",0),preferLowPowerToHighPerformance:b(p,"preferLowPowerToHighPerformance",0),failIfMajorPerformanceCaveat:b(p,"failIfMajorPerformanceCaveat",
0),enableExtensionsByDefault:b(p,"enableExtensionsByDefault",1),explicitSwapControl:b(p,"explicitSwapControl",0),renderViaOffscreenBackBuffer:b(p,"renderViaOffscreenBackBuffer",0)};v.majorVersion=p&&p.majorVersion?p.majorVersion:"undefined"!==typeof WebGL2RenderingContext?2:1;if(v.explicitSwapControl)throw"explicitSwapControl is not supported";l=na(l,v);if(!l)return 0;oa(l);z.me.getExtension("WEBGL_debug_renderer_info");return l};a.deleteContext=function(l){z===pa[l]&&(z=null);"object"==typeof JSEvents&&
JSEvents.Bf(pa[l].me.canvas);pa[l]&&pa[l].me.canvas&&(pa[l].me.canvas.We=void 0);pa[l]=null};a._setTextureCleanup({deleteTexture:function(l,p){var v=ka[p];v&&pa[l].me.deleteTexture(v);ka[p]=null}});a.MakeWebGLContext=function(l){if(!this.ae(l))return null;var p=this._MakeGrContext();if(!p)return null;p.$d=l;var v=p.delete.bind(p);p["delete"]=function(){a.ae(this.$d);v()}.bind(p);return z.Ke=p};a.MakeGrContext=a.MakeWebGLContext;a.GrDirectContext.prototype.getResourceCacheLimitBytes=function(){a.ae(this.$d);
this._getResourceCacheLimitBytes()};a.GrDirectContext.prototype.getResourceCacheUsageBytes=function(){a.ae(this.$d);this._getResourceCacheUsageBytes()};a.GrDirectContext.prototype.releaseResourcesAndAbandonContext=function(){a.ae(this.$d);this._releaseResourcesAndAbandonContext()};a.GrDirectContext.prototype.setResourceCacheLimitBytes=function(l){a.ae(this.$d);this._setResourceCacheLimitBytes(l)};a.MakeOnScreenGLSurface=function(l,p,v,w,A,D){if(!this.ae(l.$d))return null;p=void 0===A||void 0===D?
this._MakeOnScreenGLSurface(l,p,v,w):this._MakeOnScreenGLSurface(l,p,v,w,A,D);if(!p)return null;p.$d=l.$d;return p};a.MakeRenderTarget=function(){var l=arguments[0];if(!this.ae(l.$d))return null;if(3===arguments.length){var p=this._MakeRenderTargetWH(l,arguments[1],arguments[2]);if(!p)return null}else if(2===arguments.length){if(p=this._MakeRenderTargetII(l,arguments[1]),!p)return null}else return null;p.$d=l.$d;return p};a.MakeWebGLCanvasSurface=function(l,p,v){p=p||null;var w=l,A="undefined"!==
typeof OffscreenCanvas&&w instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&w instanceof HTMLCanvasElement||A||(w=document.getElementById(l),w)))throw"Canvas with id "+l+" was not found";l=this.GetWebGLContext(w,v);if(!l||0>l)throw"failed to create webgl context: err "+l;l=this.MakeWebGLContext(l);p=this.MakeOnScreenGLSurface(l,w.width,w.height,p);return p?p:(p=w.cloneNode(!0),w.parentNode.replaceChild(p,w),p.classList.add("ck-replaced"),a.MakeSWCanvasSurface(p))};a.MakeCanvasSurface=
a.MakeWebGLCanvasSurface;a.Surface.prototype.makeImageFromTexture=function(l,p){a.ae(this.$d);l=c(l);if(p=this._makeImageFromTexture(this.$d,l,p))p.ve=l;return p};a.Surface.prototype.makeImageFromTextureSource=function(l,p,v){p||={height:e(l),width:f(l),colorType:a.ColorType.RGBA_8888,alphaType:v?a.AlphaType.Premul:a.AlphaType.Unpremul};p.colorSpace||(p.colorSpace=a.ColorSpace.SRGB);a.ae(this.$d);var w=z.me;v=k(w,w.createTexture(),p,v);2===z.version?w.texImage2D(w.TEXTURE_2D,0,w.RGBA,p.width,p.height,
0,w.RGBA,w.UNSIGNED_BYTE,l):w.texImage2D(w.TEXTURE_2D,0,w.RGBA,w.RGBA,w.UNSIGNED_BYTE,l);n(w,p);this._resetContext();return this.makeImageFromTexture(v,p)};a.Surface.prototype.updateTextureFromSource=function(l,p,v){if(l.ve){a.ae(this.$d);var w=l.getImageInfo(),A=z.me,D=k(A,ka[l.ve],w,v);2===z.version?A.texImage2D(A.TEXTURE_2D,0,A.RGBA,f(p),e(p),0,A.RGBA,A.UNSIGNED_BYTE,p):A.texImage2D(A.TEXTURE_2D,0,A.RGBA,A.RGBA,A.UNSIGNED_BYTE,p);n(A,w,v);this._resetContext();ka[l.ve]=null;l.ve=c(D);w.colorSpace=
l.getColorSpace();p=this._makeImageFromTexture(this.$d,l.ve,w);v=l.Zd.be;A=l.Zd.fe;l.Zd.be=p.Zd.be;l.Zd.fe=p.Zd.fe;p.Zd.be=v;p.Zd.fe=A;p.delete();w.colorSpace.delete()}};a.MakeLazyImageFromTextureSource=function(l,p,v){p||={height:e(l),width:f(l),colorType:a.ColorType.RGBA_8888,alphaType:v?a.AlphaType.Premul:a.AlphaType.Unpremul};p.colorSpace||(p.colorSpace=a.ColorSpace.SRGB);var w={makeTexture:function(){var A=z,D=A.me,I=k(D,D.createTexture(),p,v);2===A.version?D.texImage2D(D.TEXTURE_2D,0,D.RGBA,
p.width,p.height,0,D.RGBA,D.UNSIGNED_BYTE,l):D.texImage2D(D.TEXTURE_2D,0,D.RGBA,D.RGBA,D.UNSIGNED_BYTE,l);n(D,p,v);return c(I)},freeSrc:function(){}};"VideoFrame"===l.constructor.name&&(w.freeSrc=function(){l.close()});return a.Image._makeFromGenerator(p,w)};a.ae=function(l){return l?oa(l):!1};a.Ce=function(){return z&&z.Ke&&!z.Ke.isDeleted()?z.Ke:null}})})(r);
(function(a){function b(g){return(f(255*g[3])<<24|f(255*g[0])<<16|f(255*g[1])<<8|f(255*g[2])<<0)>>>0}function c(g){if(g&&g._ck)return g;if(g instanceof Float32Array){for(var d=Math.floor(g.length/4),h=new Uint32Array(d),m=0;m<d;m++)h[m]=b(g.slice(4*m,4*(m+1)));return h}if(g instanceof Uint32Array)return g;if(g instanceof Array&&g[0]instanceof Float32Array)return g.map(b)}function e(g){if(void 0===g)return 1;var d=parseFloat(g);return g&&-1!==g.indexOf("%")?d/100:d}function f(g){return Math.round(Math.max(0,
Math.min(g||0,255)))}function k(g,d){d&&d._ck||a._free(g)}function n(g,d,h){if(!g||!g.length)return 0;if(g&&g._ck)return g.byteOffset;var m=a[d].BYTES_PER_ELEMENT;h||=a._malloc(g.length*m);a[d].set(g,h/m);return h}function l(g){var d={ie:0,count:g.length,colorType:a.ColorType.RGBA_F32};if(g instanceof Float32Array)d.ie=n(g,"HEAPF32"),d.count=g.length/4;else if(g instanceof Uint32Array)d.ie=n(g,"HEAPU32"),d.colorType=a.ColorType.RGBA_8888;else if(g instanceof Array){if(g&&g.length){for(var h=a._malloc(16*
g.length),m=0,t=h/4,u=0;u<g.length;u++)for(var y=0;4>y;y++)a.HEAPF32[t+m]=g[u][y],m++;g=h}else g=0;d.ie=g}else throw"Invalid argument to copyFlexibleColorArray, Not a color array "+typeof g;return d}function p(g){if(!g)return 0;var d=da.toTypedArray();if(g.length){if(6===g.length||9===g.length)return n(g,"HEAPF32",P),6===g.length&&a.HEAPF32.set(Vc,6+P/4),P;if(16===g.length)return d[0]=g[0],d[1]=g[1],d[2]=g[3],d[3]=g[4],d[4]=g[5],d[5]=g[7],d[6]=g[12],d[7]=g[13],d[8]=g[15],P;throw"invalid matrix size";
}if(void 0===g.m11)throw"invalid matrix argument";d[0]=g.m11;d[1]=g.m21;d[2]=g.m41;d[3]=g.m12;d[4]=g.m22;d[5]=g.m42;d[6]=g.m14;d[7]=g.m24;d[8]=g.m44;return P}function v(g){if(!g)return 0;var d=Y.toTypedArray();if(g.length){if(16!==g.length&&6!==g.length&&9!==g.length)throw"invalid matrix size";if(16===g.length)return n(g,"HEAPF32",la);d.fill(0);d[0]=g[0];d[1]=g[1];d[3]=g[2];d[4]=g[3];d[5]=g[4];d[7]=g[5];d[10]=1;d[12]=g[6];d[13]=g[7];d[15]=g[8];6===g.length&&(d[12]=0,d[13]=0,d[15]=1);return la}if(void 0===
g.m11)throw"invalid matrix argument";d[0]=g.m11;d[1]=g.m21;d[2]=g.m31;d[3]=g.m41;d[4]=g.m12;d[5]=g.m22;d[6]=g.m32;d[7]=g.m42;d[8]=g.m13;d[9]=g.m23;d[10]=g.m33;d[11]=g.m43;d[12]=g.m14;d[13]=g.m24;d[14]=g.m34;d[15]=g.m44;return la}function w(g,d){return n(g,"HEAPF32",d||ha)}function A(g,d,h,m){var t=Ea.toTypedArray();t[0]=g;t[1]=d;t[2]=h;t[3]=m;return ha}function D(g){for(var d=new Float32Array(4),h=0;4>h;h++)d[h]=a.HEAPF32[g/4+h];return d}function I(g,d){return n(g,"HEAPF32",d||U)}function Q(g,d){return n(g,
"HEAPF32",d||tb)}a.Color=function(g,d,h,m){void 0===m&&(m=1);return a.Color4f(f(g)/255,f(d)/255,f(h)/255,m)};a.ColorAsInt=function(g,d,h,m){void 0===m&&(m=255);return(f(m)<<24|f(g)<<16|f(d)<<8|f(h)<<0&268435455)>>>0};a.Color4f=function(g,d,h,m){void 0===m&&(m=1);return Float32Array.of(g,d,h,m)};Object.defineProperty(a,"TRANSPARENT",{get:function(){return a.Color4f(0,0,0,0)}});Object.defineProperty(a,"BLACK",{get:function(){return a.Color4f(0,0,0,1)}});Object.defineProperty(a,"WHITE",{get:function(){return a.Color4f(1,
1,1,1)}});Object.defineProperty(a,"RED",{get:function(){return a.Color4f(1,0,0,1)}});Object.defineProperty(a,"GREEN",{get:function(){return a.Color4f(0,1,0,1)}});Object.defineProperty(a,"BLUE",{get:function(){return a.Color4f(0,0,1,1)}});Object.defineProperty(a,"YELLOW",{get:function(){return a.Color4f(1,1,0,1)}});Object.defineProperty(a,"CYAN",{get:function(){return a.Color4f(0,1,1,1)}});Object.defineProperty(a,"MAGENTA",{get:function(){return a.Color4f(1,0,1,1)}});a.getColorComponents=function(g){return[Math.floor(255*
g[0]),Math.floor(255*g[1]),Math.floor(255*g[2]),g[3]]};a.parseColorString=function(g,d){g=g.toLowerCase();if(g.startsWith("#")){d=255;switch(g.length){case 9:d=parseInt(g.slice(7,9),16);case 7:var h=parseInt(g.slice(1,3),16);var m=parseInt(g.slice(3,5),16);var t=parseInt(g.slice(5,7),16);break;case 5:d=17*parseInt(g.slice(4,5),16);case 4:h=17*parseInt(g.slice(1,2),16),m=17*parseInt(g.slice(2,3),16),t=17*parseInt(g.slice(3,4),16)}return a.Color(h,m,t,d/255)}return g.startsWith("rgba")?(g=g.slice(5,
-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],e(g[3]))):g.startsWith("rgb")?(g=g.slice(4,-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],e(g[3]))):g.startsWith("gray(")||g.startsWith("hsl")||!d||(g=d[g],void 0===g)?a.BLACK:g};a.multiplyByAlpha=function(g,d){g=g.slice();g[3]=Math.max(0,Math.min(g[3]*d,1));return g};a.Malloc=function(g,d){var h=a._malloc(d*g.BYTES_PER_ELEMENT);return{_ck:!0,length:d,byteOffset:h,re:null,subarray:function(m,t){m=this.toTypedArray().subarray(m,t);m._ck=!0;return m},toTypedArray:function(){if(this.re&&
this.re.length)return this.re;this.re=new g(a.HEAPU8.buffer,h,d);this.re._ck=!0;return this.re}}};a.Free=function(g){a._free(g.byteOffset);g.byteOffset=0;g.toTypedArray=null;g.re=null};var P=0,da,la=0,Y,ha=0,Ea,ea,U=0,Ub,Aa=0,Vb,ub=0,Wb,vb=0,$a,Ma=0,Xb,tb=0,Yb,Zb=0,Vc=Float32Array.of(0,0,1);a.onRuntimeInitialized=function(){function g(d,h,m,t,u,y,C){y||(y=4*t.width,t.colorType===a.ColorType.RGBA_F16?y*=2:t.colorType===a.ColorType.RGBA_F32&&(y*=4));var G=y*t.height;var F=u?u.byteOffset:a._malloc(G);
if(C?!d._readPixels(t,F,y,h,m,C):!d._readPixels(t,F,y,h,m))return u||a._free(F),null;if(u)return u.toTypedArray();switch(t.colorType){case a.ColorType.RGBA_8888:case a.ColorType.RGBA_F16:d=(new Uint8Array(a.HEAPU8.buffer,F,G)).slice();break;case a.ColorType.RGBA_F32:d=(new Float32Array(a.HEAPU8.buffer,F,G)).slice();break;default:return null}a._free(F);return d}Ea=a.Malloc(Float32Array,4);ha=Ea.byteOffset;Y=a.Malloc(Float32Array,16);la=Y.byteOffset;da=a.Malloc(Float32Array,9);P=da.byteOffset;Xb=a.Malloc(Float32Array,
12);tb=Xb.byteOffset;Yb=a.Malloc(Float32Array,12);Zb=Yb.byteOffset;ea=a.Malloc(Float32Array,4);U=ea.byteOffset;Ub=a.Malloc(Float32Array,4);Aa=Ub.byteOffset;Vb=a.Malloc(Float32Array,3);ub=Vb.byteOffset;Wb=a.Malloc(Float32Array,3);vb=Wb.byteOffset;$a=a.Malloc(Int32Array,4);Ma=$a.byteOffset;a.ColorSpace.SRGB=a.ColorSpace._MakeSRGB();a.ColorSpace.DISPLAY_P3=a.ColorSpace._MakeDisplayP3();a.ColorSpace.ADOBE_RGB=a.ColorSpace._MakeAdobeRGB();a.GlyphRunFlags={IsWhiteSpace:a._GlyphRunFlags_isWhiteSpace};a.Path.MakeFromCmds=
function(d){var h=n(d,"HEAPF32"),m=a.Path._MakeFromCmds(h,d.length);k(h,d);return m};a.Path.MakeFromVerbsPointsWeights=function(d,h,m){var t=n(d,"HEAPU8"),u=n(h,"HEAPF32"),y=n(m,"HEAPF32"),C=a.Path._MakeFromVerbsPointsWeights(t,d.length,u,h.length/2,y,m&&m.length||0);k(t,d);k(u,h);k(y,m);return C};a.PathBuilder.prototype.addArc=function(d,h,m){d=I(d);this._addArc(d,h,m);return this};a.PathBuilder.prototype.addCircle=function(d,h,m,t){this._addCircle(d,h,m,!!t);return this};a.PathBuilder.prototype.addOval=
function(d,h,m){void 0===m&&(m=1);d=I(d);this._addOval(d,!!h,m);return this};a.PathBuilder.prototype.addPath=function(){var d=Array.prototype.slice.call(arguments),h=d[0],m=!1;"boolean"===typeof d[d.length-1]&&(m=d.pop());if(1===d.length)this._addPath(h,1,0,0,0,1,0,0,0,1,m);else if(2===d.length)d=d[1],this._addPath(h,d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1,m);else if(7===d.length||10===d.length)this._addPath(h,d[1],d[2],d[3],d[4],d[5],d[6],d[7]||0,d[8]||0,d[9]||1,m);else return null;
return this};a.PathBuilder.prototype.addPolygon=function(d,h){var m=n(d,"HEAPF32");this._addPolygon(m,d.length/2,h);k(m,d);return this};a.PathBuilder.prototype.addRect=function(d,h){d=I(d);this._addRect(d,!!h);return this};a.PathBuilder.prototype.addRRect=function(d,h){d=Q(d);this._addRRect(d,!!h);return this};a.PathBuilder.prototype.addVerbsPointsWeights=function(d,h,m){var t=n(d,"HEAPU8"),u=n(h,"HEAPF32"),y=n(m,"HEAPF32");this._addVerbsPointsWeights(t,d.length,u,h.length/2,y,m&&m.length||0);k(t,
d);k(u,h);k(y,m);return this};a.PathBuilder.prototype.arc=function(d,h,m,t,u,y){d=a.LTRBRect(d-m,h-m,d+m,h+m);u=(u-t)/Math.PI*180-360*!!y;t=(new a.PathBuilder).addArc(d,t/Math.PI*180,u).detachAndDelete();this.addPath(t,!0);t.delete();return this};a.PathBuilder.prototype.arcToOval=function(d,h,m,t){d=I(d);this._arcToOval(d,h,m,t);return this};a.PathBuilder.prototype.arcToRotated=function(d,h,m,t,u,y,C){this._arcToRotated(d,h,m,!!t,!!u,y,C);return this};a.PathBuilder.prototype.arcToTangent=function(d,
h,m,t,u){this._arcToTangent(d,h,m,t,u);return this};a.PathBuilder.prototype.close=function(){this._close();return this};a.PathBuilder.prototype.conicTo=function(d,h,m,t,u){this._conicTo(d,h,m,t,u);return this};a.Path.prototype.computeTightBounds=function(d){this._computeTightBounds(U);var h=ea.toTypedArray();return d?(d.set(h),d):h.slice()};a.PathBuilder.prototype.cubicTo=function(d,h,m,t,u,y){this._cubicTo(d,h,m,t,u,y);return this};a.PathBuilder.prototype.detachAndDelete=function(){var d=this.detach();
this.delete();return d};a.Path.prototype.getBounds=function(d){this._getBounds(U);var h=ea.toTypedArray();return d?(d.set(h),d):h.slice()};a.PathBuilder.prototype.getBounds=function(d){this._getBounds(U);var h=ea.toTypedArray();return d?(d.set(h),d):h.slice()};a.PathBuilder.prototype.lineTo=function(d,h){this._lineTo(d,h);return this};a.PathBuilder.prototype.moveTo=function(d,h){this._moveTo(d,h);return this};a.PathBuilder.prototype.offset=function(d,h){this._transform(1,0,d,0,1,h,0,0,1);return this};
a.PathBuilder.prototype.quadTo=function(d,h,m,t){this._quadTo(d,h,m,t);return this};a.PathBuilder.prototype.rArcTo=function(d,h,m,t,u,y,C){this._rArcTo(d,h,m,t,u,y,C);return this};a.PathBuilder.prototype.rConicTo=function(d,h,m,t,u){this._rConicTo(d,h,m,t,u);return this};a.PathBuilder.prototype.rCubicTo=function(d,h,m,t,u,y){this._rCubicTo(d,h,m,t,u,y);return this};a.PathBuilder.prototype.rLineTo=function(d,h){this._rLineTo(d,h);return this};a.PathBuilder.prototype.rMoveTo=function(d,h){this._rMoveTo(d,
h);return this};a.PathBuilder.prototype.rQuadTo=function(d,h,m,t){this._rQuadTo(d,h,m,t);return this};a.Path.prototype.makeStroked=function(d){d=d||{};d.width=d.width||1;d.miter_limit=d.miter_limit||4;d.cap=d.cap||a.StrokeCap.Butt;d.join=d.join||a.StrokeJoin.Miter;d.precision=d.precision||1;return this._makeStroked(d)};a.PathBuilder.prototype.transform=function(){if(1===arguments.length){var d=arguments[0];this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1)}else if(6===arguments.length||
9===arguments.length)d=arguments,this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.Path.prototype.makeTrimmed=function(d,h,m){return this._makeTrimmed(d,h,!!m)};a.Image.prototype.encodeToBytes=function(d,h){var m=a.Ce();d=d||a.ImageFormat.PNG;h=h||100;return m?this._encodeToBytes(d,h,m):this._encodeToBytes(d,h)};a.Image.prototype.makeShaderCubic=function(d,h,m,t,u){u=p(u);return this._makeShaderCubic(d,
h,m,t,u)};a.Image.prototype.makeShaderOptions=function(d,h,m,t,u){u=p(u);return this._makeShaderOptions(d,h,m,t,u)};a.Image.prototype.readPixels=function(d,h,m,t,u){var y=a.Ce();return g(this,d,h,m,t,u,y)};a.Canvas.prototype.clear=function(d){a.ae(this.$d);d=w(d);this._clear(d)};a.Canvas.prototype.clipRRect=function(d,h,m){a.ae(this.$d);d=Q(d);this._clipRRect(d,h,m)};a.Canvas.prototype.clipRect=function(d,h,m){a.ae(this.$d);d=I(d);this._clipRect(d,h,m)};a.Canvas.prototype.concat=function(d){a.ae(this.$d);
d=v(d);this._concat(d)};a.Canvas.prototype.drawArc=function(d,h,m,t,u){a.ae(this.$d);d=I(d);this._drawArc(d,h,m,t,u)};a.Canvas.prototype.drawAtlas=function(d,h,m,t,u,y,C){if(d&&t&&h&&m&&h.length===m.length){a.ae(this.$d);u||(u=a.BlendMode.SrcOver);var G=n(h,"HEAPF32"),F=n(m,"HEAPF32"),S=m.length/4,T=n(c(y),"HEAPU32");if(C&&"B"in C&&"C"in C)this._drawAtlasCubic(d,F,G,T,S,u,C.B,C.C,t);else{let q=a.FilterMode.Linear,x=a.MipmapMode.None;C&&(q=C.filter,"mipmap"in C&&(x=C.mipmap));this._drawAtlasOptions(d,
F,G,T,S,u,q,x,t)}k(G,h);k(F,m);k(T,y)}};a.Canvas.prototype.drawCircle=function(d,h,m,t){a.ae(this.$d);this._drawCircle(d,h,m,t)};a.Canvas.prototype.drawColor=function(d,h){a.ae(this.$d);d=w(d);void 0!==h?this._drawColor(d,h):this._drawColor(d)};a.Canvas.prototype.drawColorInt=function(d,h){a.ae(this.$d);this._drawColorInt(d,h||a.BlendMode.SrcOver)};a.Canvas.prototype.drawColorComponents=function(d,h,m,t,u){a.ae(this.$d);d=A(d,h,m,t);void 0!==u?this._drawColor(d,u):this._drawColor(d)};a.Canvas.prototype.drawDRRect=
function(d,h,m){a.ae(this.$d);d=Q(d,tb);h=Q(h,Zb);this._drawDRRect(d,h,m)};a.Canvas.prototype.drawImage=function(d,h,m,t){a.ae(this.$d);this._drawImage(d,h,m,t||null)};a.Canvas.prototype.drawImageCubic=function(d,h,m,t,u,y){a.ae(this.$d);this._drawImageCubic(d,h,m,t,u,y||null)};a.Canvas.prototype.drawImageOptions=function(d,h,m,t,u,y){a.ae(this.$d);this._drawImageOptions(d,h,m,t,u,y||null)};a.Canvas.prototype.drawImageNine=function(d,h,m,t,u){a.ae(this.$d);h=n(h,"HEAP32",Ma);m=I(m);this._drawImageNine(d,
h,m,t,u||null)};a.Canvas.prototype.drawImageRect=function(d,h,m,t,u){a.ae(this.$d);I(h,U);I(m,Aa);this._drawImageRect(d,U,Aa,t,!!u)};a.Canvas.prototype.drawImageRectCubic=function(d,h,m,t,u,y){a.ae(this.$d);I(h,U);I(m,Aa);this._drawImageRectCubic(d,U,Aa,t,u,y||null)};a.Canvas.prototype.drawImageRectOptions=function(d,h,m,t,u,y){a.ae(this.$d);I(h,U);I(m,Aa);this._drawImageRectOptions(d,U,Aa,t,u,y||null)};a.Canvas.prototype.drawLine=function(d,h,m,t,u){a.ae(this.$d);this._drawLine(d,h,m,t,u)};a.Canvas.prototype.drawOval=
function(d,h){a.ae(this.$d);d=I(d);this._drawOval(d,h)};a.Canvas.prototype.drawPaint=function(d){a.ae(this.$d);this._drawPaint(d)};a.Canvas.prototype.drawParagraph=function(d,h,m){a.ae(this.$d);this._drawParagraph(d,h,m)};a.Canvas.prototype.drawPatch=function(d,h,m,t,u){if(24>d.length)throw"Need 12 cubic points";if(h&&4>h.length)throw"Need 4 colors";if(m&&8>m.length)throw"Need 4 shader coordinates";a.ae(this.$d);const y=n(d,"HEAPF32"),C=h?n(c(h),"HEAPU32"):0,G=m?n(m,"HEAPF32"):0;t||(t=a.BlendMode.Modulate);
this._drawPatch(y,C,G,t,u);k(G,m);k(C,h);k(y,d)};a.Canvas.prototype.drawPath=function(d,h){a.ae(this.$d);this._drawPath(d,h)};a.Canvas.prototype.drawPicture=function(d){a.ae(this.$d);this._drawPicture(d)};a.Canvas.prototype.drawPoints=function(d,h,m){a.ae(this.$d);var t=n(h,"HEAPF32");this._drawPoints(d,t,h.length/2,m);k(t,h)};a.Canvas.prototype.drawRRect=function(d,h){a.ae(this.$d);d=Q(d);this._drawRRect(d,h)};a.Canvas.prototype.drawRect=function(d,h){a.ae(this.$d);d=I(d);this._drawRect(d,h)};a.Canvas.prototype.drawRect4f=
function(d,h,m,t,u){a.ae(this.$d);this._drawRect4f(d,h,m,t,u)};a.Canvas.prototype.drawShadow=function(d,h,m,t,u,y,C){a.ae(this.$d);var G=n(u,"HEAPF32"),F=n(y,"HEAPF32");h=n(h,"HEAPF32",ub);m=n(m,"HEAPF32",vb);this._drawShadow(d,h,m,t,G,F,C);k(G,u);k(F,y)};a.getShadowLocalBounds=function(d,h,m,t,u,y,C){d=p(d);m=n(m,"HEAPF32",ub);t=n(t,"HEAPF32",vb);if(!this._getShadowLocalBounds(d,h,m,t,u,y,U))return null;h=ea.toTypedArray();return C?(C.set(h),C):h.slice()};a.Canvas.prototype.drawTextBlob=function(d,
h,m,t){a.ae(this.$d);this._drawTextBlob(d,h,m,t)};a.Canvas.prototype.drawVertices=function(d,h,m){a.ae(this.$d);this._drawVertices(d,h,m)};a.Canvas.prototype.getDeviceClipBounds=function(d){this._getDeviceClipBounds(Ma);var h=$a.toTypedArray();d?d.set(h):d=h.slice();return d};a.Canvas.prototype.quickReject=function(d){d=I(d);return this._quickReject(d)};a.Canvas.prototype.getLocalToDevice=function(){this._getLocalToDevice(la);for(var d=la,h=Array(16),m=0;16>m;m++)h[m]=a.HEAPF32[d/4+m];return h};a.Canvas.prototype.getTotalMatrix=
function(){this._getTotalMatrix(P);for(var d=Array(9),h=0;9>h;h++)d[h]=a.HEAPF32[P/4+h];return d};a.Canvas.prototype.makeSurface=function(d){d=this._makeSurface(d);d.$d=this.$d;return d};a.Canvas.prototype.readPixels=function(d,h,m,t,u){a.ae(this.$d);return g(this,d,h,m,t,u)};a.Canvas.prototype.saveLayer=function(d,h,m,t,u){h=I(h);return this._saveLayer(d||null,h,m||null,t||0,u||a.TileMode.Clamp)};a.Canvas.prototype.writePixels=function(d,h,m,t,u,y,C,G){if(d.byteLength%(h*m))throw"pixels length must be a multiple of the srcWidth * srcHeight";
a.ae(this.$d);var F=d.byteLength/(h*m);y=y||a.AlphaType.Unpremul;C=C||a.ColorType.RGBA_8888;G=G||a.ColorSpace.SRGB;var S=F*h;F=n(d,"HEAPU8");h=this._writePixels({width:h,height:m,colorType:C,alphaType:y,colorSpace:G},F,S,t,u);k(F,d);return h};a.ColorFilter.MakeBlend=function(d,h,m){d=w(d);m=m||a.ColorSpace.SRGB;return a.ColorFilter._MakeBlend(d,h,m)};a.ColorFilter.MakeMatrix=function(d){if(!d||20!==d.length)throw"invalid color matrix";var h=n(d,"HEAPF32"),m=a.ColorFilter._makeMatrix(h);k(h,d);return m};
a.ContourMeasure.prototype.getPosTan=function(d,h){this._getPosTan(d,U);d=ea.toTypedArray();return h?(h.set(d),h):d.slice()};a.ImageFilter.prototype.getOutputBounds=function(d,h,m){d=I(d,U);h=p(h);this._getOutputBounds(d,h,Ma);h=$a.toTypedArray();return m?(m.set(h),m):h.slice()};a.ImageFilter.MakeDropShadow=function(d,h,m,t,u,y){u=w(u,ha);return a.ImageFilter._MakeDropShadow(d,h,m,t,u,y)};a.ImageFilter.MakeDropShadowOnly=function(d,h,m,t,u,y){u=w(u,ha);return a.ImageFilter._MakeDropShadowOnly(d,h,
m,t,u,y)};a.ImageFilter.MakeImage=function(d,h,m,t){m=I(m,U);t=I(t,Aa);if("B"in h&&"C"in h)return a.ImageFilter._MakeImageCubic(d,h.B,h.C,m,t);const u=h.filter;let y=a.MipmapMode.None;"mipmap"in h&&(y=h.mipmap);return a.ImageFilter._MakeImageOptions(d,u,y,m,t)};a.ImageFilter.MakeMatrixTransform=function(d,h,m){d=p(d);if("B"in h&&"C"in h)return a.ImageFilter._MakeMatrixTransformCubic(d,h.B,h.C,m);const t=h.filter;let u=a.MipmapMode.None;"mipmap"in h&&(u=h.mipmap);return a.ImageFilter._MakeMatrixTransformOptions(d,
t,u,m)};a.Paint.prototype.getColor=function(){this._getColor(ha);return D(ha)};a.Paint.prototype.setColor=function(d,h){h=h||null;d=w(d);this._setColor(d,h)};a.Paint.prototype.setColorComponents=function(d,h,m,t,u){u=u||null;d=A(d,h,m,t);this._setColor(d,u)};a.Path.prototype.getPoint=function(d,h){this._getPoint(d,U);d=ea.toTypedArray();return h?(h[0]=d[0],h[1]=d[1],h):d.slice(0,2)};a.Picture.prototype.makeShader=function(d,h,m,t,u){t=p(t);u=I(u);return this._makeShader(d,h,m,t,u)};a.Picture.prototype.cullRect=
function(d){this._cullRect(U);var h=ea.toTypedArray();return d?(d.set(h),d):h.slice()};a.PictureRecorder.prototype.beginRecording=function(d,h){d=I(d);return this._beginRecording(d,!!h)};a.Surface.prototype.getCanvas=function(){var d=this._getCanvas();d.$d=this.$d;return d};a.Surface.prototype.makeImageSnapshot=function(d){a.ae(this.$d);d=n(d,"HEAP32",Ma);return this._makeImageSnapshot(d)};a.Surface.prototype.makeSurface=function(d){a.ae(this.$d);d=this._makeSurface(d);d.$d=this.$d;return d};a.Surface.prototype.$e=
function(d,h){this.ue||(this.ue=this.getCanvas());return requestAnimationFrame(function(){a.ae(this.$d);d(this.ue);this.flush(h)}.bind(this))};a.Surface.prototype.requestAnimationFrame||(a.Surface.prototype.requestAnimationFrame=a.Surface.prototype.$e);a.Surface.prototype.Xe=function(d,h){this.ue||(this.ue=this.getCanvas());requestAnimationFrame(function(){a.ae(this.$d);d(this.ue);this.flush(h);this.dispose()}.bind(this))};a.Surface.prototype.drawOnce||(a.Surface.prototype.drawOnce=a.Surface.prototype.Xe);
a.PathEffect.MakeDash=function(d,h){h||=0;if(!d.length||1===d.length%2)throw"Intervals array must have even length";var m=n(d,"HEAPF32");h=a.PathEffect._MakeDash(m,d.length,h);k(m,d);return h};a.PathEffect.MakeLine2D=function(d,h){h=p(h);return a.PathEffect._MakeLine2D(d,h)};a.PathEffect.MakePath2D=function(d,h){d=p(d);return a.PathEffect._MakePath2D(d,h)};a.Shader.MakeColor=function(d,h){h=h||null;d=w(d);return a.Shader._MakeColor(d,h)};a.Shader.Blend=a.Shader.MakeBlend;a.Shader.Color=a.Shader.MakeColor;
a.Shader.MakeLinearGradient=function(d,h,m,t,u,y,C,G){G=G||null;var F=l(m),S=n(t,"HEAPF32");C=C||0;y=p(y);var T=ea.toTypedArray();T.set(d);T.set(h,2);d=a.Shader._MakeLinearGradient(U,F.ie,F.colorType,S,F.count,u,C,y,G);k(F.ie,m);t&&k(S,t);return d};a.Shader.MakeRadialGradient=function(d,h,m,t,u,y,C,G){G=G||null;var F=l(m),S=n(t,"HEAPF32");C=C||0;y=p(y);d=a.Shader._MakeRadialGradient(d[0],d[1],h,F.ie,F.colorType,S,F.count,u,C,y,G);k(F.ie,m);t&&k(S,t);return d};a.Shader.MakeSweepGradient=function(d,
h,m,t,u,y,C,G,F,S){S=S||null;var T=l(m),q=n(t,"HEAPF32");C=C||0;G=G||0;F=F||360;y=p(y);d=a.Shader._MakeSweepGradient(d,h,T.ie,T.colorType,q,T.count,u,G,F,C,y,S);k(T.ie,m);t&&k(q,t);return d};a.Shader.MakeTwoPointConicalGradient=function(d,h,m,t,u,y,C,G,F,S){S=S||null;var T=l(u),q=n(y,"HEAPF32");F=F||0;G=p(G);var x=ea.toTypedArray();x.set(d);x.set(m,2);d=a.Shader._MakeTwoPointConicalGradient(U,h,t,T.ie,T.colorType,q,T.count,C,F,G,S);k(T.ie,u);y&&k(q,y);return d};a.Vertices.prototype.bounds=function(d){this._bounds(U);
var h=ea.toTypedArray();return d?(d.set(h),d):h.slice()};a.de&&a.de.forEach(function(d){d()})};a.computeTonalColors=function(g){var d=n(g.ambient,"HEAPF32"),h=n(g.spot,"HEAPF32");this._computeTonalColors(d,h);var m={ambient:D(d),spot:D(h)};k(d,g.ambient);k(h,g.spot);return m};a.LTRBRect=function(g,d,h,m){return Float32Array.of(g,d,h,m)};a.XYWHRect=function(g,d,h,m){return Float32Array.of(g,d,g+h,d+m)};a.LTRBiRect=function(g,d,h,m){return Int32Array.of(g,d,h,m)};a.XYWHiRect=function(g,d,h,m){return Int32Array.of(g,
d,g+h,d+m)};a.RRectXY=function(g,d,h){return Float32Array.of(g[0],g[1],g[2],g[3],d,h,d,h,d,h,d,h)};a.MakeAnimatedImageFromEncoded=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._decodeAnimatedImage(d,g.byteLength))?g:null};a.MakeImageFromEncoded=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._decodeImage(d,g.byteLength))?g:null};var ab=null;a.MakeImageFromCanvasImageSource=function(g){var d=g.width,h=g.height;
ab||=document.createElement("canvas");ab.width=d;ab.height=h;var m=ab.getContext("2d",{willReadFrequently:!0});m.drawImage(g,0,0);g=m.getImageData(0,0,d,h);return a.MakeImage({width:d,height:h,alphaType:a.AlphaType.Unpremul,colorType:a.ColorType.RGBA_8888,colorSpace:a.ColorSpace.SRGB},g.data,4*d)};a.MakeImage=function(g,d,h){var m=a._malloc(d.length);a.HEAPU8.set(d,m);return a._MakeImage(g,m,d.length,h)};a.MakeVertices=function(g,d,h,m,t,u){var y=t&&t.length||0,C=0;h&&h.length&&(C|=1);m&&m.length&&
(C|=2);void 0===u||u||(C|=4);g=new a._VerticesBuilder(g,d.length/2,y,C);n(d,"HEAPF32",g.positions());g.texCoords()&&n(h,"HEAPF32",g.texCoords());g.colors()&&n(c(m),"HEAPU32",g.colors());g.indices()&&n(t,"HEAPU16",g.indices());return g.detach()};(function(g){g.de=g.de||[];g.de.push(function(){function d(q){q&&(q.dir=0===q.dir?g.TextDirection.RTL:g.TextDirection.LTR);return q}function h(q){if(!q||!q.length)return[];for(var x=[],M=0;M<q.length;M+=5){var W=g.LTRBRect(q[M],q[M+1],q[M+2],q[M+3]),wa=g.TextDirection.LTR;
0===q[M+4]&&(wa=g.TextDirection.RTL);x.push({rect:W,dir:wa})}g._free(q.byteOffset);return x}function m(q){q=q||{};void 0===q.weight&&(q.weight=g.FontWeight.Normal);q.width=q.width||g.FontWidth.Normal;q.slant=q.slant||g.FontSlant.Upright;return q}function t(q){if(!q||!q.length)return 0;for(var x=[],M=0;M<q.length;M++){var W=u(q[M]);x.push(W)}return n(x,"HEAPU32")}function u(q){if(G[q])return G[q];var x=qa(q)+1,M=g._malloc(x);ra(q,M,x);return G[q]=M}function y(q){q._colorPtr=w(q.color);q._foregroundColorPtr=
0;q._backgroundColorPtr=0;q._decorationColorPtr=0;q.foregroundColor&&(q._foregroundColorPtr=w(q.foregroundColor,F));q.backgroundColor&&(q._backgroundColorPtr=w(q.backgroundColor,S));q.decorationColor&&(q._decorationColorPtr=w(q.decorationColor,T));Array.isArray(q.fontFamilies)&&q.fontFamilies.length?(q._fontFamiliesPtr=t(q.fontFamilies),q._fontFamiliesLen=q.fontFamilies.length):(q._fontFamiliesPtr=0,q._fontFamiliesLen=0);if(q.locale){var x=q.locale;q._localePtr=u(x);q._localeLen=qa(x)}else q._localePtr=
0,q._localeLen=0;if(Array.isArray(q.shadows)&&q.shadows.length){x=q.shadows;var M=x.map(function(ma){return ma.color||g.BLACK}),W=x.map(function(ma){return ma.blurRadius||0});q._shadowLen=x.length;for(var wa=g._malloc(8*x.length),wb=wa/4,xb=0;xb<x.length;xb++){var $b=x[xb].offset||[0,0];g.HEAPF32[wb]=$b[0];g.HEAPF32[wb+1]=$b[1];wb+=2}q._shadowColorsPtr=l(M).ie;q._shadowOffsetsPtr=wa;q._shadowBlurRadiiPtr=n(W,"HEAPF32")}else q._shadowLen=0,q._shadowColorsPtr=0,q._shadowOffsetsPtr=0,q._shadowBlurRadiiPtr=
0;Array.isArray(q.fontFeatures)&&q.fontFeatures.length?(x=q.fontFeatures,M=x.map(function(ma){return ma.name}),W=x.map(function(ma){return ma.value}),q._fontFeatureLen=x.length,q._fontFeatureNamesPtr=t(M),q._fontFeatureValuesPtr=n(W,"HEAPU32")):(q._fontFeatureLen=0,q._fontFeatureNamesPtr=0,q._fontFeatureValuesPtr=0);Array.isArray(q.fontVariations)&&q.fontVariations.length?(x=q.fontVariations,M=x.map(function(ma){return ma.axis}),W=x.map(function(ma){return ma.value}),q._fontVariationLen=x.length,
q._fontVariationAxesPtr=t(M),q._fontVariationValuesPtr=n(W,"HEAPF32")):(q._fontVariationLen=0,q._fontVariationAxesPtr=0,q._fontVariationValuesPtr=0)}function C(q){g._free(q._fontFamiliesPtr);g._free(q._shadowColorsPtr);g._free(q._shadowOffsetsPtr);g._free(q._shadowBlurRadiiPtr);g._free(q._fontFeatureNamesPtr);g._free(q._fontFeatureValuesPtr);g._free(q._fontVariationAxesPtr);g._free(q._fontVariationValuesPtr)}g.Paragraph.prototype.getRectsForRange=function(q,x,M,W){q=this._getRectsForRange(q,x,M,W);
return h(q)};g.Paragraph.prototype.getRectsForPlaceholders=function(){var q=this._getRectsForPlaceholders();return h(q)};g.Paragraph.prototype.getGlyphInfoAt=function(q){return d(this._getGlyphInfoAt(q))};g.Paragraph.prototype.getClosestGlyphInfoAtCoordinate=function(q,x){return d(this._getClosestGlyphInfoAtCoordinate(q,x))};g.TypefaceFontProvider.prototype.registerFont=function(q,x){q=g.Typeface.MakeTypefaceFromData(q);if(!q)return null;x=u(x);this._registerFont(q,x);q.delete()};g.ParagraphStyle=
function(q){q.disableHinting=q.disableHinting||!1;if(q.ellipsis){var x=q.ellipsis;q._ellipsisPtr=u(x);q._ellipsisLen=qa(x)}else q._ellipsisPtr=0,q._ellipsisLen=0;null==q.heightMultiplier&&(q.heightMultiplier=-1);q.maxLines=q.maxLines||0;q.replaceTabCharacters=q.replaceTabCharacters||!1;x=(x=q.strutStyle)||{};x.strutEnabled=x.strutEnabled||!1;x.strutEnabled&&Array.isArray(x.fontFamilies)&&x.fontFamilies.length?(x._fontFamiliesPtr=t(x.fontFamilies),x._fontFamiliesLen=x.fontFamilies.length):(x._fontFamiliesPtr=
0,x._fontFamiliesLen=0);x.fontStyle=m(x.fontStyle);null==x.fontSize&&(x.fontSize=-1);null==x.heightMultiplier&&(x.heightMultiplier=-1);x.halfLeading=x.halfLeading||!1;x.leading=x.leading||0;x.forceStrutHeight=x.forceStrutHeight||!1;q.strutStyle=x;q.textAlign=q.textAlign||g.TextAlign.Start;q.textDirection=q.textDirection||g.TextDirection.LTR;q.textHeightBehavior=q.textHeightBehavior||g.TextHeightBehavior.All;q.textStyle=g.TextStyle(q.textStyle);q.applyRoundingHack=!1!==q.applyRoundingHack;return q};
g.TextStyle=function(q){q.color||(q.color=g.BLACK);q.decoration=q.decoration||0;q.decorationThickness=q.decorationThickness||0;q.decorationStyle=q.decorationStyle||g.DecorationStyle.Solid;q.textBaseline=q.textBaseline||g.TextBaseline.Alphabetic;null==q.fontSize&&(q.fontSize=-1);q.letterSpacing=q.letterSpacing||0;q.wordSpacing=q.wordSpacing||0;null==q.heightMultiplier&&(q.heightMultiplier=-1);q.halfLeading=q.halfLeading||!1;q.fontStyle=m(q.fontStyle);return q};var G={},F=g._malloc(16),S=g._malloc(16),
T=g._malloc(16);g.ParagraphBuilder.Make=function(q,x){y(q.textStyle);x=g.ParagraphBuilder._Make(q,x);C(q.textStyle);return x};g.ParagraphBuilder.MakeFromFontProvider=function(q,x){y(q.textStyle);x=g.ParagraphBuilder._MakeFromFontProvider(q,x);C(q.textStyle);return x};g.ParagraphBuilder.MakeFromFontCollection=function(q,x){y(q.textStyle);x=g.ParagraphBuilder._MakeFromFontCollection(q,x);C(q.textStyle);return x};g.ParagraphBuilder.ShapeText=function(q,x,M){let W=0;for(const wa of x)W+=wa.length;if(W!==
q.length)throw"Accumulated block lengths must equal text.length";return g.ParagraphBuilder._ShapeText(q,x,M)};g.ParagraphBuilder.prototype.pushStyle=function(q){y(q);this._pushStyle(q);C(q)};g.ParagraphBuilder.prototype.pushPaintStyle=function(q,x,M){y(q);this._pushPaintStyle(q,x,M);C(q)};g.ParagraphBuilder.prototype.addPlaceholder=function(q,x,M,W,wa){M=M||g.PlaceholderAlignment.Baseline;W=W||g.TextBaseline.Alphabetic;this._addPlaceholder(q||0,x||0,M,W,wa||0)};g.ParagraphBuilder.prototype.setWordsUtf8=
function(q){var x=n(q,"HEAPU32");this._setWordsUtf8(x,q&&q.length||0);k(x,q)};g.ParagraphBuilder.prototype.setWordsUtf16=function(q){var x=n(q,"HEAPU32");this._setWordsUtf16(x,q&&q.length||0);k(x,q)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf8=function(q){var x=n(q,"HEAPU32");this._setGraphemeBreaksUtf8(x,q&&q.length||0);k(x,q)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf16=function(q){var x=n(q,"HEAPU32");this._setGraphemeBreaksUtf16(x,q&&q.length||0);k(x,q)};g.ParagraphBuilder.prototype.setLineBreaksUtf8=
function(q){var x=n(q,"HEAPU32");this._setLineBreaksUtf8(x,q&&q.length||0);k(x,q)};g.ParagraphBuilder.prototype.setLineBreaksUtf16=function(q){var x=n(q,"HEAPU32");this._setLineBreaksUtf16(x,q&&q.length||0);k(x,q)}})})(r);a.de=a.de||[];a.de.push(function(){});a.de=a.de||[];a.de.push(function(){a.Canvas.prototype.drawText=function(g,d,h,m,t){var u=qa(g),y=a._malloc(u+1);ra(g,y,u+1);this._drawSimpleText(y,u,d,h,t,m);a._free(y)};a.Canvas.prototype.drawGlyphs=function(g,d,h,m,t,u){if(!(2*g.length<=d.length))throw"Not enough positions for the array of gyphs";
a.ae(this.$d);const y=n(g,"HEAPU16"),C=n(d,"HEAPF32");this._drawGlyphs(g.length,y,C,h,m,t,u);k(C,d);k(y,g)};a.Font.prototype.getGlyphBounds=function(g,d,h){var m=n(g,"HEAPU16"),t=a._malloc(16*g.length);this._getGlyphWidthBounds(m,g.length,0,t,d||null);d=new Float32Array(a.HEAPU8.buffer,t,4*g.length);k(m,g);if(h)return h.set(d),a._free(t),h;g=Float32Array.from(d);a._free(t);return g};a.Font.prototype.getGlyphIDs=function(g,d,h){d||(d=g.length);var m=qa(g)+1,t=a._malloc(m);ra(g,t,m);g=a._malloc(2*d);
d=this._getGlyphIDs(t,m-1,d,g);a._free(t);if(0>d)return a._free(g),null;t=new Uint16Array(a.HEAPU8.buffer,g,d);if(h)return h.set(t),a._free(g),h;h=Uint16Array.from(t);a._free(g);return h};a.Font.prototype.getGlyphIntercepts=function(g,d,h,m){var t=n(g,"HEAPU16"),u=n(d,"HEAPF32");return this._getGlyphIntercepts(t,g.length,!(g&&g._ck),u,d.length,!(d&&d._ck),h,m)};a.Font.prototype.getGlyphWidths=function(g,d,h){var m=n(g,"HEAPU16"),t=a._malloc(4*g.length);this._getGlyphWidthBounds(m,g.length,t,0,d||
null);d=new Float32Array(a.HEAPU8.buffer,t,g.length);k(m,g);if(h)return h.set(d),a._free(t),h;g=Float32Array.from(d);a._free(t);return g};a.FontMgr.FromData=function(){if(!arguments.length)return null;var g=arguments;1===g.length&&Array.isArray(g[0])&&(g=arguments[0]);if(!g.length)return null;for(var d=[],h=[],m=0;m<g.length;m++){var t=new Uint8Array(g[m]),u=n(t,"HEAPU8");d.push(u);h.push(t.byteLength)}d=n(d,"HEAPU32");h=n(h,"HEAPU32");g=a.FontMgr._fromData(d,h,g.length);a._free(d);a._free(h);return g};
a.Typeface.MakeTypefaceFromData=function(g){g=new Uint8Array(g);var d=n(g,"HEAPU8");return(g=a.Typeface._MakeTypefaceFromData(d,g.byteLength))?g:null};a.Typeface.MakeFreeTypeFaceFromData=a.Typeface.MakeTypefaceFromData;a.Typeface.prototype.getGlyphIDs=function(g,d,h){d||(d=g.length);var m=qa(g)+1,t=a._malloc(m);ra(g,t,m);g=a._malloc(2*d);d=this._getGlyphIDs(t,m-1,d,g);a._free(t);if(0>d)return a._free(g),null;t=new Uint16Array(a.HEAPU8.buffer,g,d);if(h)return h.set(t),a._free(g),h;h=Uint16Array.from(t);
a._free(g);return h};a.TextBlob.MakeOnPath=function(g,d,h,m){if(g&&g.length&&d&&d.countPoints()){if(1===d.countPoints())return this.MakeFromText(g,h);m||=0;var t=h.getGlyphIDs(g);t=h.getGlyphWidths(t);var u=[];d=new a.ContourMeasureIter(d,!1,1);for(var y=d.next(),C=new Float32Array(4),G=0;G<g.length&&y;G++){var F=t[G];m+=F/2;if(m>y.length()){y.delete();y=d.next();if(!y){g=g.substring(0,G);break}m=F/2}y.getPosTan(m,C);var S=C[2],T=C[3];u.push(S,T,C[0]-F/2*S,C[1]-F/2*T);m+=F/2}g=this.MakeFromRSXform(g,
u,h);y&&y.delete();d.delete();return g}};a.TextBlob.MakeFromRSXform=function(g,d,h){var m=qa(g)+1,t=a._malloc(m);ra(g,t,m);g=n(d,"HEAPF32");h=a.TextBlob._MakeFromRSXform(t,m-1,g,h);a._free(t);return h?h:null};a.TextBlob.MakeFromRSXformGlyphs=function(g,d,h){var m=n(g,"HEAPU16");d=n(d,"HEAPF32");h=a.TextBlob._MakeFromRSXformGlyphs(m,2*g.length,d,h);k(m,g);return h?h:null};a.TextBlob.MakeFromGlyphs=function(g,d){var h=n(g,"HEAPU16");d=a.TextBlob._MakeFromGlyphs(h,2*g.length,d);k(h,g);return d?d:null};
a.TextBlob.MakeFromText=function(g,d){var h=qa(g)+1,m=a._malloc(h);ra(g,m,h);g=a.TextBlob._MakeFromText(m,h-1,d);a._free(m);return g?g:null};a.MallocGlyphIDs=function(g){return a.Malloc(Uint16Array,g)}});a.de=a.de||[];a.de.push(function(){a.MakePicture=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._MakePicture(d,g.byteLength))?g:null}});a.de=a.de||[];a.de.push(function(){a.RuntimeEffect.Make=function(g,d){return a.RuntimeEffect._Make(g,{onError:d||function(h){console.log("RuntimeEffect error",
h)}})};a.RuntimeEffect.MakeForBlender=function(g,d){return a.RuntimeEffect._MakeForBlender(g,{onError:d||function(h){console.log("RuntimeEffect error",h)}})};a.RuntimeEffect.prototype.makeShader=function(g,d){var h=!g._ck,m=n(g,"HEAPF32");d=p(d);return this._makeShader(m,4*g.length,h,d)};a.RuntimeEffect.prototype.makeShaderWithChildren=function(g,d,h){var m=!g._ck,t=n(g,"HEAPF32");h=p(h);for(var u=[],y=0;y<d.length;y++)u.push(d[y].Zd.be);d=n(u,"HEAPU32");return this._makeShaderWithChildren(t,4*g.length,
m,d,u.length,h)};a.RuntimeEffect.prototype.makeBlender=function(g){var d=!g._ck,h=n(g,"HEAPF32");return this._makeBlender(h,4*g.length,d)}})})(r);var sa=Object.assign({},r),ta="",ua,va;
if(fa||ia)ia?ta=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ta=document.currentScript.src),_scriptName&&(ta=_scriptName),ta.startsWith("blob:")?ta="":ta=ta.substr(0,ta.replace(/[?#].*/,"").lastIndexOf("/")+1),ia&&(va=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ua=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));
var xa=console.log.bind(console),ya=console.error.bind(console);Object.assign(r,sa);sa=null;var za,Ba=!1,Ca,B,Da,Fa,E,H,J,Ga;function Ha(){var a=za.buffer;r.HEAP8=Ca=new Int8Array(a);r.HEAP16=Da=new Int16Array(a);r.HEAPU8=B=new Uint8Array(a);r.HEAPU16=Fa=new Uint16Array(a);r.HEAP32=E=new Int32Array(a);r.HEAPU32=H=new Uint32Array(a);r.HEAPF32=J=new Float32Array(a);r.HEAPF64=Ga=new Float64Array(a)}var Ia=[],Ja=[],Ka=[],La=0,Na=null,Oa=null;
function Pa(a){a="Aborted("+a+")";ya(a);Ba=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Qa=a=>a.startsWith("data:application/octet-stream;base64,"),Ra;function Sa(a){return ua(a).then(b=>new Uint8Array(b),()=>{if(va)var b=va(a);else throw"both async and sync fetching of the wasm failed";return b})}function Ta(a,b,c){return Sa(a).then(e=>WebAssembly.instantiate(e,b)).then(c,e=>{ya(`failed to asynchronously prepare wasm: ${e}`);Pa(e)})}
function Ua(a,b){var c=Ra;return"function"!=typeof WebAssembly.instantiateStreaming||Qa(c)||"function"!=typeof fetch?Ta(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(f){ya(`wasm streaming compile failed: ${f}`);ya("falling back to ArrayBuffer instantiation");return Ta(c,a,b)}))}function Va(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Wa=a=>{a.forEach(b=>b(r))},Xa=r.noExitRuntime||!0;
class Ya{constructor(a){this.be=a-24}}
var Za=0,bb=0,cb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,db=(a,b=0,c=NaN)=>{var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&cb)return cb.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var n=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|n:(f&7)<<18|k<<12|n<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e},
eb={},fb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function gb(a){return this.fromWireType(H[a>>2])}
var hb={},ib={},jb={},kb,mb=(a,b,c)=>{function e(l){l=c(l);if(l.length!==a.length)throw new kb("Mismatched type converter count");for(var p=0;p<a.length;++p)lb(a[p],l[p])}a.forEach(l=>jb[l]=b);var f=Array(b.length),k=[],n=0;b.forEach((l,p)=>{ib.hasOwnProperty(l)?f[p]=ib[l]:(k.push(l),hb.hasOwnProperty(l)||(hb[l]=[]),hb[l].push(()=>{f[p]=ib[l];++n;n===k.length&&e(f)}))});0===k.length&&e(f)},nb,K=a=>{for(var b="";B[a];)b+=nb[B[a++]];return b},L;
function ob(a,b,c={}){var e=b.name;if(!a)throw new L(`type "${e}" must have a positive integer typeid pointer`);if(ib.hasOwnProperty(a)){if(c.mf)return;throw new L(`Cannot register type '${e}' twice`);}ib[a]=b;delete jb[a];hb.hasOwnProperty(a)&&(b=hb[a],delete hb[a],b.forEach(f=>f()))}function lb(a,b,c={}){return ob(a,b,c)}
var pb=a=>{throw new L(a.Zd.ee.ce.name+" instance already deleted");},qb=!1,rb=()=>{},sb=(a,b,c)=>{if(b===c)return a;if(void 0===c.he)return null;a=sb(a,b,c.he);return null===a?null:c.df(a)},yb={},zb={},Ab=(a,b)=>{if(void 0===b)throw new L("ptr should not be undefined");for(;a.he;)b=a.ze(b),a=a.he;return zb[b]},Cb=(a,b)=>{if(!b.ee||!b.be)throw new kb("makeClassHandle requires ptr and ptrType");if(!!b.je!==!!b.fe)throw new kb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Bb(Object.create(a,
{Zd:{value:b,writable:!0}}))},Bb=a=>{if("undefined"===typeof FinalizationRegistry)return Bb=b=>b,a;qb=new FinalizationRegistry(b=>{b=b.Zd;--b.count.value;0===b.count.value&&(b.fe?b.je.oe(b.fe):b.ee.ce.oe(b.be))});Bb=b=>{var c=b.Zd;c.fe&&qb.register(b,{Zd:c},b);return b};rb=b=>{qb.unregister(b)};return Bb(a)},Db=[];function Eb(){}
var Fb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Gb=(a,b,c)=>{if(void 0===a[b].ge){var e=a[b];a[b]=function(...f){if(!a[b].ge.hasOwnProperty(f.length))throw new L(`Function '${c}' called with an invalid number of arguments (${f.length}) - expects one of (${a[b].ge})!`);return a[b].ge[f.length].apply(this,f)};a[b].ge=[];a[b].ge[e.pe]=e}},Hb=(a,b,c)=>{if(r.hasOwnProperty(a)){if(void 0===c||void 0!==r[a].ge&&void 0!==r[a].ge[c])throw new L(`Cannot register public name '${a}' twice`);Gb(r,a,a);
if(r[a].ge.hasOwnProperty(c))throw new L(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);r[a].ge[c]=b}else r[a]=b,r[a].pe=c},Ib=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Jb(a,b,c,e,f,k,n,l){this.name=a;this.constructor=b;this.te=c;this.oe=e;this.he=f;this.gf=k;this.ze=n;this.df=l;this.qf=[]}
var Kb=(a,b,c)=>{for(;b!==c;){if(!b.ze)throw new L(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ze(a);b=b.he}return a};function Lb(a,b){if(null===b){if(this.Le)throw new L(`null is not a valid ${this.name}`);return 0}if(!b.Zd)throw new L(`Cannot pass "${Mb(b)}" as a ${this.name}`);if(!b.Zd.be)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);return Kb(b.Zd.be,b.Zd.ee.ce,this.ce)}
function Nb(a,b){if(null===b){if(this.Le)throw new L(`null is not a valid ${this.name}`);if(this.Ee){var c=this.Me();null!==a&&a.push(this.oe,c);return c}return 0}if(!b||!b.Zd)throw new L(`Cannot pass "${Mb(b)}" as a ${this.name}`);if(!b.Zd.be)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.De&&b.Zd.ee.De)throw new L(`Cannot convert argument of type ${b.Zd.je?b.Zd.je.name:b.Zd.ee.name} to parameter type ${this.name}`);c=Kb(b.Zd.be,b.Zd.ee.ce,this.ce);if(this.Ee){if(void 0===
b.Zd.fe)throw new L("Passing raw pointer to smart pointer is illegal");switch(this.vf){case 0:if(b.Zd.je===this)c=b.Zd.fe;else throw new L(`Cannot convert argument of type ${b.Zd.je?b.Zd.je.name:b.Zd.ee.name} to parameter type ${this.name}`);break;case 1:c=b.Zd.fe;break;case 2:if(b.Zd.je===this)c=b.Zd.fe;else{var e=b.clone();c=this.rf(c,Ob(()=>e["delete"]()));null!==a&&a.push(this.oe,c)}break;default:throw new L("Unsupporting sharing policy");}}return c}
function Pb(a,b){if(null===b){if(this.Le)throw new L(`null is not a valid ${this.name}`);return 0}if(!b.Zd)throw new L(`Cannot pass "${Mb(b)}" as a ${this.name}`);if(!b.Zd.be)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Zd.ee.De)throw new L(`Cannot convert argument of type ${b.Zd.ee.name} to parameter type ${this.name}`);return Kb(b.Zd.be,b.Zd.ee.ce,this.ce)}
function Qb(a,b,c,e,f,k,n,l,p,v,w){this.name=a;this.ce=b;this.Le=c;this.De=e;this.Ee=f;this.pf=k;this.vf=n;this.Te=l;this.Me=p;this.rf=v;this.oe=w;f||void 0!==b.he?this.toWireType=Nb:(this.toWireType=e?Lb:Pb,this.le=null)}
var Rb=(a,b,c)=>{if(!r.hasOwnProperty(a))throw new kb("Replacing nonexistent public symbol");void 0!==r[a].ge&&void 0!==c?r[a].ge[c]=b:(r[a]=b,r[a].pe=c)},N,Sb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,r["dynCall_"+a])(b,...c)):b=N.get(b)(...c);return b},Tb=(a,b)=>(...c)=>Sb(a,b,c),O=(a,b)=>{a=K(a);var c=a.includes("j")?Tb(a,b):N.get(b);if("function"!=typeof c)throw new L(`unknown function pointer with signature ${a}: ${b}`);return c},ac,dc=a=>{a=bc(a);var b=K(a);cc(a);return b},ec=
(a,b)=>{function c(k){f[k]||ib[k]||(jb[k]?jb[k].forEach(c):(e.push(k),f[k]=!0))}var e=[],f={};b.forEach(c);throw new ac(`${a}: `+e.map(dc).join([", "]));};function fc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].le)return!0;return!1}
function gc(a,b,c,e,f){var k=b.length;if(2>k)throw new L("argTypes array size mismatch! Must at least get return value and 'this' types!");var n=null!==b[1]&&null!==c,l=fc(b),p="void"!==b[0].name,v=k-2,w=Array(v),A=[],D=[];return Fb(a,function(...I){D.length=0;A.length=n?2:1;A[0]=f;if(n){var Q=b[1].toWireType(D,this);A[1]=Q}for(var P=0;P<v;++P)w[P]=b[P+2].toWireType(D,I[P]),A.push(w[P]);I=e(...A);if(l)fb(D);else for(P=n?1:2;P<b.length;P++){var da=1===P?Q:w[P-2];null!==b[P].le&&b[P].le(da)}Q=p?b[0].fromWireType(I):
void 0;return Q})}
var hc=(a,b)=>{for(var c=[],e=0;e<a;e++)c.push(H[b+4*e>>2]);return c},ic=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},jc=[],kc=[],lc=a=>{9<a&&0===--kc[a+1]&&(kc[a]=void 0,jc.push(a))},mc=a=>{if(!a)throw new L("Cannot use deleted val. handle = "+a);return kc[a]},Ob=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=jc.pop()||kc.length;kc[b]=a;kc[b+1]=1;return b}},nc={name:"emscripten::val",fromWireType:a=>{var b=mc(a);lc(a);
return b},toWireType:(a,b)=>Ob(b),ke:8,readValueFromPointer:gb,le:null},oc=(a,b,c)=>{switch(b){case 1:return c?function(e){return this.fromWireType(Ca[e])}:function(e){return this.fromWireType(B[e])};case 2:return c?function(e){return this.fromWireType(Da[e>>1])}:function(e){return this.fromWireType(Fa[e>>1])};case 4:return c?function(e){return this.fromWireType(E[e>>2])}:function(e){return this.fromWireType(H[e>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},pc=(a,b)=>
{var c=ib[a];if(void 0===c)throw a=`${b} has unknown type ${dc(a)}`,new L(a);return c},Mb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},qc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(J[c>>2])};case 8:return function(c){return this.fromWireType(Ga[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},rc=(a,b,c)=>{switch(b){case 1:return c?e=>Ca[e]:e=>B[e];case 2:return c?e=>Da[e>>1]:e=>Fa[e>>
1];case 4:return c?e=>E[e>>2]:e=>H[e>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},ra=(a,b,c)=>{var e=B;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var n=a.charCodeAt(k);if(55296<=n&&57343>=n){var l=a.charCodeAt(++k);n=65536+((n&1023)<<10)|l&1023}if(127>=n){if(b>=c)break;e[b++]=n}else{if(2047>=n){if(b+1>=c)break;e[b++]=192|n>>6}else{if(65535>=n){if(b+2>=c)break;e[b++]=224|n>>12}else{if(b+3>=c)break;e[b++]=240|n>>18;e[b++]=128|n>>12&63}e[b++]=128|n>>6&
63}e[b++]=128|n&63}}e[b]=0;return b-f},qa=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},sc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,tc=(a,b)=>{var c=a>>1;for(var e=c+b/2;!(c>=e)&&Fa[c];)++c;c<<=1;if(32<c-a&&sc)return sc.decode(B.subarray(a,c));c="";for(e=0;!(e>=b/2);++e){var f=Da[a+2*e>>1];if(0==f)break;c+=String.fromCharCode(f)}return c},uc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var e=
b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)Da[b>>1]=a.charCodeAt(f),b+=2;Da[b>>1]=0;return b-e},vc=a=>2*a.length,wc=(a,b)=>{for(var c=0,e="";!(c>=b/4);){var f=E[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e},xc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var n=a.charCodeAt(++f);k=65536+((k&1023)<<10)|n&1023}E[b>>2]=k;b+=
4;if(b+4>c)break}E[b>>2]=0;return b-e},yc=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b},zc=(a,b,c)=>{var e=[];a=a.toWireType(e,c);e.length&&(H[b>>2]=Ob(e));return a},Ac=[],Bc={},Cc=a=>{var b=Bc[a];return void 0===b?K(a):b},Dc=()=>{function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;
"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},Ec=a=>{var b=Ac.length;Ac.push(a);return b},Fc=(a,b)=>{for(var c=Array(a),e=0;e<a;++e)c[e]=pc(H[b+4*e>>2],"parameter "+e);return c},Gc=Reflect.construct,R,Hc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,e)=>b.vertexAttribDivisorANGLE(c,
e),a.drawArraysInstanced=(c,e,f,k)=>b.drawArraysInstancedANGLE(c,e,f,k),a.drawElementsInstanced=(c,e,f,k,n)=>b.drawElementsInstancedANGLE(c,e,f,k,n))},Ic=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Jc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,e)=>b.drawBuffersWEBGL(c,e))},Kc=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Lc=1,Mc=[],Nc=[],Oc=[],Pc=[],ka=[],Qc=[],Rc=[],pa=[],Sc=[],Tc=[],Uc=[],Wc={},Xc={},Yc=4,Zc=0,ja=a=>{for(var b=Lc++,c=a.length;c<b;c++)a[c]=null;return b},$c=(a,b,c,e)=>{for(var f=0;f<a;f++){var k=R[c](),n=k&&ja(e);k?(k.name=n,e[n]=k):V||=1282;E[b+4*f>>2]=n}},na=(a,b)=>{a.Oe||(a.Oe=a.getContext,a.getContext=function(e,f){f=a.Oe(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var c=1<b.majorVersion?a.getContext("webgl2",
b):a.getContext("webgl",b);return c?ad(c,b):0},ad=(a,b)=>{var c=ja(pa),e={handle:c,attributes:b,version:b.majorVersion,me:a};a.canvas&&(a.canvas.We=e);pa[c]=e;("undefined"==typeof b.ef||b.ef)&&bd(e);return c},oa=a=>{z=pa[a];r.wf=R=z?.me;return!(a&&!R)},bd=a=>{a||=z;if(!a.nf){a.nf=!0;var b=a.me;b.Af=b.getExtension("WEBGL_multi_draw");b.yf=b.getExtension("EXT_polygon_offset_clamp");b.xf=b.getExtension("EXT_clip_control");b.Cf=b.getExtension("WEBGL_polygon_mode");Hc(b);Ic(b);Jc(b);b.Qe=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.Se=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.ne=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.ne)b.ne=b.getExtension("EXT_disjoint_timer_query");Kc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},z,V,cd=(a,b)=>{R.bindFramebuffer(a,Oc[b])},dd=a=>{R.bindVertexArray(Rc[a])},ed=a=>R.clear(a),fd=(a,b,c,e)=>R.clearColor(a,b,c,e),gd=a=>R.clearStencil(a),hd=(a,b)=>{for(var c=0;c<a;c++){var e=E[b+
4*c>>2];R.deleteVertexArray(Rc[e]);Rc[e]=null}},jd=[],kd=(a,b)=>{$c(a,b,"createVertexArray",Rc)};function ld(){var a=Kc(R);return a=a.concat(a.map(b=>"GL_"+b))}
var md=(a,b,c)=>{if(b){var e=void 0;switch(a){case 36346:e=1;break;case 36344:0!=c&&1!=c&&(V||=1280);return;case 34814:case 36345:e=0;break;case 34466:var f=R.getParameter(34467);e=f?f.length:0;break;case 33309:if(2>z.version){V||=1282;return}e=ld().length;break;case 33307:case 33308:if(2>z.version){V||=1280;return}e=33307==a?3:0}if(void 0===e)switch(f=R.getParameter(a),typeof f){case "number":e=f;break;case "boolean":e=f?1:0;break;case "string":V||=1280;return;case "object":if(null===f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:e=
0;break;default:V||=1280;return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(c){case 0:E[b+4*a>>2]=f[a];break;case 2:J[b+4*a>>2]=f[a];break;case 4:Ca[b+a]=f[a]?1:0}return}try{e=f.name|0}catch(k){V||=1280;ya(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${k})`);return}}break;default:V||=1280;ya(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${f} of type ${typeof f}!`);
return}switch(c){case 1:c=e;H[b>>2]=c;H[b+4>>2]=(c-H[b>>2])/4294967296;break;case 0:E[b>>2]=e;break;case 2:J[b>>2]=e;break;case 4:Ca[b]=e?1:0}}else V||=1281},nd=(a,b)=>md(a,b,0),od=(a,b,c)=>{if(c){a=Sc[a];b=2>z.version?R.ne.getQueryObjectEXT(a,b):R.getQueryParameter(a,b);var e;"boolean"==typeof b?e=b?1:0:e=b;H[c>>2]=e;H[c+4>>2]=(e-H[c>>2])/4294967296}else V||=1281},qd=a=>{var b=qa(a)+1,c=pd(b);c&&ra(a,c,b);return c},rd=a=>{var b=Wc[a];if(!b){switch(a){case 7939:b=qd(ld().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
R.getParameter(a))||(V||=1280);b=b?qd(b):0;break;case 7938:b=R.getParameter(7938);var c=`OpenGL ES 2.0 (${b})`;2<=z.version&&(c=`OpenGL ES 3.0 (${b})`);b=qd(c);break;case 35724:b=R.getParameter(35724);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=qd(b);break;default:V||=1280}Wc[a]=b}return b},sd=(a,b)=>{if(2>z.version)return V||=1282,0;var c=Xc[a];if(c)return 0>b||b>=c.length?(V||=1281,0):c[b];switch(a){case 7939:return c=
ld().map(qd),c=Xc[a]=c,0>b||b>=c.length?(V||=1281,0):c[b];default:return V||=1280,0}},td=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ud=a=>{a-=5120;return 0==a?Ca:1==a?B:2==a?Da:4==a?E:6==a?J:5==a||28922==a||28520==a||30779==a||30782==a?H:Fa},vd=(a,b,c,e,f)=>{a=ud(a);b=e*((Zc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Yc-1&-Yc);return a.subarray(f>>>31-Math.clz32(a.BYTES_PER_ELEMENT),f+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},X=a=>{var b=R.cf;if(b){var c=
b.ye[a];"number"==typeof c&&(b.ye[a]=c=R.getUniformLocation(b,b.Ue[a]+(0<c?`[${c}]`:"")));return c}V||=1282},wd=[],xd=[],yd={},Ad=()=>{if(!zd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in yd)void 0===yd[b]?delete a[b]:a[b]=yd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);zd=c}return zd},zd,Bd=[null,[],[]];
kb=r.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Cd=Array(256),Dd=0;256>Dd;++Dd)Cd[Dd]=String.fromCharCode(Dd);nb=Cd;L=r.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Eb.prototype,{isAliasOf:function(a){if(!(this instanceof Eb&&a instanceof Eb))return!1;var b=this.Zd.ee.ce,c=this.Zd.be;a.Zd=a.Zd;var e=a.Zd.ee.ce;for(a=a.Zd.be;b.he;)c=b.ze(c),b=b.he;for(;e.he;)a=e.ze(a),e=e.he;return b===e&&c===a},clone:function(){this.Zd.be||pb(this);if(this.Zd.xe)return this.Zd.count.value+=1,this;var a=Bb,b=Object,c=b.create,e=Object.getPrototypeOf(this),f=this.Zd;a=a(c.call(b,e,{Zd:{value:{count:f.count,we:f.we,xe:f.xe,be:f.be,ee:f.ee,fe:f.fe,je:f.je}}}));a.Zd.count.value+=
1;a.Zd.we=!1;return a},["delete"](){this.Zd.be||pb(this);if(this.Zd.we&&!this.Zd.xe)throw new L("Object already scheduled for deletion");rb(this);var a=this.Zd;--a.count.value;0===a.count.value&&(a.fe?a.je.oe(a.fe):a.ee.ce.oe(a.be));this.Zd.xe||(this.Zd.fe=void 0,this.Zd.be=void 0)},isDeleted:function(){return!this.Zd.be},deleteLater:function(){this.Zd.be||pb(this);if(this.Zd.we&&!this.Zd.xe)throw new L("Object already scheduled for deletion");Db.push(this);this.Zd.we=!0;return this}});
Object.assign(Qb.prototype,{hf(a){this.Te&&(a=this.Te(a));return a},Pe(a){this.oe?.(a)},ke:8,readValueFromPointer:gb,fromWireType:function(a){function b(){return this.Ee?Cb(this.ce.te,{ee:this.pf,be:c,je:this,fe:a}):Cb(this.ce.te,{ee:this,be:a})}var c=this.hf(a);if(!c)return this.Pe(a),null;var e=Ab(this.ce,c);if(void 0!==e){if(0===e.Zd.count.value)return e.Zd.be=c,e.Zd.fe=a,e.clone();e=e.clone();this.Pe(a);return e}e=this.ce.gf(c);e=yb[e];if(!e)return b.call(this);e=this.De?e.bf:e.pointerType;var f=
sb(c,this.ce,e.ce);return null===f?b.call(this):this.Ee?Cb(e.ce.te,{ee:e,be:f,je:this,fe:a}):Cb(e.ce.te,{ee:e,be:f})}});ac=r.UnboundTypeError=((a,b)=>{var c=Fb(b,function(e){this.name=b;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
kc.push(0,1,void 0,1,null,1,!0,1,!1,1);r.count_emval_handles=()=>kc.length/2-5-jc.length;for(var Ed=0;32>Ed;++Ed)jd.push(Array(Ed));var Fd=new Float32Array(288);for(Ed=0;288>=Ed;++Ed)wd[Ed]=Fd.subarray(0,Ed);var Gd=new Int32Array(288);for(Ed=0;288>=Ed;++Ed)xd[Ed]=Gd.subarray(0,Ed);
var Wd={F:(a,b,c)=>{var e=new Ya(a);H[e.be+16>>2]=0;H[e.be+4>>2]=b;H[e.be+8>>2]=c;Za=a;bb++;throw Za;},W:function(){return 0},wd:()=>{},vd:function(){return 0},ud:()=>{},td:()=>{},V:function(){},sd:()=>{},od:()=>{Pa("")},B:a=>{var b=eb[a];delete eb[a];var c=b.Me,e=b.oe,f=b.Re,k=f.map(n=>n.lf).concat(f.map(n=>n.tf));mb([a],k,n=>{var l={};f.forEach((p,v)=>{var w=n[v],A=p.jf,D=p.kf,I=n[v+f.length],Q=p.sf,P=p.uf;l[p.ff]={read:da=>w.fromWireType(A(D,da)),write:(da,la)=>{var Y=[];Q(P,da,I.toWireType(Y,
la));fb(Y)}}});return[{name:b.name,fromWireType:p=>{var v={},w;for(w in l)v[w]=l[w].read(p);e(p);return v},toWireType:(p,v)=>{for(var w in l)if(!(w in v))throw new TypeError(`Missing field: "${w}"`);var A=c();for(w in l)l[w].write(A,v[w]);null!==p&&p.push(e,A);return A},ke:8,readValueFromPointer:gb,le:e}]})},Z:()=>{},nd:(a,b,c,e)=>{b=K(b);lb(a,{name:b,fromWireType:function(f){return!!f},toWireType:function(f,k){return k?c:e},ke:8,readValueFromPointer:function(f){return this.fromWireType(B[f])},le:null})},
k:(a,b,c,e,f,k,n,l,p,v,w,A,D)=>{w=K(w);k=O(f,k);l&&=O(n,l);v&&=O(p,v);D=O(A,D);var I=Ib(w);Hb(I,function(){ec(`Cannot construct ${w} due to unbound types`,[e])});mb([a,b,c],e?[e]:[],Q=>{Q=Q[0];if(e){var P=Q.ce;var da=P.te}else da=Eb.prototype;Q=Fb(w,function(...Ea){if(Object.getPrototypeOf(this)!==la)throw new L("Use 'new' to construct "+w);if(void 0===Y.qe)throw new L(w+" has no accessible constructor");var ea=Y.qe[Ea.length];if(void 0===ea)throw new L(`Tried to invoke ctor of ${w} with invalid number of parameters (${Ea.length}) - expected (${Object.keys(Y.qe).toString()}) parameters instead!`);
return ea.apply(this,Ea)});var la=Object.create(da,{constructor:{value:Q}});Q.prototype=la;var Y=new Jb(w,Q,la,D,P,k,l,v);if(Y.he){var ha;(ha=Y.he).Ae??(ha.Ae=[]);Y.he.Ae.push(Y)}P=new Qb(w,Y,!0,!1,!1);ha=new Qb(w+"*",Y,!1,!1,!1);da=new Qb(w+" const*",Y,!1,!0,!1);yb[a]={pointerType:ha,bf:da};Rb(I,Q);return[P,ha,da]})},e:(a,b,c,e,f,k,n)=>{var l=hc(c,e);b=K(b);b=ic(b);k=O(f,k);mb([],[a],p=>{function v(){ec(`Cannot call ${w} due to unbound types`,l)}p=p[0];var w=`${p.name}.${b}`;b.startsWith("@@")&&
(b=Symbol[b.substring(2)]);var A=p.ce.constructor;void 0===A[b]?(v.pe=c-1,A[b]=v):(Gb(A,b,w),A[b].ge[c-1]=v);mb([],l,D=>{D=[D[0],null].concat(D.slice(1));D=gc(w,D,null,k,n);void 0===A[b].ge?(D.pe=c-1,A[b]=D):A[b].ge[c-1]=D;if(p.ce.Ae)for(const I of p.ce.Ae)I.constructor.hasOwnProperty(b)||(I.constructor[b]=D);return[]});return[]})},y:(a,b,c,e,f,k)=>{var n=hc(b,c);f=O(e,f);mb([],[a],l=>{l=l[0];var p=`constructor ${l.name}`;void 0===l.ce.qe&&(l.ce.qe=[]);if(void 0!==l.ce.qe[b-1])throw new L(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${l.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);l.ce.qe[b-1]=()=>{ec(`Cannot construct ${l.name} due to unbound types`,n)};mb([],n,v=>{v.splice(1,0,null);l.ce.qe[b-1]=gc(p,v,null,f,k);return[]});return[]})},a:(a,b,c,e,f,k,n,l)=>{var p=hc(c,e);b=K(b);b=ic(b);k=O(f,k);mb([],[a],v=>{function w(){ec(`Cannot call ${A} due to unbound types`,p)}v=v[0];var A=`${v.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&v.ce.qf.push(b);
var D=v.ce.te,I=D[b];void 0===I||void 0===I.ge&&I.className!==v.name&&I.pe===c-2?(w.pe=c-2,w.className=v.name,D[b]=w):(Gb(D,b,A),D[b].ge[c-2]=w);mb([],p,Q=>{Q=gc(A,Q,v,k,n);void 0===D[b].ge?(Q.pe=c-2,D[b]=Q):D[b].ge[c-2]=Q;return[]});return[]})},q:(a,b,c)=>{a=K(a);mb([],[b],e=>{e=e[0];r[a]=e.fromWireType(c);return[]})},md:a=>lb(a,nc),j:(a,b,c,e)=>{function f(){}b=K(b);f.values={};lb(a,{name:b,constructor:f,fromWireType:function(k){return this.constructor.values[k]},toWireType:(k,n)=>n.value,ke:8,
readValueFromPointer:oc(b,c,e),le:null});Hb(b,f)},b:(a,b,c)=>{var e=pc(a,"enum");b=K(b);a=e.constructor;e=Object.create(e.constructor.prototype,{value:{value:c},constructor:{value:Fb(`${e.name}_${b}`,function(){})}});a.values[c]=e;a[b]=e},T:(a,b,c)=>{b=K(b);lb(a,{name:b,fromWireType:e=>e,toWireType:(e,f)=>f,ke:8,readValueFromPointer:qc(b,c),le:null})},x:(a,b,c,e,f,k)=>{var n=hc(b,c);a=K(a);a=ic(a);f=O(e,f);Hb(a,function(){ec(`Cannot call ${a} due to unbound types`,n)},b-1);mb([],n,l=>{l=[l[0],null].concat(l.slice(1));
Rb(a,gc(a,l,null,f,k),b-1);return[]})},C:(a,b,c,e,f)=>{b=K(b);-1===f&&(f=4294967295);f=l=>l;if(0===e){var k=32-8*c;f=l=>l<<k>>>k}var n=b.includes("unsigned")?function(l,p){return p>>>0}:function(l,p){return p};lb(a,{name:b,fromWireType:f,toWireType:n,ke:8,readValueFromPointer:rc(b,c,0!==e),le:null})},p:(a,b,c)=>{function e(k){return new f(Ca.buffer,H[k+4>>2],H[k>>2])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=K(c);lb(a,{name:c,fromWireType:e,
ke:8,readValueFromPointer:e},{mf:!0})},o:(a,b,c,e,f,k,n,l,p,v,w,A)=>{c=K(c);k=O(f,k);l=O(n,l);v=O(p,v);A=O(w,A);mb([a],[b],D=>{D=D[0];return[new Qb(c,D.ce,!1,!1,!0,D,e,k,l,v,A)]})},S:(a,b)=>{b=K(b);var c="std::string"===b;lb(a,{name:b,fromWireType:function(e){var f=H[e>>2],k=e+4;if(c)for(var n=k,l=0;l<=f;++l){var p=k+l;if(l==f||0==B[p]){n=n?db(B,n,p-n):"";if(void 0===v)var v=n;else v+=String.fromCharCode(0),v+=n;n=p+1}}else{v=Array(f);for(l=0;l<f;++l)v[l]=String.fromCharCode(B[k+l]);v=v.join("")}cc(e);
return v},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var k="string"==typeof f;if(!(k||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array))throw new L("Cannot pass non-string to std::string");var n=c&&k?qa(f):f.length;var l=pd(4+n+1),p=l+4;H[l>>2]=n;if(c&&k)ra(f,p,n+1);else if(k)for(k=0;k<n;++k){var v=f.charCodeAt(k);if(255<v)throw cc(p),new L("String has UTF-16 code units that do not fit in 8 bits");B[p+k]=v}else for(k=0;k<n;++k)B[p+k]=f[k];
null!==e&&e.push(cc,l);return l},ke:8,readValueFromPointer:gb,le(e){cc(e)}})},M:(a,b,c)=>{c=K(c);if(2===b){var e=tc;var f=uc;var k=vc;var n=l=>Fa[l>>1]}else 4===b&&(e=wc,f=xc,k=yc,n=l=>H[l>>2]);lb(a,{name:c,fromWireType:l=>{for(var p=H[l>>2],v,w=l+4,A=0;A<=p;++A){var D=l+4+A*b;if(A==p||0==n(D))w=e(w,D-w),void 0===v?v=w:(v+=String.fromCharCode(0),v+=w),w=D+b}cc(l);return v},toWireType:(l,p)=>{if("string"!=typeof p)throw new L(`Cannot pass non-string to C++ string type ${c}`);var v=k(p),w=pd(4+v+b);
H[w>>2]=v/b;f(p,w+4,v+b);null!==l&&l.push(cc,w);return w},ke:8,readValueFromPointer:gb,le(l){cc(l)}})},A:(a,b,c,e,f,k)=>{eb[a]={name:K(b),Me:O(c,e),oe:O(f,k),Re:[]}},d:(a,b,c,e,f,k,n,l,p,v)=>{eb[a].Re.push({ff:K(b),lf:c,jf:O(e,f),kf:k,tf:n,sf:O(l,p),uf:v})},ld:(a,b)=>{b=K(b);lb(a,{zf:!0,name:b,ke:0,fromWireType:()=>{},toWireType:()=>{}})},kd:()=>1,jd:()=>{throw Infinity;},E:(a,b,c)=>{a=mc(a);b=pc(b,"emval::as");return zc(b,c,a)},L:(a,b,c,e)=>{a=Ac[a];b=mc(b);return a(null,b,c,e)},t:(a,b,c,e,f)=>{a=
Ac[a];b=mc(b);c=Cc(c);return a(b,b[c],e,f)},c:lc,K:a=>{if(0===a)return Ob(Dc());a=Cc(a);return Ob(Dc()[a])},n:(a,b,c)=>{var e=Fc(a,b),f=e.shift();a--;var k=Array(a);b=`methodCaller<(${e.map(n=>n.name).join(", ")}) => ${f.name}>`;return Ec(Fb(b,(n,l,p,v)=>{for(var w=0,A=0;A<a;++A)k[A]=e[A].readValueFromPointer(v+w),w+=e[A].ke;n=1===c?Gc(l,k):l.apply(n,k);return zc(f,p,n)}))},z:(a,b)=>{a=mc(a);b=mc(b);return Ob(a[b])},H:a=>{9<a&&(kc[a+1]+=1)},G:()=>Ob([]),f:a=>Ob(Cc(a)),D:()=>Ob({}),id:a=>{a=mc(a);
return!a},l:a=>{var b=mc(a);fb(b);lc(a)},h:(a,b,c)=>{a=mc(a);b=mc(b);c=mc(c);a[b]=c},g:(a,b)=>{a=pc(a,"_emval_take_value");a=a.readValueFromPointer(b);return Ob(a)},Y:function(){return-52},X:function(){},hd:(a,b,c,e)=>{var f=(new Date).getFullYear(),k=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();H[a>>2]=60*Math.max(k,f);E[b>>2]=Number(k!=f);b=n=>{var l=Math.abs(n);return`UTC${0<=n?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};
a=b(k);b=b(f);f<k?(ra(a,c,17),ra(b,e,17)):(ra(a,e,17),ra(b,c,17))},gd:()=>performance.now(),fd:a=>R.activeTexture(a),ed:(a,b)=>{R.attachShader(Nc[a],Qc[b])},dd:(a,b)=>{R.beginQuery(a,Sc[b])},cd:(a,b)=>{R.ne.beginQueryEXT(a,Sc[b])},bd:(a,b,c)=>{R.bindAttribLocation(Nc[a],b,c?db(B,c):"")},ad:(a,b)=>{35051==a?R.Je=b:35052==a&&(R.se=b);R.bindBuffer(a,Mc[b])},$c:cd,_c:(a,b)=>{R.bindRenderbuffer(a,Pc[b])},Zc:(a,b)=>{R.bindSampler(a,Tc[b])},Yc:(a,b)=>{R.bindTexture(a,ka[b])},Xc:dd,Wc:dd,Vc:(a,b,c,e)=>R.blendColor(a,
b,c,e),Uc:a=>R.blendEquation(a),Tc:(a,b)=>R.blendFunc(a,b),Sc:(a,b,c,e,f,k,n,l,p,v)=>R.blitFramebuffer(a,b,c,e,f,k,n,l,p,v),Rc:(a,b,c,e)=>{2<=z.version?c&&b?R.bufferData(a,B,e,c,b):R.bufferData(a,b,e):R.bufferData(a,c?B.subarray(c,c+b):b,e)},Qc:(a,b,c,e)=>{2<=z.version?c&&R.bufferSubData(a,b,B,e,c):R.bufferSubData(a,b,B.subarray(e,e+c))},Pc:a=>R.checkFramebufferStatus(a),Oc:ed,Nc:fd,Mc:gd,Lc:(a,b,c,e)=>R.clientWaitSync(Uc[a],b,(c>>>0)+4294967296*e),Kc:(a,b,c,e)=>{R.colorMask(!!a,!!b,!!c,!!e)},Jc:a=>
{R.compileShader(Qc[a])},Ic:(a,b,c,e,f,k,n,l)=>{2<=z.version?R.se||!n?R.compressedTexImage2D(a,b,c,e,f,k,n,l):R.compressedTexImage2D(a,b,c,e,f,k,B,l,n):R.compressedTexImage2D(a,b,c,e,f,k,B.subarray(l,l+n))},Hc:(a,b,c,e,f,k,n,l,p)=>{2<=z.version?R.se||!l?R.compressedTexSubImage2D(a,b,c,e,f,k,n,l,p):R.compressedTexSubImage2D(a,b,c,e,f,k,n,B,p,l):R.compressedTexSubImage2D(a,b,c,e,f,k,n,B.subarray(p,p+l))},Gc:(a,b,c,e,f)=>R.copyBufferSubData(a,b,c,e,f),Fc:(a,b,c,e,f,k,n,l)=>R.copyTexSubImage2D(a,b,c,
e,f,k,n,l),Ec:()=>{var a=ja(Nc),b=R.createProgram();b.name=a;b.He=b.Fe=b.Ge=0;b.Ne=1;Nc[a]=b;return a},Dc:a=>{var b=ja(Qc);Qc[b]=R.createShader(a);return b},Cc:a=>R.cullFace(a),Bc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Mc[e];f&&(R.deleteBuffer(f),f.name=0,Mc[e]=null,e==R.Je&&(R.Je=0),e==R.se&&(R.se=0))}},Ac:(a,b)=>{for(var c=0;c<a;++c){var e=E[b+4*c>>2],f=Oc[e];f&&(R.deleteFramebuffer(f),f.name=0,Oc[e]=null)}},zc:a=>{if(a){var b=Nc[a];b?(R.deleteProgram(b),b.name=0,Nc[a]=null):V||=1281}},
yc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Sc[e];f&&(R.deleteQuery(f),Sc[e]=null)}},xc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Sc[e];f&&(R.ne.deleteQueryEXT(f),Sc[e]=null)}},wc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Pc[e];f&&(R.deleteRenderbuffer(f),f.name=0,Pc[e]=null)}},vc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Tc[e];f&&(R.deleteSampler(f),f.name=0,Tc[e]=null)}},uc:a=>{if(a){var b=Qc[a];b?(R.deleteShader(b),Qc[a]=null):V||=1281}},tc:a=>{if(a){var b=Uc[a];b?
(R.deleteSync(b),b.name=0,Uc[a]=null):V||=1281}},sc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=ka[e];f&&(R.deleteTexture(f),f.name=0,ka[e]=null)}},rc:hd,qc:hd,pc:a=>{R.depthMask(!!a)},oc:a=>R.disable(a),nc:a=>{R.disableVertexAttribArray(a)},mc:(a,b,c)=>{R.drawArrays(a,b,c)},lc:(a,b,c,e)=>{R.drawArraysInstanced(a,b,c,e)},kc:(a,b,c,e,f)=>{R.Qe.drawArraysInstancedBaseInstanceWEBGL(a,b,c,e,f)},jc:(a,b)=>{for(var c=jd[a],e=0;e<a;e++)c[e]=E[b+4*e>>2];R.drawBuffers(c)},ic:(a,b,c,e)=>{R.drawElements(a,
b,c,e)},hc:(a,b,c,e,f)=>{R.drawElementsInstanced(a,b,c,e,f)},gc:(a,b,c,e,f,k,n)=>{R.Qe.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,e,f,k,n)},fc:(a,b,c,e,f,k)=>{R.drawElements(a,e,f,k)},ec:a=>R.enable(a),dc:a=>{R.enableVertexAttribArray(a)},cc:a=>R.endQuery(a),bc:a=>{R.ne.endQueryEXT(a)},ac:(a,b)=>(a=R.fenceSync(a,b))?(b=ja(Uc),a.name=b,Uc[b]=a,b):0,$b:()=>R.finish(),_b:()=>R.flush(),Zb:(a,b,c,e)=>{R.framebufferRenderbuffer(a,b,c,Pc[e])},Yb:(a,b,c,e,f)=>{R.framebufferTexture2D(a,b,c,ka[e],
f)},Xb:a=>R.frontFace(a),Wb:(a,b)=>{$c(a,b,"createBuffer",Mc)},Vb:(a,b)=>{$c(a,b,"createFramebuffer",Oc)},Ub:(a,b)=>{$c(a,b,"createQuery",Sc)},Tb:(a,b)=>{for(var c=0;c<a;c++){var e=R.ne.createQueryEXT();if(!e){for(V||=1282;c<a;)E[b+4*c++>>2]=0;break}var f=ja(Sc);e.name=f;Sc[f]=e;E[b+4*c>>2]=f}},Sb:(a,b)=>{$c(a,b,"createRenderbuffer",Pc)},Rb:(a,b)=>{$c(a,b,"createSampler",Tc)},Qb:(a,b)=>{$c(a,b,"createTexture",ka)},Pb:kd,Ob:kd,Nb:a=>R.generateMipmap(a),Mb:(a,b,c)=>{c?E[c>>2]=R.getBufferParameter(a,
b):V||=1281},Lb:()=>{var a=R.getError()||V;V=0;return a},Kb:(a,b)=>md(a,b,2),Jb:(a,b,c,e)=>{a=R.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;E[e>>2]=a},Ib:nd,Hb:(a,b,c,e)=>{a=R.getProgramInfoLog(Nc[a]);null===a&&(a="(unknown error)");b=0<b&&e?ra(a,e,b):0;c&&(E[c>>2]=b)},Gb:(a,b,c)=>{if(c)if(a>=Lc)V||=1281;else if(a=Nc[a],35716==b)a=R.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.He){var e=
R.getProgramParameter(a,35718);for(b=0;b<e;++b)a.He=Math.max(a.He,R.getActiveUniform(a,b).name.length+1)}E[c>>2]=a.He}else if(35722==b){if(!a.Fe)for(e=R.getProgramParameter(a,35721),b=0;b<e;++b)a.Fe=Math.max(a.Fe,R.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.Fe}else if(35381==b){if(!a.Ge)for(e=R.getProgramParameter(a,35382),b=0;b<e;++b)a.Ge=Math.max(a.Ge,R.getActiveUniformBlockName(a,b).length+1);E[c>>2]=a.Ge}else E[c>>2]=R.getProgramParameter(a,b);else V||=1281},Fb:od,Eb:od,Db:(a,b,c)=>{if(c){a=
R.getQueryParameter(Sc[a],b);var e;"boolean"==typeof a?e=a?1:0:e=a;E[c>>2]=e}else V||=1281},Cb:(a,b,c)=>{if(c){a=R.ne.getQueryObjectEXT(Sc[a],b);var e;"boolean"==typeof a?e=a?1:0:e=a;E[c>>2]=e}else V||=1281},Bb:(a,b,c)=>{c?E[c>>2]=R.getQuery(a,b):V||=1281},Ab:(a,b,c)=>{c?E[c>>2]=R.ne.getQueryEXT(a,b):V||=1281},zb:(a,b,c)=>{c?E[c>>2]=R.getRenderbufferParameter(a,b):V||=1281},yb:(a,b,c,e)=>{a=R.getShaderInfoLog(Qc[a]);null===a&&(a="(unknown error)");b=0<b&&e?ra(a,e,b):0;c&&(E[c>>2]=b)},xb:(a,b,c,e)=>
{a=R.getShaderPrecisionFormat(a,b);E[c>>2]=a.rangeMin;E[c+4>>2]=a.rangeMax;E[e>>2]=a.precision},wb:(a,b,c)=>{c?35716==b?(a=R.getShaderInfoLog(Qc[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=R.getShaderSource(Qc[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=R.getShaderParameter(Qc[a],b):V||=1281},vb:rd,ub:sd,tb:(a,b)=>{b=b?db(B,b):"";if(a=Nc[a]){var c=a,e=c.ye,f=c.Ve,k;if(!e){c.ye=e={};c.Ue={};var n=R.getProgramParameter(c,35718);for(k=0;k<n;++k){var l=R.getActiveUniform(c,k);var p=
l.name;l=l.size;var v=td(p);v=0<v?p.slice(0,v):p;var w=c.Ne;c.Ne+=l;f[v]=[l,w];for(p=0;p<l;++p)e[w]=p,c.Ue[w++]=v}}c=a.ye;e=0;f=b;k=td(b);0<k&&(e=parseInt(b.slice(k+1))>>>0,f=b.slice(0,k));if((f=a.Ve[f])&&e<f[0]&&(e+=f[1],c[e]=c[e]||R.getUniformLocation(a,b)))return e}else V||=1281;return-1},sb:(a,b,c)=>{for(var e=jd[b],f=0;f<b;f++)e[f]=E[c+4*f>>2];R.invalidateFramebuffer(a,e)},rb:(a,b,c,e,f,k,n)=>{for(var l=jd[b],p=0;p<b;p++)l[p]=E[c+4*p>>2];R.invalidateSubFramebuffer(a,l,e,f,k,n)},qb:a=>R.isSync(Uc[a]),
pb:a=>(a=ka[a])?R.isTexture(a):0,ob:a=>R.lineWidth(a),nb:a=>{a=Nc[a];R.linkProgram(a);a.ye=0;a.Ve={}},mb:(a,b,c,e,f,k)=>{R.Se.multiDrawArraysInstancedBaseInstanceWEBGL(a,E,b>>2,E,c>>2,E,e>>2,H,f>>2,k)},lb:(a,b,c,e,f,k,n,l)=>{R.Se.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,E,b>>2,c,E,e>>2,E,f>>2,E,k>>2,H,n>>2,l)},kb:(a,b)=>{3317==a?Yc=b:3314==a&&(Zc=b);R.pixelStorei(a,b)},jb:(a,b)=>{R.ne.queryCounterEXT(Sc[a],b)},ib:a=>R.readBuffer(a),hb:(a,b,c,e,f,k,n)=>{if(2<=z.version)if(R.Je)R.readPixels(a,
b,c,e,f,k,n);else{var l=ud(k);n>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);R.readPixels(a,b,c,e,f,k,l,n)}else(l=vd(k,f,c,e,n))?R.readPixels(a,b,c,e,f,k,l):V||=1280},gb:(a,b,c,e)=>R.renderbufferStorage(a,b,c,e),fb:(a,b,c,e,f)=>R.renderbufferStorageMultisample(a,b,c,e,f),eb:(a,b,c)=>{R.samplerParameterf(Tc[a],b,c)},db:(a,b,c)=>{R.samplerParameteri(Tc[a],b,c)},cb:(a,b,c)=>{R.samplerParameteri(Tc[a],b,E[c>>2])},bb:(a,b,c,e)=>R.scissor(a,b,c,e),ab:(a,b,c,e)=>{for(var f="",k=0;k<b;++k){var n=(n=H[c+4*k>>2])?
db(B,n,e?H[e+4*k>>2]:void 0):"";f+=n}R.shaderSource(Qc[a],f)},$a:(a,b,c)=>R.stencilFunc(a,b,c),_a:(a,b,c,e)=>R.stencilFuncSeparate(a,b,c,e),Za:a=>R.stencilMask(a),Ya:(a,b)=>R.stencilMaskSeparate(a,b),Xa:(a,b,c)=>R.stencilOp(a,b,c),Wa:(a,b,c,e)=>R.stencilOpSeparate(a,b,c,e),Va:(a,b,c,e,f,k,n,l,p)=>{if(2<=z.version){if(R.se){R.texImage2D(a,b,c,e,f,k,n,l,p);return}if(p){var v=ud(l);p>>>=31-Math.clz32(v.BYTES_PER_ELEMENT);R.texImage2D(a,b,c,e,f,k,n,l,v,p);return}}v=p?vd(l,n,e,f,p):null;R.texImage2D(a,
b,c,e,f,k,n,l,v)},Ua:(a,b,c)=>R.texParameterf(a,b,c),Ta:(a,b,c)=>{R.texParameterf(a,b,J[c>>2])},Sa:(a,b,c)=>R.texParameteri(a,b,c),Ra:(a,b,c)=>{R.texParameteri(a,b,E[c>>2])},Qa:(a,b,c,e,f)=>R.texStorage2D(a,b,c,e,f),Pa:(a,b,c,e,f,k,n,l,p)=>{if(2<=z.version){if(R.se){R.texSubImage2D(a,b,c,e,f,k,n,l,p);return}if(p){var v=ud(l);R.texSubImage2D(a,b,c,e,f,k,n,l,v,p>>>31-Math.clz32(v.BYTES_PER_ELEMENT));return}}p=p?vd(l,n,f,k,p):null;R.texSubImage2D(a,b,c,e,f,k,n,l,p)},Oa:(a,b)=>{R.uniform1f(X(a),b)},Na:(a,
b,c)=>{if(2<=z.version)b&&R.uniform1fv(X(a),J,c>>2,b);else{if(288>=b)for(var e=wd[b],f=0;f<b;++f)e[f]=J[c+4*f>>2];else e=J.subarray(c>>2,c+4*b>>2);R.uniform1fv(X(a),e)}},Ma:(a,b)=>{R.uniform1i(X(a),b)},La:(a,b,c)=>{if(2<=z.version)b&&R.uniform1iv(X(a),E,c>>2,b);else{if(288>=b)for(var e=xd[b],f=0;f<b;++f)e[f]=E[c+4*f>>2];else e=E.subarray(c>>2,c+4*b>>2);R.uniform1iv(X(a),e)}},Ka:(a,b,c)=>{R.uniform2f(X(a),b,c)},Ja:(a,b,c)=>{if(2<=z.version)b&&R.uniform2fv(X(a),J,c>>2,2*b);else{if(144>=b){b*=2;for(var e=
wd[b],f=0;f<b;f+=2)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2]}else e=J.subarray(c>>2,c+8*b>>2);R.uniform2fv(X(a),e)}},Ia:(a,b,c)=>{R.uniform2i(X(a),b,c)},Ha:(a,b,c)=>{if(2<=z.version)b&&R.uniform2iv(X(a),E,c>>2,2*b);else{if(144>=b){b*=2;for(var e=xd[b],f=0;f<b;f+=2)e[f]=E[c+4*f>>2],e[f+1]=E[c+(4*f+4)>>2]}else e=E.subarray(c>>2,c+8*b>>2);R.uniform2iv(X(a),e)}},Ga:(a,b,c,e)=>{R.uniform3f(X(a),b,c,e)},Fa:(a,b,c)=>{if(2<=z.version)b&&R.uniform3fv(X(a),J,c>>2,3*b);else{if(96>=b){b*=3;for(var e=wd[b],f=0;f<
b;f+=3)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2],e[f+2]=J[c+(4*f+8)>>2]}else e=J.subarray(c>>2,c+12*b>>2);R.uniform3fv(X(a),e)}},Ea:(a,b,c,e)=>{R.uniform3i(X(a),b,c,e)},Da:(a,b,c)=>{if(2<=z.version)b&&R.uniform3iv(X(a),E,c>>2,3*b);else{if(96>=b){b*=3;for(var e=xd[b],f=0;f<b;f+=3)e[f]=E[c+4*f>>2],e[f+1]=E[c+(4*f+4)>>2],e[f+2]=E[c+(4*f+8)>>2]}else e=E.subarray(c>>2,c+12*b>>2);R.uniform3iv(X(a),e)}},Ca:(a,b,c,e,f)=>{R.uniform4f(X(a),b,c,e,f)},Ba:(a,b,c)=>{if(2<=z.version)b&&R.uniform4fv(X(a),J,c>>2,4*
b);else{if(72>=b){var e=wd[4*b],f=J;c>>=2;b*=4;for(var k=0;k<b;k+=4){var n=c+k;e[k]=f[n];e[k+1]=f[n+1];e[k+2]=f[n+2];e[k+3]=f[n+3]}}else e=J.subarray(c>>2,c+16*b>>2);R.uniform4fv(X(a),e)}},Aa:(a,b,c,e,f)=>{R.uniform4i(X(a),b,c,e,f)},za:(a,b,c)=>{if(2<=z.version)b&&R.uniform4iv(X(a),E,c>>2,4*b);else{if(72>=b){b*=4;for(var e=xd[b],f=0;f<b;f+=4)e[f]=E[c+4*f>>2],e[f+1]=E[c+(4*f+4)>>2],e[f+2]=E[c+(4*f+8)>>2],e[f+3]=E[c+(4*f+12)>>2]}else e=E.subarray(c>>2,c+16*b>>2);R.uniform4iv(X(a),e)}},ya:(a,b,c,e)=>
{if(2<=z.version)b&&R.uniformMatrix2fv(X(a),!!c,J,e>>2,4*b);else{if(72>=b){b*=4;for(var f=wd[b],k=0;k<b;k+=4)f[k]=J[e+4*k>>2],f[k+1]=J[e+(4*k+4)>>2],f[k+2]=J[e+(4*k+8)>>2],f[k+3]=J[e+(4*k+12)>>2]}else f=J.subarray(e>>2,e+16*b>>2);R.uniformMatrix2fv(X(a),!!c,f)}},xa:(a,b,c,e)=>{if(2<=z.version)b&&R.uniformMatrix3fv(X(a),!!c,J,e>>2,9*b);else{if(32>=b){b*=9;for(var f=wd[b],k=0;k<b;k+=9)f[k]=J[e+4*k>>2],f[k+1]=J[e+(4*k+4)>>2],f[k+2]=J[e+(4*k+8)>>2],f[k+3]=J[e+(4*k+12)>>2],f[k+4]=J[e+(4*k+16)>>2],f[k+
5]=J[e+(4*k+20)>>2],f[k+6]=J[e+(4*k+24)>>2],f[k+7]=J[e+(4*k+28)>>2],f[k+8]=J[e+(4*k+32)>>2]}else f=J.subarray(e>>2,e+36*b>>2);R.uniformMatrix3fv(X(a),!!c,f)}},wa:(a,b,c,e)=>{if(2<=z.version)b&&R.uniformMatrix4fv(X(a),!!c,J,e>>2,16*b);else{if(18>=b){var f=wd[16*b],k=J;e>>=2;b*=16;for(var n=0;n<b;n+=16){var l=e+n;f[n]=k[l];f[n+1]=k[l+1];f[n+2]=k[l+2];f[n+3]=k[l+3];f[n+4]=k[l+4];f[n+5]=k[l+5];f[n+6]=k[l+6];f[n+7]=k[l+7];f[n+8]=k[l+8];f[n+9]=k[l+9];f[n+10]=k[l+10];f[n+11]=k[l+11];f[n+12]=k[l+12];f[n+
13]=k[l+13];f[n+14]=k[l+14];f[n+15]=k[l+15]}}else f=J.subarray(e>>2,e+64*b>>2);R.uniformMatrix4fv(X(a),!!c,f)}},va:a=>{a=Nc[a];R.useProgram(a);R.cf=a},ua:(a,b)=>R.vertexAttrib1f(a,b),ta:(a,b)=>{R.vertexAttrib2f(a,J[b>>2],J[b+4>>2])},sa:(a,b)=>{R.vertexAttrib3f(a,J[b>>2],J[b+4>>2],J[b+8>>2])},ra:(a,b)=>{R.vertexAttrib4f(a,J[b>>2],J[b+4>>2],J[b+8>>2],J[b+12>>2])},qa:(a,b)=>{R.vertexAttribDivisor(a,b)},pa:(a,b,c,e,f)=>{R.vertexAttribIPointer(a,b,c,e,f)},oa:(a,b,c,e,f,k)=>{R.vertexAttribPointer(a,b,c,
!!e,f,k)},na:(a,b,c,e)=>R.viewport(a,b,c,e),ma:(a,b,c,e)=>{R.waitSync(Uc[a],b,(c>>>0)+4294967296*e)},la:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+1/c);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-za.buffer.byteLength+65535)/65536|0;try{za.grow(e);Ha();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},ka:()=>z?z.handle:0,rd:(a,b)=>{var c=0;Ad().forEach((e,f)=>{var k=b+c;f=H[a+4*f>>2]=k;for(k=0;k<e.length;++k)Ca[f++]=
e.charCodeAt(k);Ca[f]=0;c+=e.length+1});return 0},qd:(a,b)=>{var c=Ad();H[a>>2]=c.length;var e=0;c.forEach(f=>e+=f.length+1);H[b>>2]=e;return 0},ja:a=>{Xa||(Ba=!0);throw new Va(a);},N:()=>52,$:function(){return 52},pd:()=>52,_:function(){return 70},U:(a,b,c,e)=>{for(var f=0,k=0;k<c;k++){var n=H[b>>2],l=H[b+4>>2];b+=8;for(var p=0;p<l;p++){var v=B[n+p],w=Bd[a];0===v||10===v?((1===a?xa:ya)(db(w)),w.length=0):w.push(v)}f+=l}H[e>>2]=f;return 0},ia:cd,ha:ed,ga:fd,fa:gd,J:nd,R:rd,ea:sd,i:Hd,w:Id,m:Jd,I:Kd,
da:Ld,Q:Md,P:Nd,s:Od,v:Pd,r:Qd,u:Rd,O:Sd,ca:Td,ba:Ud,aa:Vd},Z=function(){function a(c){Z=c.exports;za=Z.xd;Ha();N=Z.Ad;Ja.unshift(Z.yd);La--;0==La&&(null!==Na&&(clearInterval(Na),Na=null),Oa&&(c=Oa,Oa=null,c()));return Z}var b={a:Wd};La++;if(r.instantiateWasm)try{return r.instantiateWasm(b,a)}catch(c){ya(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ra??=r.locateFile?Qa("canvaskit.wasm")?"canvaskit.wasm":ta+"canvaskit.wasm":(new URL("canvaskit.wasm",import.meta.url)).href;
Ua(b,function(c){a(c.instance)}).catch(ba);return{}}(),bc=a=>(bc=Z.zd)(a),pd=r._malloc=a=>(pd=r._malloc=Z.Bd)(a),cc=r._free=a=>(cc=r._free=Z.Cd)(a),Xd=(a,b)=>(Xd=Z.Dd)(a,b),Yd=a=>(Yd=Z.Ed)(a),Zd=()=>(Zd=Z.Fd)();r.dynCall_viji=(a,b,c,e,f)=>(r.dynCall_viji=Z.Gd)(a,b,c,e,f);r.dynCall_vijiii=(a,b,c,e,f,k,n)=>(r.dynCall_vijiii=Z.Hd)(a,b,c,e,f,k,n);r.dynCall_viiiiij=(a,b,c,e,f,k,n,l)=>(r.dynCall_viiiiij=Z.Id)(a,b,c,e,f,k,n,l);r.dynCall_vij=(a,b,c,e)=>(r.dynCall_vij=Z.Jd)(a,b,c,e);
r.dynCall_iiiji=(a,b,c,e,f,k)=>(r.dynCall_iiiji=Z.Kd)(a,b,c,e,f,k);r.dynCall_jii=(a,b,c)=>(r.dynCall_jii=Z.Ld)(a,b,c);r.dynCall_jiiiiii=(a,b,c,e,f,k,n)=>(r.dynCall_jiiiiii=Z.Md)(a,b,c,e,f,k,n);r.dynCall_jiiiiji=(a,b,c,e,f,k,n,l)=>(r.dynCall_jiiiiji=Z.Nd)(a,b,c,e,f,k,n,l);r.dynCall_ji=(a,b)=>(r.dynCall_ji=Z.Od)(a,b);r.dynCall_iijj=(a,b,c,e,f,k)=>(r.dynCall_iijj=Z.Pd)(a,b,c,e,f,k);r.dynCall_iiji=(a,b,c,e,f)=>(r.dynCall_iiji=Z.Qd)(a,b,c,e,f);
r.dynCall_iijjiii=(a,b,c,e,f,k,n,l,p)=>(r.dynCall_iijjiii=Z.Rd)(a,b,c,e,f,k,n,l,p);r.dynCall_iij=(a,b,c,e)=>(r.dynCall_iij=Z.Sd)(a,b,c,e);r.dynCall_vijjjii=(a,b,c,e,f,k,n,l,p,v)=>(r.dynCall_vijjjii=Z.Td)(a,b,c,e,f,k,n,l,p,v);r.dynCall_jiji=(a,b,c,e,f)=>(r.dynCall_jiji=Z.Ud)(a,b,c,e,f);r.dynCall_viijii=(a,b,c,e,f,k,n)=>(r.dynCall_viijii=Z.Vd)(a,b,c,e,f,k,n);r.dynCall_iiiiij=(a,b,c,e,f,k,n)=>(r.dynCall_iiiiij=Z.Wd)(a,b,c,e,f,k,n);
r.dynCall_iiiiijj=(a,b,c,e,f,k,n,l,p)=>(r.dynCall_iiiiijj=Z.Xd)(a,b,c,e,f,k,n,l,p);r.dynCall_iiiiiijj=(a,b,c,e,f,k,n,l,p,v)=>(r.dynCall_iiiiiijj=Z.Yd)(a,b,c,e,f,k,n,l,p,v);function Rd(a,b,c,e,f){var k=Zd();try{N.get(a)(b,c,e,f)}catch(n){Yd(k);if(n!==n+0)throw n;Xd(1,0)}}function Id(a,b,c){var e=Zd();try{return N.get(a)(b,c)}catch(f){Yd(e);if(f!==f+0)throw f;Xd(1,0)}}function Pd(a,b,c){var e=Zd();try{N.get(a)(b,c)}catch(f){Yd(e);if(f!==f+0)throw f;Xd(1,0)}}
function Hd(a,b){var c=Zd();try{return N.get(a)(b)}catch(e){Yd(c);if(e!==e+0)throw e;Xd(1,0)}}function Od(a,b){var c=Zd();try{N.get(a)(b)}catch(e){Yd(c);if(e!==e+0)throw e;Xd(1,0)}}function Jd(a,b,c,e){var f=Zd();try{return N.get(a)(b,c,e)}catch(k){Yd(f);if(k!==k+0)throw k;Xd(1,0)}}function Vd(a,b,c,e,f,k,n,l,p,v){var w=Zd();try{N.get(a)(b,c,e,f,k,n,l,p,v)}catch(A){Yd(w);if(A!==A+0)throw A;Xd(1,0)}}function Qd(a,b,c,e){var f=Zd();try{N.get(a)(b,c,e)}catch(k){Yd(f);if(k!==k+0)throw k;Xd(1,0)}}
function Td(a,b,c,e,f,k,n){var l=Zd();try{N.get(a)(b,c,e,f,k,n)}catch(p){Yd(l);if(p!==p+0)throw p;Xd(1,0)}}function Sd(a,b,c,e,f,k){var n=Zd();try{N.get(a)(b,c,e,f,k)}catch(l){Yd(n);if(l!==l+0)throw l;Xd(1,0)}}function Ud(a,b,c,e,f,k,n,l){var p=Zd();try{N.get(a)(b,c,e,f,k,n,l)}catch(v){Yd(p);if(v!==v+0)throw v;Xd(1,0)}}function Md(a,b,c,e,f,k,n,l){var p=Zd();try{return N.get(a)(b,c,e,f,k,n,l)}catch(v){Yd(p);if(v!==v+0)throw v;Xd(1,0)}}
function Kd(a,b,c,e,f){var k=Zd();try{return N.get(a)(b,c,e,f)}catch(n){Yd(k);if(n!==n+0)throw n;Xd(1,0)}}function Nd(a,b,c,e,f,k,n,l,p,v){var w=Zd();try{return N.get(a)(b,c,e,f,k,n,l,p,v)}catch(A){Yd(w);if(A!==A+0)throw A;Xd(1,0)}}function Ld(a,b,c,e,f,k,n){var l=Zd();try{return N.get(a)(b,c,e,f,k,n)}catch(p){Yd(l);if(p!==p+0)throw p;Xd(1,0)}}var $d,ae;Oa=function be(){$d||ce();$d||(Oa=be)};
function ce(){if(!(0<La)){if(!ae&&(ae=1,Wa(Ia),0<La))return;$d||($d=1,r.calledRun=1,Ba||(Wa(Ja),aa(r),r.onRuntimeInitialized?.(),Wa(Ka)))}}ce();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default CanvasKitInit;
