
var CanvasKitInit = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var r=moduleArg,ba,ca,ea=new Promise((a,b)=>{ba=a;ca=b}),fa="object"==typeof window,ha="function"==typeof importScripts;
(function(a){a.Ud=a.Ud||[];a.Ud.push(function(){a.MakeSWCanvasSurface=function(b){var c=b,e="undefined"!==typeof OffscreenCanvas&&c instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&c instanceof HTMLCanvasElement||e||(c=document.getElementById(b),c)))throw"Canvas with id "+b+" was not found";if(b=a.MakeSurface(c.width,c.height))b.re=c;return b};a.MakeCanvasSurface||(a.MakeCanvasSurface=a.MakeSWCanvasSurface);a.MakeSurface=function(b,c){var e={width:b,height:c,colorType:a.ColorType.RGBA_8888,
alphaType:a.AlphaType.Unpremul,colorSpace:a.ColorSpace.SRGB},f=b*c*4,k=a._malloc(f);if(e=a.Surface._makeRasterDirect(e,k,4*b))e.re=null,e.Re=b,e.Oe=c,e.Pe=f,e.ye=k,e.getCanvas().clear(a.TRANSPARENT);return e};a.MakeRasterDirectSurface=function(b,c,e){return a.Surface._makeRasterDirect(b,c.byteOffset,e)};a.Surface.prototype.flush=function(b){a.Rd(this.Qd);this._flush();if(this.re){var c=new Uint8ClampedArray(a.HEAPU8.buffer,this.ye,this.Pe);c=new ImageData(c,this.Re,this.Oe);b?this.re.getContext("2d").putImageData(c,
0,0,b[0],b[1],b[2]-b[0],b[3]-b[1]):this.re.getContext("2d").putImageData(c,0,0)}};a.Surface.prototype.dispose=function(){this.ye&&a._free(this.ye);this.delete()};a.Rd=a.Rd||function(){};a.se=a.se||function(){return null}})})(r);
(function(a){a.Ud=a.Ud||[];a.Ud.push(function(){function b(l,q,v){return l&&l.hasOwnProperty(q)?l[q]:v}function c(l){var q=ia(ja);ja[q]=l;return q}function e(l){return l.naturalHeight||l.videoHeight||l.displayHeight||l.height}function f(l){return l.naturalWidth||l.videoWidth||l.displayWidth||l.width}function k(l,q,v,w){l.bindTexture(l.TEXTURE_2D,q);w||v.alphaType!==a.AlphaType.Premul||l.pixelStorei(l.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!0);return q}function n(l,q,v){v||q.alphaType!==a.AlphaType.Premul||
l.pixelStorei(l.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);l.bindTexture(l.TEXTURE_2D,null)}a.GetWebGLContext=function(l,q){if(!l)throw"null canvas passed into makeWebGLContext";var v={alpha:b(q,"alpha",1),depth:b(q,"depth",1),stencil:b(q,"stencil",8),antialias:b(q,"antialias",0),premultipliedAlpha:b(q,"premultipliedAlpha",1),preserveDrawingBuffer:b(q,"preserveDrawingBuffer",0),preferLowPowerToHighPerformance:b(q,"preferLowPowerToHighPerformance",0),failIfMajorPerformanceCaveat:b(q,"failIfMajorPerformanceCaveat",
0),enableExtensionsByDefault:b(q,"enableExtensionsByDefault",1),explicitSwapControl:b(q,"explicitSwapControl",0),renderViaOffscreenBackBuffer:b(q,"renderViaOffscreenBackBuffer",0)};v.majorVersion=q&&q.majorVersion?q.majorVersion:"undefined"!==typeof WebGL2RenderingContext?2:1;if(v.explicitSwapControl)throw"explicitSwapControl is not supported";l=ka(l,v);if(!l)return 0;na(l);A.ce.getExtension("WEBGL_debug_renderer_info");return l};a.deleteContext=function(l){A===oa[l]&&(A=null);"object"==typeof JSEvents&&
JSEvents.rf(oa[l].ce.canvas);oa[l]&&oa[l].ce.canvas&&(oa[l].ce.canvas.Me=void 0);oa[l]=null};a._setTextureCleanup({deleteTexture:function(l,q){var v=ja[q];v&&oa[l].ce.deleteTexture(v);ja[q]=null}});a.MakeWebGLContext=function(l){if(!this.Rd(l))return null;var q=this._MakeGrContext();if(!q)return null;q.Qd=l;var v=q.delete.bind(q);q["delete"]=function(){a.Rd(this.Qd);v()}.bind(q);return A.Ae=q};a.MakeGrContext=a.MakeWebGLContext;a.GrDirectContext.prototype.getResourceCacheLimitBytes=function(){a.Rd(this.Qd);
this._getResourceCacheLimitBytes()};a.GrDirectContext.prototype.getResourceCacheUsageBytes=function(){a.Rd(this.Qd);this._getResourceCacheUsageBytes()};a.GrDirectContext.prototype.releaseResourcesAndAbandonContext=function(){a.Rd(this.Qd);this._releaseResourcesAndAbandonContext()};a.GrDirectContext.prototype.setResourceCacheLimitBytes=function(l){a.Rd(this.Qd);this._setResourceCacheLimitBytes(l)};a.MakeOnScreenGLSurface=function(l,q,v,w,z,D){if(!this.Rd(l.Qd))return null;q=void 0===z||void 0===D?
this._MakeOnScreenGLSurface(l,q,v,w):this._MakeOnScreenGLSurface(l,q,v,w,z,D);if(!q)return null;q.Qd=l.Qd;return q};a.MakeRenderTarget=function(){var l=arguments[0];if(!this.Rd(l.Qd))return null;if(3===arguments.length){var q=this._MakeRenderTargetWH(l,arguments[1],arguments[2]);if(!q)return null}else if(2===arguments.length){if(q=this._MakeRenderTargetII(l,arguments[1]),!q)return null}else return null;q.Qd=l.Qd;return q};a.MakeWebGLCanvasSurface=function(l,q,v){q=q||null;var w=l,z="undefined"!==
typeof OffscreenCanvas&&w instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&w instanceof HTMLCanvasElement||z||(w=document.getElementById(l),w)))throw"Canvas with id "+l+" was not found";l=this.GetWebGLContext(w,v);if(!l||0>l)throw"failed to create webgl context: err "+l;l=this.MakeWebGLContext(l);q=this.MakeOnScreenGLSurface(l,w.width,w.height,q);return q?q:(q=w.cloneNode(!0),w.parentNode.replaceChild(q,w),q.classList.add("ck-replaced"),a.MakeSWCanvasSurface(q))};a.MakeCanvasSurface=
a.MakeWebGLCanvasSurface;a.Surface.prototype.makeImageFromTexture=function(l,q){a.Rd(this.Qd);l=c(l);if(q=this._makeImageFromTexture(this.Qd,l,q))q.le=l;return q};a.Surface.prototype.makeImageFromTextureSource=function(l,q,v){q||={height:e(l),width:f(l),colorType:a.ColorType.RGBA_8888,alphaType:v?a.AlphaType.Premul:a.AlphaType.Unpremul};q.colorSpace||(q.colorSpace=a.ColorSpace.SRGB);a.Rd(this.Qd);var w=A.ce;v=k(w,w.createTexture(),q,v);2===A.version?w.texImage2D(w.TEXTURE_2D,0,w.RGBA,q.width,q.height,
0,w.RGBA,w.UNSIGNED_BYTE,l):w.texImage2D(w.TEXTURE_2D,0,w.RGBA,w.RGBA,w.UNSIGNED_BYTE,l);n(w,q);this._resetContext();return this.makeImageFromTexture(v,q)};a.Surface.prototype.updateTextureFromSource=function(l,q,v){if(l.le){a.Rd(this.Qd);var w=l.getImageInfo(),z=A.ce,D=k(z,ja[l.le],w,v);2===A.version?z.texImage2D(z.TEXTURE_2D,0,z.RGBA,f(q),e(q),0,z.RGBA,z.UNSIGNED_BYTE,q):z.texImage2D(z.TEXTURE_2D,0,z.RGBA,z.RGBA,z.UNSIGNED_BYTE,q);n(z,w,v);this._resetContext();ja[l.le]=null;l.le=c(D);w.colorSpace=
l.getColorSpace();q=this._makeImageFromTexture(this.Qd,l.le,w);v=l.Pd.Sd;z=l.Pd.Wd;l.Pd.Sd=q.Pd.Sd;l.Pd.Wd=q.Pd.Wd;q.Pd.Sd=v;q.Pd.Wd=z;q.delete();w.colorSpace.delete()}};a.MakeLazyImageFromTextureSource=function(l,q,v){q||={height:e(l),width:f(l),colorType:a.ColorType.RGBA_8888,alphaType:v?a.AlphaType.Premul:a.AlphaType.Unpremul};q.colorSpace||(q.colorSpace=a.ColorSpace.SRGB);var w={makeTexture:function(){var z=A,D=z.ce,I=k(D,D.createTexture(),q,v);2===z.version?D.texImage2D(D.TEXTURE_2D,0,D.RGBA,
q.width,q.height,0,D.RGBA,D.UNSIGNED_BYTE,l):D.texImage2D(D.TEXTURE_2D,0,D.RGBA,D.RGBA,D.UNSIGNED_BYTE,l);n(D,q,v);return c(I)},freeSrc:function(){}};"VideoFrame"===l.constructor.name&&(w.freeSrc=function(){l.close()});return a.Image._makeFromGenerator(q,w)};a.Rd=function(l){return l?na(l):!1};a.se=function(){return A&&A.Ae&&!A.Ae.isDeleted()?A.Ae:null}})})(r);
(function(a){function b(g){return(f(255*g[3])<<24|f(255*g[0])<<16|f(255*g[1])<<8|f(255*g[2])<<0)>>>0}function c(g){if(g&&g._ck)return g;if(g instanceof Float32Array){for(var d=Math.floor(g.length/4),h=new Uint32Array(d),m=0;m<d;m++)h[m]=b(g.slice(4*m,4*(m+1)));return h}if(g instanceof Uint32Array)return g;if(g instanceof Array&&g[0]instanceof Float32Array)return g.map(b)}function e(g){if(void 0===g)return 1;var d=parseFloat(g);return g&&-1!==g.indexOf("%")?d/100:d}function f(g){return Math.round(Math.max(0,
Math.min(g||0,255)))}function k(g,d){d&&d._ck||a._free(g)}function n(g,d,h){if(!g||!g.length)return 0;if(g&&g._ck)return g.byteOffset;var m=a[d].BYTES_PER_ELEMENT;h||=a._malloc(g.length*m);a[d].set(g,h/m);return h}function l(g){var d={Zd:0,count:g.length,colorType:a.ColorType.RGBA_F32};if(g instanceof Float32Array)d.Zd=n(g,"HEAPF32"),d.count=g.length/4;else if(g instanceof Uint32Array)d.Zd=n(g,"HEAPU32"),d.colorType=a.ColorType.RGBA_8888;else if(g instanceof Array){if(g&&g.length){for(var h=a._malloc(16*
g.length),m=0,t=h/4,u=0;u<g.length;u++)for(var y=0;4>y;y++)a.HEAPF32[t+m]=g[u][y],m++;g=h}else g=0;d.Zd=g}else throw"Invalid argument to copyFlexibleColorArray, Not a color array "+typeof g;return d}function q(g){if(!g)return 0;var d=Z.toTypedArray();if(g.length){if(6===g.length||9===g.length)return n(g,"HEAPF32",O),6===g.length&&a.HEAPF32.set(Vc,6+O/4),O;if(16===g.length)return d[0]=g[0],d[1]=g[1],d[2]=g[3],d[3]=g[4],d[4]=g[5],d[5]=g[7],d[6]=g[12],d[7]=g[13],d[8]=g[15],O;throw"invalid matrix size";
}if(void 0===g.m11)throw"invalid matrix argument";d[0]=g.m11;d[1]=g.m21;d[2]=g.m41;d[3]=g.m12;d[4]=g.m22;d[5]=g.m42;d[6]=g.m14;d[7]=g.m24;d[8]=g.m44;return O}function v(g){if(!g)return 0;var d=X.toTypedArray();if(g.length){if(16!==g.length&&6!==g.length&&9!==g.length)throw"invalid matrix size";if(16===g.length)return n(g,"HEAPF32",la);d.fill(0);d[0]=g[0];d[1]=g[1];d[3]=g[2];d[4]=g[3];d[5]=g[4];d[7]=g[5];d[10]=1;d[12]=g[6];d[13]=g[7];d[15]=g[8];6===g.length&&(d[12]=0,d[13]=0,d[15]=1);return la}if(void 0===
g.m11)throw"invalid matrix argument";d[0]=g.m11;d[1]=g.m21;d[2]=g.m31;d[3]=g.m41;d[4]=g.m12;d[5]=g.m22;d[6]=g.m32;d[7]=g.m42;d[8]=g.m13;d[9]=g.m23;d[10]=g.m33;d[11]=g.m43;d[12]=g.m14;d[13]=g.m24;d[14]=g.m34;d[15]=g.m44;return la}function w(g,d){return n(g,"HEAPF32",d||da)}function z(g,d,h,m){var t=Ea.toTypedArray();t[0]=g;t[1]=d;t[2]=h;t[3]=m;return da}function D(g){for(var d=new Float32Array(4),h=0;4>h;h++)d[h]=a.HEAPF32[g/4+h];return d}function I(g,d){return n(g,"HEAPF32",d||U)}function P(g,d){return n(g,
"HEAPF32",d||tb)}a.Color=function(g,d,h,m){void 0===m&&(m=1);return a.Color4f(f(g)/255,f(d)/255,f(h)/255,m)};a.ColorAsInt=function(g,d,h,m){void 0===m&&(m=255);return(f(m)<<24|f(g)<<16|f(d)<<8|f(h)<<0&268435455)>>>0};a.Color4f=function(g,d,h,m){void 0===m&&(m=1);return Float32Array.of(g,d,h,m)};Object.defineProperty(a,"TRANSPARENT",{get:function(){return a.Color4f(0,0,0,0)}});Object.defineProperty(a,"BLACK",{get:function(){return a.Color4f(0,0,0,1)}});Object.defineProperty(a,"WHITE",{get:function(){return a.Color4f(1,
1,1,1)}});Object.defineProperty(a,"RED",{get:function(){return a.Color4f(1,0,0,1)}});Object.defineProperty(a,"GREEN",{get:function(){return a.Color4f(0,1,0,1)}});Object.defineProperty(a,"BLUE",{get:function(){return a.Color4f(0,0,1,1)}});Object.defineProperty(a,"YELLOW",{get:function(){return a.Color4f(1,1,0,1)}});Object.defineProperty(a,"CYAN",{get:function(){return a.Color4f(0,1,1,1)}});Object.defineProperty(a,"MAGENTA",{get:function(){return a.Color4f(1,0,1,1)}});a.getColorComponents=function(g){return[Math.floor(255*
g[0]),Math.floor(255*g[1]),Math.floor(255*g[2]),g[3]]};a.parseColorString=function(g,d){g=g.toLowerCase();if(g.startsWith("#")){d=255;switch(g.length){case 9:d=parseInt(g.slice(7,9),16);case 7:var h=parseInt(g.slice(1,3),16);var m=parseInt(g.slice(3,5),16);var t=parseInt(g.slice(5,7),16);break;case 5:d=17*parseInt(g.slice(4,5),16);case 4:h=17*parseInt(g.slice(1,2),16),m=17*parseInt(g.slice(2,3),16),t=17*parseInt(g.slice(3,4),16)}return a.Color(h,m,t,d/255)}return g.startsWith("rgba")?(g=g.slice(5,
-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],e(g[3]))):g.startsWith("rgb")?(g=g.slice(4,-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],e(g[3]))):g.startsWith("gray(")||g.startsWith("hsl")||!d||(g=d[g],void 0===g)?a.BLACK:g};a.multiplyByAlpha=function(g,d){g=g.slice();g[3]=Math.max(0,Math.min(g[3]*d,1));return g};a.Malloc=function(g,d){var h=a._malloc(d*g.BYTES_PER_ELEMENT);return{_ck:!0,length:d,byteOffset:h,he:null,subarray:function(m,t){m=this.toTypedArray().subarray(m,t);m._ck=!0;return m},toTypedArray:function(){if(this.he&&
this.he.length)return this.he;this.he=new g(a.HEAPU8.buffer,h,d);this.he._ck=!0;return this.he}}};a.Free=function(g){a._free(g.byteOffset);g.byteOffset=0;g.toTypedArray=null;g.he=null};var O=0,Z,la=0,X,da=0,Ea,aa,U=0,Tb,Aa=0,Ub,ub=0,Vb,vb=0,$a,Ma=0,Wb,tb=0,Xb,Yb=0,Vc=Float32Array.of(0,0,1);a.onRuntimeInitialized=function(){function g(d,h,m,t,u,y,C){y||(y=4*t.width,t.colorType===a.ColorType.RGBA_F16?y*=2:t.colorType===a.ColorType.RGBA_F32&&(y*=4));var G=y*t.height;var F=u?u.byteOffset:a._malloc(G);
if(C?!d._readPixels(t,F,y,h,m,C):!d._readPixels(t,F,y,h,m))return u||a._free(F),null;if(u)return u.toTypedArray();switch(t.colorType){case a.ColorType.RGBA_8888:case a.ColorType.RGBA_F16:d=(new Uint8Array(a.HEAPU8.buffer,F,G)).slice();break;case a.ColorType.RGBA_F32:d=(new Float32Array(a.HEAPU8.buffer,F,G)).slice();break;default:return null}a._free(F);return d}Ea=a.Malloc(Float32Array,4);da=Ea.byteOffset;X=a.Malloc(Float32Array,16);la=X.byteOffset;Z=a.Malloc(Float32Array,9);O=Z.byteOffset;Wb=a.Malloc(Float32Array,
12);tb=Wb.byteOffset;Xb=a.Malloc(Float32Array,12);Yb=Xb.byteOffset;aa=a.Malloc(Float32Array,4);U=aa.byteOffset;Tb=a.Malloc(Float32Array,4);Aa=Tb.byteOffset;Ub=a.Malloc(Float32Array,3);ub=Ub.byteOffset;Vb=a.Malloc(Float32Array,3);vb=Vb.byteOffset;$a=a.Malloc(Int32Array,4);Ma=$a.byteOffset;a.ColorSpace.SRGB=a.ColorSpace._MakeSRGB();a.ColorSpace.DISPLAY_P3=a.ColorSpace._MakeDisplayP3();a.ColorSpace.ADOBE_RGB=a.ColorSpace._MakeAdobeRGB();a.GlyphRunFlags={IsWhiteSpace:a._GlyphRunFlags_isWhiteSpace};a.Path.MakeFromCmds=
function(d){var h=n(d,"HEAPF32"),m=a.Path._MakeFromCmds(h,d.length);k(h,d);return m};a.Path.MakeFromVerbsPointsWeights=function(d,h,m){var t=n(d,"HEAPU8"),u=n(h,"HEAPF32"),y=n(m,"HEAPF32"),C=a.Path._MakeFromVerbsPointsWeights(t,d.length,u,h.length/2,y,m&&m.length||0);k(t,d);k(u,h);k(y,m);return C};a.PathBuilder.prototype.addArc=function(d,h,m){d=I(d);this._addArc(d,h,m);return this};a.PathBuilder.prototype.addCircle=function(d,h,m,t){this._addCircle(d,h,m,!!t);return this};a.PathBuilder.prototype.addOval=
function(d,h,m){void 0===m&&(m=1);d=I(d);this._addOval(d,!!h,m);return this};a.PathBuilder.prototype.addPath=function(){var d=Array.prototype.slice.call(arguments),h=d[0],m=!1;"boolean"===typeof d[d.length-1]&&(m=d.pop());if(1===d.length)this._addPath(h,1,0,0,0,1,0,0,0,1,m);else if(2===d.length)d=d[1],this._addPath(h,d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1,m);else if(7===d.length||10===d.length)this._addPath(h,d[1],d[2],d[3],d[4],d[5],d[6],d[7]||0,d[8]||0,d[9]||1,m);else return null;
return this};a.PathBuilder.prototype.addPolygon=function(d,h){var m=n(d,"HEAPF32");this._addPolygon(m,d.length/2,h);k(m,d);return this};a.PathBuilder.prototype.addRect=function(d,h){d=I(d);this._addRect(d,!!h);return this};a.PathBuilder.prototype.addRRect=function(d,h){d=P(d);this._addRRect(d,!!h);return this};a.PathBuilder.prototype.addVerbsPointsWeights=function(d,h,m){var t=n(d,"HEAPU8"),u=n(h,"HEAPF32"),y=n(m,"HEAPF32");this._addVerbsPointsWeights(t,d.length,u,h.length/2,y,m&&m.length||0);k(t,
d);k(u,h);k(y,m);return this};a.PathBuilder.prototype.arc=function(d,h,m,t,u,y){d=a.LTRBRect(d-m,h-m,d+m,h+m);u=(u-t)/Math.PI*180-360*!!y;t=(new a.PathBuilder).addArc(d,t/Math.PI*180,u).detachAndDelete();this.addPath(t,!0);t.delete();return this};a.PathBuilder.prototype.arcToOval=function(d,h,m,t){d=I(d);this._arcToOval(d,h,m,t);return this};a.PathBuilder.prototype.arcToRotated=function(d,h,m,t,u,y,C){this._arcToRotated(d,h,m,!!t,!!u,y,C);return this};a.PathBuilder.prototype.arcToTangent=function(d,
h,m,t,u){this._arcToTangent(d,h,m,t,u);return this};a.PathBuilder.prototype.close=function(){this._close();return this};a.PathBuilder.prototype.conicTo=function(d,h,m,t,u){this._conicTo(d,h,m,t,u);return this};a.Path.prototype.computeTightBounds=function(d){this._computeTightBounds(U);var h=aa.toTypedArray();return d?(d.set(h),d):h.slice()};a.PathBuilder.prototype.cubicTo=function(d,h,m,t,u,y){this._cubicTo(d,h,m,t,u,y);return this};a.PathBuilder.prototype.detachAndDelete=function(){var d=this.detach();
this.delete();return d};a.Path.prototype.getBounds=function(d){this._getBounds(U);var h=aa.toTypedArray();return d?(d.set(h),d):h.slice()};a.PathBuilder.prototype.getBounds=function(d){this._getBounds(U);var h=aa.toTypedArray();return d?(d.set(h),d):h.slice()};a.PathBuilder.prototype.lineTo=function(d,h){this._lineTo(d,h);return this};a.PathBuilder.prototype.moveTo=function(d,h){this._moveTo(d,h);return this};a.PathBuilder.prototype.offset=function(d,h){this._transform(1,0,d,0,1,h,0,0,1);return this};
a.PathBuilder.prototype.quadTo=function(d,h,m,t){this._quadTo(d,h,m,t);return this};a.PathBuilder.prototype.rArcTo=function(d,h,m,t,u,y,C){this._rArcTo(d,h,m,t,u,y,C);return this};a.PathBuilder.prototype.rConicTo=function(d,h,m,t,u){this._rConicTo(d,h,m,t,u);return this};a.PathBuilder.prototype.rCubicTo=function(d,h,m,t,u,y){this._rCubicTo(d,h,m,t,u,y);return this};a.PathBuilder.prototype.rLineTo=function(d,h){this._rLineTo(d,h);return this};a.PathBuilder.prototype.rMoveTo=function(d,h){this._rMoveTo(d,
h);return this};a.PathBuilder.prototype.rQuadTo=function(d,h,m,t){this._rQuadTo(d,h,m,t);return this};a.Path.prototype.makeStroked=function(d){d=d||{};d.width=d.width||1;d.miter_limit=d.miter_limit||4;d.cap=d.cap||a.StrokeCap.Butt;d.join=d.join||a.StrokeJoin.Miter;d.precision=d.precision||1;return this._makeStroked(d)};a.PathBuilder.prototype.transform=function(){if(1===arguments.length){var d=arguments[0];this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1)}else if(6===arguments.length||
9===arguments.length)d=arguments,this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.Path.prototype.makeTrimmed=function(d,h,m){return this._makeTrimmed(d,h,!!m)};a.Image.prototype.encodeToBytes=function(d,h){var m=a.se();d=d||a.ImageFormat.PNG;h=h||100;return m?this._encodeToBytes(d,h,m):this._encodeToBytes(d,h)};a.Image.prototype.makeShaderCubic=function(d,h,m,t,u){u=q(u);return this._makeShaderCubic(d,
h,m,t,u)};a.Image.prototype.makeShaderOptions=function(d,h,m,t,u){u=q(u);return this._makeShaderOptions(d,h,m,t,u)};a.Image.prototype.readPixels=function(d,h,m,t,u){var y=a.se();return g(this,d,h,m,t,u,y)};a.Canvas.prototype.clear=function(d){a.Rd(this.Qd);d=w(d);this._clear(d)};a.Canvas.prototype.clipRRect=function(d,h,m){a.Rd(this.Qd);d=P(d);this._clipRRect(d,h,m)};a.Canvas.prototype.clipRect=function(d,h,m){a.Rd(this.Qd);d=I(d);this._clipRect(d,h,m)};a.Canvas.prototype.concat=function(d){a.Rd(this.Qd);
d=v(d);this._concat(d)};a.Canvas.prototype.drawArc=function(d,h,m,t,u){a.Rd(this.Qd);d=I(d);this._drawArc(d,h,m,t,u)};a.Canvas.prototype.drawAtlas=function(d,h,m,t,u,y,C){if(d&&t&&h&&m&&h.length===m.length){a.Rd(this.Qd);u||(u=a.BlendMode.SrcOver);var G=n(h,"HEAPF32"),F=n(m,"HEAPF32"),S=m.length/4,T=n(c(y),"HEAPU32");if(C&&"B"in C&&"C"in C)this._drawAtlasCubic(d,F,G,T,S,u,C.B,C.C,t);else{let p=a.FilterMode.Linear,x=a.MipmapMode.None;C&&(p=C.filter,"mipmap"in C&&(x=C.mipmap));this._drawAtlasOptions(d,
F,G,T,S,u,p,x,t)}k(G,h);k(F,m);k(T,y)}};a.Canvas.prototype.drawCircle=function(d,h,m,t){a.Rd(this.Qd);this._drawCircle(d,h,m,t)};a.Canvas.prototype.drawColor=function(d,h){a.Rd(this.Qd);d=w(d);void 0!==h?this._drawColor(d,h):this._drawColor(d)};a.Canvas.prototype.drawColorInt=function(d,h){a.Rd(this.Qd);this._drawColorInt(d,h||a.BlendMode.SrcOver)};a.Canvas.prototype.drawColorComponents=function(d,h,m,t,u){a.Rd(this.Qd);d=z(d,h,m,t);void 0!==u?this._drawColor(d,u):this._drawColor(d)};a.Canvas.prototype.drawDRRect=
function(d,h,m){a.Rd(this.Qd);d=P(d,tb);h=P(h,Yb);this._drawDRRect(d,h,m)};a.Canvas.prototype.drawImage=function(d,h,m,t){a.Rd(this.Qd);this._drawImage(d,h,m,t||null)};a.Canvas.prototype.drawImageCubic=function(d,h,m,t,u,y){a.Rd(this.Qd);this._drawImageCubic(d,h,m,t,u,y||null)};a.Canvas.prototype.drawImageOptions=function(d,h,m,t,u,y){a.Rd(this.Qd);this._drawImageOptions(d,h,m,t,u,y||null)};a.Canvas.prototype.drawImageNine=function(d,h,m,t,u){a.Rd(this.Qd);h=n(h,"HEAP32",Ma);m=I(m);this._drawImageNine(d,
h,m,t,u||null)};a.Canvas.prototype.drawImageRect=function(d,h,m,t,u){a.Rd(this.Qd);I(h,U);I(m,Aa);this._drawImageRect(d,U,Aa,t,!!u)};a.Canvas.prototype.drawImageRectCubic=function(d,h,m,t,u,y){a.Rd(this.Qd);I(h,U);I(m,Aa);this._drawImageRectCubic(d,U,Aa,t,u,y||null)};a.Canvas.prototype.drawImageRectOptions=function(d,h,m,t,u,y){a.Rd(this.Qd);I(h,U);I(m,Aa);this._drawImageRectOptions(d,U,Aa,t,u,y||null)};a.Canvas.prototype.drawLine=function(d,h,m,t,u){a.Rd(this.Qd);this._drawLine(d,h,m,t,u)};a.Canvas.prototype.drawOval=
function(d,h){a.Rd(this.Qd);d=I(d);this._drawOval(d,h)};a.Canvas.prototype.drawPaint=function(d){a.Rd(this.Qd);this._drawPaint(d)};a.Canvas.prototype.drawParagraph=function(d,h,m){a.Rd(this.Qd);this._drawParagraph(d,h,m)};a.Canvas.prototype.drawPatch=function(d,h,m,t,u){if(24>d.length)throw"Need 12 cubic points";if(h&&4>h.length)throw"Need 4 colors";if(m&&8>m.length)throw"Need 4 shader coordinates";a.Rd(this.Qd);const y=n(d,"HEAPF32"),C=h?n(c(h),"HEAPU32"):0,G=m?n(m,"HEAPF32"):0;t||(t=a.BlendMode.Modulate);
this._drawPatch(y,C,G,t,u);k(G,m);k(C,h);k(y,d)};a.Canvas.prototype.drawPath=function(d,h){a.Rd(this.Qd);this._drawPath(d,h)};a.Canvas.prototype.drawPicture=function(d){a.Rd(this.Qd);this._drawPicture(d)};a.Canvas.prototype.drawPoints=function(d,h,m){a.Rd(this.Qd);var t=n(h,"HEAPF32");this._drawPoints(d,t,h.length/2,m);k(t,h)};a.Canvas.prototype.drawRRect=function(d,h){a.Rd(this.Qd);d=P(d);this._drawRRect(d,h)};a.Canvas.prototype.drawRect=function(d,h){a.Rd(this.Qd);d=I(d);this._drawRect(d,h)};a.Canvas.prototype.drawRect4f=
function(d,h,m,t,u){a.Rd(this.Qd);this._drawRect4f(d,h,m,t,u)};a.Canvas.prototype.drawShadow=function(d,h,m,t,u,y,C){a.Rd(this.Qd);var G=n(u,"HEAPF32"),F=n(y,"HEAPF32");h=n(h,"HEAPF32",ub);m=n(m,"HEAPF32",vb);this._drawShadow(d,h,m,t,G,F,C);k(G,u);k(F,y)};a.getShadowLocalBounds=function(d,h,m,t,u,y,C){d=q(d);m=n(m,"HEAPF32",ub);t=n(t,"HEAPF32",vb);if(!this._getShadowLocalBounds(d,h,m,t,u,y,U))return null;h=aa.toTypedArray();return C?(C.set(h),C):h.slice()};a.Canvas.prototype.drawTextBlob=function(d,
h,m,t){a.Rd(this.Qd);this._drawTextBlob(d,h,m,t)};a.Canvas.prototype.drawVertices=function(d,h,m){a.Rd(this.Qd);this._drawVertices(d,h,m)};a.Canvas.prototype.getDeviceClipBounds=function(d){this._getDeviceClipBounds(Ma);var h=$a.toTypedArray();d?d.set(h):d=h.slice();return d};a.Canvas.prototype.quickReject=function(d){d=I(d);return this._quickReject(d)};a.Canvas.prototype.getLocalToDevice=function(){this._getLocalToDevice(la);for(var d=la,h=Array(16),m=0;16>m;m++)h[m]=a.HEAPF32[d/4+m];return h};a.Canvas.prototype.getTotalMatrix=
function(){this._getTotalMatrix(O);for(var d=Array(9),h=0;9>h;h++)d[h]=a.HEAPF32[O/4+h];return d};a.Canvas.prototype.makeSurface=function(d){d=this._makeSurface(d);d.Qd=this.Qd;return d};a.Canvas.prototype.readPixels=function(d,h,m,t,u){a.Rd(this.Qd);return g(this,d,h,m,t,u)};a.Canvas.prototype.saveLayer=function(d,h,m,t,u){h=I(h);return this._saveLayer(d||null,h,m||null,t||0,u||a.TileMode.Clamp)};a.Canvas.prototype.writePixels=function(d,h,m,t,u,y,C,G){if(d.byteLength%(h*m))throw"pixels length must be a multiple of the srcWidth * srcHeight";
a.Rd(this.Qd);var F=d.byteLength/(h*m);y=y||a.AlphaType.Unpremul;C=C||a.ColorType.RGBA_8888;G=G||a.ColorSpace.SRGB;var S=F*h;F=n(d,"HEAPU8");h=this._writePixels({width:h,height:m,colorType:C,alphaType:y,colorSpace:G},F,S,t,u);k(F,d);return h};a.ColorFilter.MakeBlend=function(d,h,m){d=w(d);m=m||a.ColorSpace.SRGB;return a.ColorFilter._MakeBlend(d,h,m)};a.ColorFilter.MakeMatrix=function(d){if(!d||20!==d.length)throw"invalid color matrix";var h=n(d,"HEAPF32"),m=a.ColorFilter._makeMatrix(h);k(h,d);return m};
a.ContourMeasure.prototype.getPosTan=function(d,h){this._getPosTan(d,U);d=aa.toTypedArray();return h?(h.set(d),h):d.slice()};a.ImageFilter.prototype.getOutputBounds=function(d,h,m){d=I(d,U);h=q(h);this._getOutputBounds(d,h,Ma);h=$a.toTypedArray();return m?(m.set(h),m):h.slice()};a.ImageFilter.MakeDropShadow=function(d,h,m,t,u,y){u=w(u,da);return a.ImageFilter._MakeDropShadow(d,h,m,t,u,y)};a.ImageFilter.MakeDropShadowOnly=function(d,h,m,t,u,y){u=w(u,da);return a.ImageFilter._MakeDropShadowOnly(d,h,
m,t,u,y)};a.ImageFilter.MakeImage=function(d,h,m,t){m=I(m,U);t=I(t,Aa);if("B"in h&&"C"in h)return a.ImageFilter._MakeImageCubic(d,h.B,h.C,m,t);const u=h.filter;let y=a.MipmapMode.None;"mipmap"in h&&(y=h.mipmap);return a.ImageFilter._MakeImageOptions(d,u,y,m,t)};a.ImageFilter.MakeMatrixTransform=function(d,h,m){d=q(d);if("B"in h&&"C"in h)return a.ImageFilter._MakeMatrixTransformCubic(d,h.B,h.C,m);const t=h.filter;let u=a.MipmapMode.None;"mipmap"in h&&(u=h.mipmap);return a.ImageFilter._MakeMatrixTransformOptions(d,
t,u,m)};a.Paint.prototype.getColor=function(){this._getColor(da);return D(da)};a.Paint.prototype.setColor=function(d,h){h=h||null;d=w(d);this._setColor(d,h)};a.Paint.prototype.setColorComponents=function(d,h,m,t,u){u=u||null;d=z(d,h,m,t);this._setColor(d,u)};a.Path.prototype.getPoint=function(d,h){this._getPoint(d,U);d=aa.toTypedArray();return h?(h[0]=d[0],h[1]=d[1],h):d.slice(0,2)};a.Picture.prototype.makeShader=function(d,h,m,t,u){t=q(t);u=I(u);return this._makeShader(d,h,m,t,u)};a.Picture.prototype.cullRect=
function(d){this._cullRect(U);var h=aa.toTypedArray();return d?(d.set(h),d):h.slice()};a.PictureRecorder.prototype.beginRecording=function(d,h){d=I(d);return this._beginRecording(d,!!h)};a.Surface.prototype.getCanvas=function(){var d=this._getCanvas();d.Qd=this.Qd;return d};a.Surface.prototype.makeImageSnapshot=function(d){a.Rd(this.Qd);d=n(d,"HEAP32",Ma);return this._makeImageSnapshot(d)};a.Surface.prototype.makeSurface=function(d){a.Rd(this.Qd);d=this._makeSurface(d);d.Qd=this.Qd;return d};a.Surface.prototype.Qe=
function(d,h){this.ke||(this.ke=this.getCanvas());return requestAnimationFrame(function(){a.Rd(this.Qd);d(this.ke);this.flush(h)}.bind(this))};a.Surface.prototype.requestAnimationFrame||(a.Surface.prototype.requestAnimationFrame=a.Surface.prototype.Qe);a.Surface.prototype.Ne=function(d,h){this.ke||(this.ke=this.getCanvas());requestAnimationFrame(function(){a.Rd(this.Qd);d(this.ke);this.flush(h);this.dispose()}.bind(this))};a.Surface.prototype.drawOnce||(a.Surface.prototype.drawOnce=a.Surface.prototype.Ne);
a.PathEffect.MakeDash=function(d,h){h||=0;if(!d.length||1===d.length%2)throw"Intervals array must have even length";var m=n(d,"HEAPF32");h=a.PathEffect._MakeDash(m,d.length,h);k(m,d);return h};a.PathEffect.MakeLine2D=function(d,h){h=q(h);return a.PathEffect._MakeLine2D(d,h)};a.PathEffect.MakePath2D=function(d,h){d=q(d);return a.PathEffect._MakePath2D(d,h)};a.Shader.MakeColor=function(d,h){h=h||null;d=w(d);return a.Shader._MakeColor(d,h)};a.Shader.Blend=a.Shader.MakeBlend;a.Shader.Color=a.Shader.MakeColor;
a.Shader.MakeLinearGradient=function(d,h,m,t,u,y,C,G){G=G||null;var F=l(m),S=n(t,"HEAPF32");C=C||0;y=q(y);var T=aa.toTypedArray();T.set(d);T.set(h,2);d=a.Shader._MakeLinearGradient(U,F.Zd,F.colorType,S,F.count,u,C,y,G);k(F.Zd,m);t&&k(S,t);return d};a.Shader.MakeRadialGradient=function(d,h,m,t,u,y,C,G){G=G||null;var F=l(m),S=n(t,"HEAPF32");C=C||0;y=q(y);d=a.Shader._MakeRadialGradient(d[0],d[1],h,F.Zd,F.colorType,S,F.count,u,C,y,G);k(F.Zd,m);t&&k(S,t);return d};a.Shader.MakeSweepGradient=function(d,
h,m,t,u,y,C,G,F,S){S=S||null;var T=l(m),p=n(t,"HEAPF32");C=C||0;G=G||0;F=F||360;y=q(y);d=a.Shader._MakeSweepGradient(d,h,T.Zd,T.colorType,p,T.count,u,G,F,C,y,S);k(T.Zd,m);t&&k(p,t);return d};a.Shader.MakeTwoPointConicalGradient=function(d,h,m,t,u,y,C,G,F,S){S=S||null;var T=l(u),p=n(y,"HEAPF32");F=F||0;G=q(G);var x=aa.toTypedArray();x.set(d);x.set(m,2);d=a.Shader._MakeTwoPointConicalGradient(U,h,t,T.Zd,T.colorType,p,T.count,C,F,G,S);k(T.Zd,u);y&&k(p,y);return d};a.Vertices.prototype.bounds=function(d){this._bounds(U);
var h=aa.toTypedArray();return d?(d.set(h),d):h.slice()};a.Ud&&a.Ud.forEach(function(d){d()})};a.computeTonalColors=function(g){var d=n(g.ambient,"HEAPF32"),h=n(g.spot,"HEAPF32");this._computeTonalColors(d,h);var m={ambient:D(d),spot:D(h)};k(d,g.ambient);k(h,g.spot);return m};a.LTRBRect=function(g,d,h,m){return Float32Array.of(g,d,h,m)};a.XYWHRect=function(g,d,h,m){return Float32Array.of(g,d,g+h,d+m)};a.LTRBiRect=function(g,d,h,m){return Int32Array.of(g,d,h,m)};a.XYWHiRect=function(g,d,h,m){return Int32Array.of(g,
d,g+h,d+m)};a.RRectXY=function(g,d,h){return Float32Array.of(g[0],g[1],g[2],g[3],d,h,d,h,d,h,d,h)};a.MakeAnimatedImageFromEncoded=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._decodeAnimatedImage(d,g.byteLength))?g:null};a.MakeImageFromEncoded=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._decodeImage(d,g.byteLength))?g:null};var ab=null;a.MakeImageFromCanvasImageSource=function(g){var d=g.width,h=g.height;
ab||=document.createElement("canvas");ab.width=d;ab.height=h;var m=ab.getContext("2d",{willReadFrequently:!0});m.drawImage(g,0,0);g=m.getImageData(0,0,d,h);return a.MakeImage({width:d,height:h,alphaType:a.AlphaType.Unpremul,colorType:a.ColorType.RGBA_8888,colorSpace:a.ColorSpace.SRGB},g.data,4*d)};a.MakeImage=function(g,d,h){var m=a._malloc(d.length);a.HEAPU8.set(d,m);return a._MakeImage(g,m,d.length,h)};a.MakeVertices=function(g,d,h,m,t,u){var y=t&&t.length||0,C=0;h&&h.length&&(C|=1);m&&m.length&&
(C|=2);void 0===u||u||(C|=4);g=new a._VerticesBuilder(g,d.length/2,y,C);n(d,"HEAPF32",g.positions());g.texCoords()&&n(h,"HEAPF32",g.texCoords());g.colors()&&n(c(m),"HEAPU32",g.colors());g.indices()&&n(t,"HEAPU16",g.indices());return g.detach()};(function(g){g.Ud=g.Ud||[];g.Ud.push(function(){function d(p){p&&(p.dir=0===p.dir?g.TextDirection.RTL:g.TextDirection.LTR);return p}function h(p){if(!p||!p.length)return[];for(var x=[],M=0;M<p.length;M+=5){var W=g.LTRBRect(p[M],p[M+1],p[M+2],p[M+3]),wa=g.TextDirection.LTR;
0===p[M+4]&&(wa=g.TextDirection.RTL);x.push({rect:W,dir:wa})}g._free(p.byteOffset);return x}function m(p){p=p||{};void 0===p.weight&&(p.weight=g.FontWeight.Normal);p.width=p.width||g.FontWidth.Normal;p.slant=p.slant||g.FontSlant.Upright;return p}function t(p){if(!p||!p.length)return 0;for(var x=[],M=0;M<p.length;M++){var W=u(p[M]);x.push(W)}return n(x,"HEAPU32")}function u(p){if(G[p])return G[p];var x=pa(p)+1,M=g._malloc(x);qa(p,M,x);return G[p]=M}function y(p){p._colorPtr=w(p.color);p._foregroundColorPtr=
0;p._backgroundColorPtr=0;p._decorationColorPtr=0;p.foregroundColor&&(p._foregroundColorPtr=w(p.foregroundColor,F));p.backgroundColor&&(p._backgroundColorPtr=w(p.backgroundColor,S));p.decorationColor&&(p._decorationColorPtr=w(p.decorationColor,T));Array.isArray(p.fontFamilies)&&p.fontFamilies.length?(p._fontFamiliesPtr=t(p.fontFamilies),p._fontFamiliesLen=p.fontFamilies.length):(p._fontFamiliesPtr=0,p._fontFamiliesLen=0);if(p.locale){var x=p.locale;p._localePtr=u(x);p._localeLen=pa(x)}else p._localePtr=
0,p._localeLen=0;if(Array.isArray(p.shadows)&&p.shadows.length){x=p.shadows;var M=x.map(function(ma){return ma.color||g.BLACK}),W=x.map(function(ma){return ma.blurRadius||0});p._shadowLen=x.length;for(var wa=g._malloc(8*x.length),wb=wa/4,xb=0;xb<x.length;xb++){var Zb=x[xb].offset||[0,0];g.HEAPF32[wb]=Zb[0];g.HEAPF32[wb+1]=Zb[1];wb+=2}p._shadowColorsPtr=l(M).Zd;p._shadowOffsetsPtr=wa;p._shadowBlurRadiiPtr=n(W,"HEAPF32")}else p._shadowLen=0,p._shadowColorsPtr=0,p._shadowOffsetsPtr=0,p._shadowBlurRadiiPtr=
0;Array.isArray(p.fontFeatures)&&p.fontFeatures.length?(x=p.fontFeatures,M=x.map(function(ma){return ma.name}),W=x.map(function(ma){return ma.value}),p._fontFeatureLen=x.length,p._fontFeatureNamesPtr=t(M),p._fontFeatureValuesPtr=n(W,"HEAPU32")):(p._fontFeatureLen=0,p._fontFeatureNamesPtr=0,p._fontFeatureValuesPtr=0);Array.isArray(p.fontVariations)&&p.fontVariations.length?(x=p.fontVariations,M=x.map(function(ma){return ma.axis}),W=x.map(function(ma){return ma.value}),p._fontVariationLen=x.length,
p._fontVariationAxesPtr=t(M),p._fontVariationValuesPtr=n(W,"HEAPF32")):(p._fontVariationLen=0,p._fontVariationAxesPtr=0,p._fontVariationValuesPtr=0)}function C(p){g._free(p._fontFamiliesPtr);g._free(p._shadowColorsPtr);g._free(p._shadowOffsetsPtr);g._free(p._shadowBlurRadiiPtr);g._free(p._fontFeatureNamesPtr);g._free(p._fontFeatureValuesPtr);g._free(p._fontVariationAxesPtr);g._free(p._fontVariationValuesPtr)}g.Paragraph.prototype.getRectsForRange=function(p,x,M,W){p=this._getRectsForRange(p,x,M,W);
return h(p)};g.Paragraph.prototype.getRectsForPlaceholders=function(){var p=this._getRectsForPlaceholders();return h(p)};g.Paragraph.prototype.getGlyphInfoAt=function(p){return d(this._getGlyphInfoAt(p))};g.Paragraph.prototype.getClosestGlyphInfoAtCoordinate=function(p,x){return d(this._getClosestGlyphInfoAtCoordinate(p,x))};g.TypefaceFontProvider.prototype.registerFont=function(p,x){p=g.Typeface.MakeTypefaceFromData(p);if(!p)return null;x=u(x);this._registerFont(p,x);p.delete()};g.ParagraphStyle=
function(p){p.disableHinting=p.disableHinting||!1;if(p.ellipsis){var x=p.ellipsis;p._ellipsisPtr=u(x);p._ellipsisLen=pa(x)}else p._ellipsisPtr=0,p._ellipsisLen=0;null==p.heightMultiplier&&(p.heightMultiplier=-1);p.maxLines=p.maxLines||0;p.replaceTabCharacters=p.replaceTabCharacters||!1;x=(x=p.strutStyle)||{};x.strutEnabled=x.strutEnabled||!1;x.strutEnabled&&Array.isArray(x.fontFamilies)&&x.fontFamilies.length?(x._fontFamiliesPtr=t(x.fontFamilies),x._fontFamiliesLen=x.fontFamilies.length):(x._fontFamiliesPtr=
0,x._fontFamiliesLen=0);x.fontStyle=m(x.fontStyle);null==x.fontSize&&(x.fontSize=-1);null==x.heightMultiplier&&(x.heightMultiplier=-1);x.halfLeading=x.halfLeading||!1;x.leading=x.leading||0;x.forceStrutHeight=x.forceStrutHeight||!1;p.strutStyle=x;p.textAlign=p.textAlign||g.TextAlign.Start;p.textDirection=p.textDirection||g.TextDirection.LTR;p.textHeightBehavior=p.textHeightBehavior||g.TextHeightBehavior.All;p.textStyle=g.TextStyle(p.textStyle);p.applyRoundingHack=!1!==p.applyRoundingHack;return p};
g.TextStyle=function(p){p.color||(p.color=g.BLACK);p.decoration=p.decoration||0;p.decorationThickness=p.decorationThickness||0;p.decorationStyle=p.decorationStyle||g.DecorationStyle.Solid;p.textBaseline=p.textBaseline||g.TextBaseline.Alphabetic;null==p.fontSize&&(p.fontSize=-1);p.letterSpacing=p.letterSpacing||0;p.wordSpacing=p.wordSpacing||0;null==p.heightMultiplier&&(p.heightMultiplier=-1);p.halfLeading=p.halfLeading||!1;p.fontStyle=m(p.fontStyle);return p};var G={},F=g._malloc(16),S=g._malloc(16),
T=g._malloc(16);g.ParagraphBuilder.Make=function(p,x){y(p.textStyle);x=g.ParagraphBuilder._Make(p,x);C(p.textStyle);return x};g.ParagraphBuilder.MakeFromFontProvider=function(p,x){y(p.textStyle);x=g.ParagraphBuilder._MakeFromFontProvider(p,x);C(p.textStyle);return x};g.ParagraphBuilder.MakeFromFontCollection=function(p,x){y(p.textStyle);x=g.ParagraphBuilder._MakeFromFontCollection(p,x);C(p.textStyle);return x};g.ParagraphBuilder.ShapeText=function(p,x,M){let W=0;for(const wa of x)W+=wa.length;if(W!==
p.length)throw"Accumulated block lengths must equal text.length";return g.ParagraphBuilder._ShapeText(p,x,M)};g.ParagraphBuilder.prototype.pushStyle=function(p){y(p);this._pushStyle(p);C(p)};g.ParagraphBuilder.prototype.pushPaintStyle=function(p,x,M){y(p);this._pushPaintStyle(p,x,M);C(p)};g.ParagraphBuilder.prototype.addPlaceholder=function(p,x,M,W,wa){M=M||g.PlaceholderAlignment.Baseline;W=W||g.TextBaseline.Alphabetic;this._addPlaceholder(p||0,x||0,M,W,wa||0)};g.ParagraphBuilder.prototype.setWordsUtf8=
function(p){var x=n(p,"HEAPU32");this._setWordsUtf8(x,p&&p.length||0);k(x,p)};g.ParagraphBuilder.prototype.setWordsUtf16=function(p){var x=n(p,"HEAPU32");this._setWordsUtf16(x,p&&p.length||0);k(x,p)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf8=function(p){var x=n(p,"HEAPU32");this._setGraphemeBreaksUtf8(x,p&&p.length||0);k(x,p)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf16=function(p){var x=n(p,"HEAPU32");this._setGraphemeBreaksUtf16(x,p&&p.length||0);k(x,p)};g.ParagraphBuilder.prototype.setLineBreaksUtf8=
function(p){var x=n(p,"HEAPU32");this._setLineBreaksUtf8(x,p&&p.length||0);k(x,p)};g.ParagraphBuilder.prototype.setLineBreaksUtf16=function(p){var x=n(p,"HEAPU32");this._setLineBreaksUtf16(x,p&&p.length||0);k(x,p)}})})(r);a.Ud=a.Ud||[];a.Ud.push(function(){});a.Ud=a.Ud||[];a.Ud.push(function(){a.Canvas.prototype.drawText=function(g,d,h,m,t){var u=pa(g),y=a._malloc(u+1);qa(g,y,u+1);this._drawSimpleText(y,u,d,h,t,m);a._free(y)};a.Canvas.prototype.drawGlyphs=function(g,d,h,m,t,u){if(!(2*g.length<=d.length))throw"Not enough positions for the array of gyphs";
a.Rd(this.Qd);const y=n(g,"HEAPU16"),C=n(d,"HEAPF32");this._drawGlyphs(g.length,y,C,h,m,t,u);k(C,d);k(y,g)};a.Font.prototype.getGlyphBounds=function(g,d,h){var m=n(g,"HEAPU16"),t=a._malloc(16*g.length);this._getGlyphWidthBounds(m,g.length,0,t,d||null);d=new Float32Array(a.HEAPU8.buffer,t,4*g.length);k(m,g);if(h)return h.set(d),a._free(t),h;g=Float32Array.from(d);a._free(t);return g};a.Font.prototype.getGlyphIDs=function(g,d,h){d||(d=g.length);var m=pa(g)+1,t=a._malloc(m);qa(g,t,m);g=a._malloc(2*d);
d=this._getGlyphIDs(t,m-1,d,g);a._free(t);if(0>d)return a._free(g),null;t=new Uint16Array(a.HEAPU8.buffer,g,d);if(h)return h.set(t),a._free(g),h;h=Uint16Array.from(t);a._free(g);return h};a.Font.prototype.getGlyphIntercepts=function(g,d,h,m){var t=n(g,"HEAPU16"),u=n(d,"HEAPF32");return this._getGlyphIntercepts(t,g.length,!(g&&g._ck),u,d.length,!(d&&d._ck),h,m)};a.Font.prototype.getGlyphWidths=function(g,d,h){var m=n(g,"HEAPU16"),t=a._malloc(4*g.length);this._getGlyphWidthBounds(m,g.length,t,0,d||
null);d=new Float32Array(a.HEAPU8.buffer,t,g.length);k(m,g);if(h)return h.set(d),a._free(t),h;g=Float32Array.from(d);a._free(t);return g};a.FontMgr.FromData=function(){if(!arguments.length)return null;var g=arguments;1===g.length&&Array.isArray(g[0])&&(g=arguments[0]);if(!g.length)return null;for(var d=[],h=[],m=0;m<g.length;m++){var t=new Uint8Array(g[m]),u=n(t,"HEAPU8");d.push(u);h.push(t.byteLength)}d=n(d,"HEAPU32");h=n(h,"HEAPU32");g=a.FontMgr._fromData(d,h,g.length);a._free(d);a._free(h);return g};
a.Typeface.MakeTypefaceFromData=function(g){g=new Uint8Array(g);var d=n(g,"HEAPU8");return(g=a.Typeface._MakeTypefaceFromData(d,g.byteLength))?g:null};a.Typeface.MakeFreeTypeFaceFromData=a.Typeface.MakeTypefaceFromData;a.Typeface.prototype.getGlyphIDs=function(g,d,h){d||(d=g.length);var m=pa(g)+1,t=a._malloc(m);qa(g,t,m);g=a._malloc(2*d);d=this._getGlyphIDs(t,m-1,d,g);a._free(t);if(0>d)return a._free(g),null;t=new Uint16Array(a.HEAPU8.buffer,g,d);if(h)return h.set(t),a._free(g),h;h=Uint16Array.from(t);
a._free(g);return h};a.TextBlob.MakeOnPath=function(g,d,h,m){if(g&&g.length&&d&&d.countPoints()){if(1===d.countPoints())return this.MakeFromText(g,h);m||=0;var t=h.getGlyphIDs(g);t=h.getGlyphWidths(t);var u=[];d=new a.ContourMeasureIter(d,!1,1);for(var y=d.next(),C=new Float32Array(4),G=0;G<g.length&&y;G++){var F=t[G];m+=F/2;if(m>y.length()){y.delete();y=d.next();if(!y){g=g.substring(0,G);break}m=F/2}y.getPosTan(m,C);var S=C[2],T=C[3];u.push(S,T,C[0]-F/2*S,C[1]-F/2*T);m+=F/2}g=this.MakeFromRSXform(g,
u,h);y&&y.delete();d.delete();return g}};a.TextBlob.MakeFromRSXform=function(g,d,h){var m=pa(g)+1,t=a._malloc(m);qa(g,t,m);g=n(d,"HEAPF32");h=a.TextBlob._MakeFromRSXform(t,m-1,g,h);a._free(t);return h?h:null};a.TextBlob.MakeFromRSXformGlyphs=function(g,d,h){var m=n(g,"HEAPU16");d=n(d,"HEAPF32");h=a.TextBlob._MakeFromRSXformGlyphs(m,2*g.length,d,h);k(m,g);return h?h:null};a.TextBlob.MakeFromGlyphs=function(g,d){var h=n(g,"HEAPU16");d=a.TextBlob._MakeFromGlyphs(h,2*g.length,d);k(h,g);return d?d:null};
a.TextBlob.MakeFromText=function(g,d){var h=pa(g)+1,m=a._malloc(h);qa(g,m,h);g=a.TextBlob._MakeFromText(m,h-1,d);a._free(m);return g?g:null};a.MallocGlyphIDs=function(g){return a.Malloc(Uint16Array,g)}});a.Ud=a.Ud||[];a.Ud.push(function(){a.MakePicture=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._MakePicture(d,g.byteLength))?g:null}});a.Ud=a.Ud||[];a.Ud.push(function(){a.RuntimeEffect.Make=function(g,d){return a.RuntimeEffect._Make(g,{onError:d||function(h){console.log("RuntimeEffect error",
h)}})};a.RuntimeEffect.MakeForBlender=function(g,d){return a.RuntimeEffect._MakeForBlender(g,{onError:d||function(h){console.log("RuntimeEffect error",h)}})};a.RuntimeEffect.prototype.makeShader=function(g,d){var h=!g._ck,m=n(g,"HEAPF32");d=q(d);return this._makeShader(m,4*g.length,h,d)};a.RuntimeEffect.prototype.makeShaderWithChildren=function(g,d,h){var m=!g._ck,t=n(g,"HEAPF32");h=q(h);for(var u=[],y=0;y<d.length;y++)u.push(d[y].Pd.Sd);d=n(u,"HEAPU32");return this._makeShaderWithChildren(t,4*g.length,
m,d,u.length,h)};a.RuntimeEffect.prototype.makeBlender=function(g){var d=!g._ck,h=n(g,"HEAPF32");return this._makeBlender(h,4*g.length,d)}})})(r);var ra=Object.assign({},r),sa="",ta,ua;
if(fa||ha)ha?sa=self.location.href:"undefined"!=typeof document&&document.currentScript&&(sa=document.currentScript.src),_scriptName&&(sa=_scriptName),sa.startsWith("blob:")?sa="":sa=sa.substr(0,sa.replace(/[?#].*/,"").lastIndexOf("/")+1),ha&&(ua=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ta=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));
var va=console.log.bind(console),xa=console.error.bind(console);Object.assign(r,ra);ra=null;var ya,za=!1,Ba,B,Ca,Da,E,H,J,Fa;function Ga(){var a=ya.buffer;r.HEAP8=Ba=new Int8Array(a);r.HEAP16=Ca=new Int16Array(a);r.HEAPU8=B=new Uint8Array(a);r.HEAPU16=Da=new Uint16Array(a);r.HEAP32=E=new Int32Array(a);r.HEAPU32=H=new Uint32Array(a);r.HEAPF32=J=new Float32Array(a);r.HEAPF64=Fa=new Float64Array(a)}var Ha=[],Ia=[],Ja=[],Ka=0,La=null,Na=null;
function Oa(a){a="Aborted("+a+")";xa(a);za=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}var Pa=a=>a.startsWith("data:application/octet-stream;base64,"),Qa;function Ra(a){return ta(a).then(b=>new Uint8Array(b),()=>{if(ua)var b=ua(a);else throw"both async and sync fetching of the wasm failed";return b})}function Sa(a,b,c){return Ra(a).then(e=>WebAssembly.instantiate(e,b)).then(c,e=>{xa(`failed to asynchronously prepare wasm: ${e}`);Oa(e)})}
function Ta(a,b){var c=Qa;return"function"!=typeof WebAssembly.instantiateStreaming||Pa(c)||"function"!=typeof fetch?Sa(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(f){xa(`wasm streaming compile failed: ${f}`);xa("falling back to ArrayBuffer instantiation");return Sa(c,a,b)}))}var Ua=a=>{a.forEach(b=>b(r))};class Va{constructor(a){this.Sd=a-24}}
var Wa=0,Xa=0,Ya="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Za=(a,b=0,c=NaN)=>{var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&Ya)return Ya.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var n=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|n:(f&7)<<18|k<<12|n<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e},
bb={},cb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function db(a){return this.fromWireType(H[a>>2])}
var eb={},fb={},gb={},hb,jb=(a,b,c)=>{function e(l){l=c(l);if(l.length!==a.length)throw new hb("Mismatched type converter count");for(var q=0;q<a.length;++q)ib(a[q],l[q])}a.forEach(l=>gb[l]=b);var f=Array(b.length),k=[],n=0;b.forEach((l,q)=>{fb.hasOwnProperty(l)?f[q]=fb[l]:(k.push(l),eb.hasOwnProperty(l)||(eb[l]=[]),eb[l].push(()=>{f[q]=fb[l];++n;n===k.length&&e(f)}))});0===k.length&&e(f)},kb,K=a=>{for(var b="";B[a];)b+=kb[B[a++]];return b},L;
function lb(a,b,c={}){var e=b.name;if(!a)throw new L(`type "${e}" must have a positive integer typeid pointer`);if(fb.hasOwnProperty(a)){if(c.bf)return;throw new L(`Cannot register type '${e}' twice`);}fb[a]=b;delete gb[a];eb.hasOwnProperty(a)&&(b=eb[a],delete eb[a],b.forEach(f=>f()))}function ib(a,b,c={}){return lb(a,b,c)}
var mb=a=>{throw new L(a.Pd.Vd.Td.name+" instance already deleted");},nb=!1,ob=()=>{},pb=(a,b,c)=>{if(b===c)return a;if(void 0===c.Yd)return null;a=pb(a,b,c.Yd);return null===a?null:c.Ue(a)},qb={},rb={},sb=(a,b)=>{if(void 0===b)throw new L("ptr should not be undefined");for(;a.Yd;)b=a.pe(b),a=a.Yd;return rb[b]},zb=(a,b)=>{if(!b.Vd||!b.Sd)throw new hb("makeClassHandle requires ptr and ptrType");if(!!b.$d!==!!b.Wd)throw new hb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return yb(Object.create(a,
{Pd:{value:b,writable:!0}}))},yb=a=>{if("undefined"===typeof FinalizationRegistry)return yb=b=>b,a;nb=new FinalizationRegistry(b=>{b=b.Pd;--b.count.value;0===b.count.value&&(b.Wd?b.$d.ee(b.Wd):b.Vd.Td.ee(b.Sd))});yb=b=>{var c=b.Pd;c.Wd&&nb.register(b,{Pd:c},b);return b};ob=b=>{nb.unregister(b)};return yb(a)},Ab=[];function Bb(){}
var Cb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Db=(a,b,c)=>{if(void 0===a[b].Xd){var e=a[b];a[b]=function(...f){if(!a[b].Xd.hasOwnProperty(f.length))throw new L(`Function '${c}' called with an invalid number of arguments (${f.length}) - expects one of (${a[b].Xd})!`);return a[b].Xd[f.length].apply(this,f)};a[b].Xd=[];a[b].Xd[e.fe]=e}},Eb=(a,b,c)=>{if(r.hasOwnProperty(a)){if(void 0===c||void 0!==r[a].Xd&&void 0!==r[a].Xd[c])throw new L(`Cannot register public name '${a}' twice`);Db(r,a,a);
if(r[a].Xd.hasOwnProperty(c))throw new L(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);r[a].Xd[c]=b}else r[a]=b,r[a].fe=c},Fb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Gb(a,b,c,e,f,k,n,l){this.name=a;this.constructor=b;this.je=c;this.ee=e;this.Yd=f;this.Xe=k;this.pe=n;this.Ue=l;this.ef=[]}
var Hb=(a,b,c)=>{for(;b!==c;){if(!b.pe)throw new L(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.pe(a);b=b.Yd}return a};function Ib(a,b){if(null===b){if(this.Be)throw new L(`null is not a valid ${this.name}`);return 0}if(!b.Pd)throw new L(`Cannot pass "${Jb(b)}" as a ${this.name}`);if(!b.Pd.Sd)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);return Hb(b.Pd.Sd,b.Pd.Vd.Td,this.Td)}
function Kb(a,b){if(null===b){if(this.Be)throw new L(`null is not a valid ${this.name}`);if(this.ue){var c=this.Ce();null!==a&&a.push(this.ee,c);return c}return 0}if(!b||!b.Pd)throw new L(`Cannot pass "${Jb(b)}" as a ${this.name}`);if(!b.Pd.Sd)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.te&&b.Pd.Vd.te)throw new L(`Cannot convert argument of type ${b.Pd.$d?b.Pd.$d.name:b.Pd.Vd.name} to parameter type ${this.name}`);c=Hb(b.Pd.Sd,b.Pd.Vd.Td,this.Td);if(this.ue){if(void 0===
b.Pd.Wd)throw new L("Passing raw pointer to smart pointer is illegal");switch(this.kf){case 0:if(b.Pd.$d===this)c=b.Pd.Wd;else throw new L(`Cannot convert argument of type ${b.Pd.$d?b.Pd.$d.name:b.Pd.Vd.name} to parameter type ${this.name}`);break;case 1:c=b.Pd.Wd;break;case 2:if(b.Pd.$d===this)c=b.Pd.Wd;else{var e=b.clone();c=this.ff(c,Lb(()=>e["delete"]()));null!==a&&a.push(this.ee,c)}break;default:throw new L("Unsupporting sharing policy");}}return c}
function Mb(a,b){if(null===b){if(this.Be)throw new L(`null is not a valid ${this.name}`);return 0}if(!b.Pd)throw new L(`Cannot pass "${Jb(b)}" as a ${this.name}`);if(!b.Pd.Sd)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Pd.Vd.te)throw new L(`Cannot convert argument of type ${b.Pd.Vd.name} to parameter type ${this.name}`);return Hb(b.Pd.Sd,b.Pd.Vd.Td,this.Td)}
function Nb(a,b,c,e,f,k,n,l,q,v,w){this.name=a;this.Td=b;this.Be=c;this.te=e;this.ue=f;this.df=k;this.kf=n;this.Je=l;this.Ce=q;this.ff=v;this.ee=w;f||void 0!==b.Yd?this.toWireType=Kb:(this.toWireType=e?Ib:Mb,this.be=null)}
var Ob=(a,b,c)=>{if(!r.hasOwnProperty(a))throw new hb("Replacing nonexistent public symbol");void 0!==r[a].Xd&&void 0!==c?r[a].Xd[c]=b:(r[a]=b,r[a].fe=c)},Pb,Qb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,r["dynCall_"+a])(b,...c)):b=Pb.get(b)(...c);return b},Rb=(a,b)=>(...c)=>Qb(a,b,c),N=(a,b)=>{a=K(a);var c=a.includes("j")?Rb(a,b):Pb.get(b);if("function"!=typeof c)throw new L(`unknown function pointer with signature ${a}: ${b}`);return c},Sb,bc=a=>{a=$b(a);var b=K(a);ac(a);return b},
cc=(a,b)=>{function c(k){f[k]||fb[k]||(gb[k]?gb[k].forEach(c):(e.push(k),f[k]=!0))}var e=[],f={};b.forEach(c);throw new Sb(`${a}: `+e.map(bc).join([", "]));};function dc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].be)return!0;return!1}
function ec(a,b,c,e,f){var k=b.length;if(2>k)throw new L("argTypes array size mismatch! Must at least get return value and 'this' types!");var n=null!==b[1]&&null!==c,l=dc(b),q="void"!==b[0].name,v=k-2,w=Array(v),z=[],D=[];return Cb(a,function(...I){D.length=0;z.length=n?2:1;z[0]=f;if(n){var P=b[1].toWireType(D,this);z[1]=P}for(var O=0;O<v;++O)w[O]=b[O+2].toWireType(D,I[O]),z.push(w[O]);I=e(...z);if(l)cb(D);else for(O=n?1:2;O<b.length;O++){var Z=1===O?P:w[O-2];null!==b[O].be&&b[O].be(Z)}P=q?b[0].fromWireType(I):
void 0;return P})}
var fc=(a,b)=>{for(var c=[],e=0;e<a;e++)c.push(H[b+4*e>>2]);return c},gc=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},hc=[],ic=[],jc=a=>{9<a&&0===--ic[a+1]&&(ic[a]=void 0,hc.push(a))},kc=a=>{if(!a)throw new L("Cannot use deleted val. handle = "+a);return ic[a]},Lb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=hc.pop()||ic.length;ic[b]=a;ic[b+1]=1;return b}},lc={name:"emscripten::val",fromWireType:a=>{var b=kc(a);jc(a);
return b},toWireType:(a,b)=>Lb(b),ae:8,readValueFromPointer:db,be:null},mc=(a,b,c)=>{switch(b){case 1:return c?function(e){return this.fromWireType(Ba[e])}:function(e){return this.fromWireType(B[e])};case 2:return c?function(e){return this.fromWireType(Ca[e>>1])}:function(e){return this.fromWireType(Da[e>>1])};case 4:return c?function(e){return this.fromWireType(E[e>>2])}:function(e){return this.fromWireType(H[e>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},nc=(a,b)=>
{var c=fb[a];if(void 0===c)throw a=`${b} has unknown type ${bc(a)}`,new L(a);return c},Jb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},oc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(J[c>>2])};case 8:return function(c){return this.fromWireType(Fa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},pc=(a,b,c)=>{switch(b){case 1:return c?e=>Ba[e]:e=>B[e];case 2:return c?e=>Ca[e>>1]:e=>Da[e>>
1];case 4:return c?e=>E[e>>2]:e=>H[e>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},qa=(a,b,c)=>{var e=B;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var n=a.charCodeAt(k);if(55296<=n&&57343>=n){var l=a.charCodeAt(++k);n=65536+((n&1023)<<10)|l&1023}if(127>=n){if(b>=c)break;e[b++]=n}else{if(2047>=n){if(b+1>=c)break;e[b++]=192|n>>6}else{if(65535>=n){if(b+2>=c)break;e[b++]=224|n>>12}else{if(b+3>=c)break;e[b++]=240|n>>18;e[b++]=128|n>>12&63}e[b++]=128|n>>6&
63}e[b++]=128|n&63}}e[b]=0;return b-f},pa=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},qc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,rc=(a,b)=>{var c=a>>1;for(var e=c+b/2;!(c>=e)&&Da[c];)++c;c<<=1;if(32<c-a&&qc)return qc.decode(B.subarray(a,c));c="";for(e=0;!(e>=b/2);++e){var f=Ca[a+2*e>>1];if(0==f)break;c+=String.fromCharCode(f)}return c},sc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var e=
b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)Ca[b>>1]=a.charCodeAt(f),b+=2;Ca[b>>1]=0;return b-e},tc=a=>2*a.length,uc=(a,b)=>{for(var c=0,e="";!(c>=b/4);){var f=E[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e},vc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var n=a.charCodeAt(++f);k=65536+((k&1023)<<10)|n&1023}E[b>>2]=k;b+=
4;if(b+4>c)break}E[b>>2]=0;return b-e},wc=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b},xc=(a,b,c)=>{var e=[];a=a.toWireType(e,c);e.length&&(H[b>>2]=Lb(e));return a},yc=[],zc={},Ac=a=>{var b=zc[a];return void 0===b?K(a):b},Bc=()=>{function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;
"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},Cc=a=>{var b=yc.length;yc.push(a);return b},Dc=(a,b)=>{for(var c=Array(a),e=0;e<a;++e)c[e]=nc(H[b+4*e>>2],"parameter "+e);return c},Ec=Reflect.construct,Q,Fc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,e)=>b.vertexAttribDivisorANGLE(c,
e),a.drawArraysInstanced=(c,e,f,k)=>b.drawArraysInstancedANGLE(c,e,f,k),a.drawElementsInstanced=(c,e,f,k,n)=>b.drawElementsInstancedANGLE(c,e,f,k,n))},Gc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Hc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,e)=>b.drawBuffersWEBGL(c,e))},Ic=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Jc=1,Kc=[],Lc=[],Mc=[],Nc=[],ja=[],Oc=[],Pc=[],oa=[],Qc=[],Rc=[],Sc=[],Tc={},Uc={},Wc=4,Xc=0,ia=a=>{for(var b=Jc++,c=a.length;c<b;c++)a[c]=null;return b},Yc=(a,b,c,e)=>{for(var f=0;f<a;f++){var k=Q[c](),n=k&&ia(e);k?(k.name=n,e[n]=k):R||=1282;E[b+4*f>>2]=n}},ka=(a,b)=>{a.Ee||(a.Ee=a.getContext,a.getContext=function(e,f){f=a.Ee(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var c=1<b.majorVersion?a.getContext("webgl2",
b):a.getContext("webgl",b);return c?Zc(c,b):0},Zc=(a,b)=>{var c=ia(oa),e={handle:c,attributes:b,version:b.majorVersion,ce:a};a.canvas&&(a.canvas.Me=e);oa[c]=e;("undefined"==typeof b.Ve||b.Ve)&&$c(e);return c},na=a=>{A=oa[a];r.lf=Q=A?.ce;return!(a&&!Q)},$c=a=>{a||=A;if(!a.cf){a.cf=!0;var b=a.ce;b.qf=b.getExtension("WEBGL_multi_draw");b.nf=b.getExtension("EXT_polygon_offset_clamp");b.mf=b.getExtension("EXT_clip_control");b.sf=b.getExtension("WEBGL_polygon_mode");Fc(b);Gc(b);Hc(b);b.Ge=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.Ie=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.de=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.de)b.de=b.getExtension("EXT_disjoint_timer_query");Ic(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},A,R,ad=(a,b)=>{Q.bindFramebuffer(a,Mc[b])},bd=a=>{Q.bindVertexArray(Pc[a])},cd=a=>Q.clear(a),dd=(a,b,c,e)=>Q.clearColor(a,b,c,e),ed=a=>Q.clearStencil(a),fd=(a,b)=>{for(var c=0;c<a;c++){var e=E[b+
4*c>>2];Q.deleteVertexArray(Pc[e]);Pc[e]=null}},gd=[],hd=(a,b)=>{Yc(a,b,"createVertexArray",Pc)};function jd(){var a=Ic(Q);return a=a.concat(a.map(b=>"GL_"+b))}
var kd=(a,b,c)=>{if(b){var e=void 0;switch(a){case 36346:e=1;break;case 36344:0!=c&&1!=c&&(R||=1280);return;case 34814:case 36345:e=0;break;case 34466:var f=Q.getParameter(34467);e=f?f.length:0;break;case 33309:if(2>A.version){R||=1282;return}e=jd().length;break;case 33307:case 33308:if(2>A.version){R||=1280;return}e=33307==a?3:0}if(void 0===e)switch(f=Q.getParameter(a),typeof f){case "number":e=f;break;case "boolean":e=f?1:0;break;case "string":R||=1280;return;case "object":if(null===f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:e=
0;break;default:R||=1280;return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(c){case 0:E[b+4*a>>2]=f[a];break;case 2:J[b+4*a>>2]=f[a];break;case 4:Ba[b+a]=f[a]?1:0}return}try{e=f.name|0}catch(k){R||=1280;xa(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${k})`);return}}break;default:R||=1280;xa(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${f} of type ${typeof f}!`);
return}switch(c){case 1:c=e;H[b>>2]=c;H[b+4>>2]=(c-H[b>>2])/4294967296;break;case 0:E[b>>2]=e;break;case 2:J[b>>2]=e;break;case 4:Ba[b]=e?1:0}}else R||=1281},ld=(a,b)=>kd(a,b,0),md=(a,b,c)=>{if(c){a=Qc[a];b=2>A.version?Q.de.getQueryObjectEXT(a,b):Q.getQueryParameter(a,b);var e;"boolean"==typeof b?e=b?1:0:e=b;H[c>>2]=e;H[c+4>>2]=(e-H[c>>2])/4294967296}else R||=1281},od=a=>{var b=pa(a)+1,c=nd(b);c&&qa(a,c,b);return c},pd=a=>{var b=Tc[a];if(!b){switch(a){case 7939:b=od(jd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
Q.getParameter(a))||(R||=1280);b=b?od(b):0;break;case 7938:b=Q.getParameter(7938);var c=`OpenGL ES 2.0 (${b})`;2<=A.version&&(c=`OpenGL ES 3.0 (${b})`);b=od(c);break;case 35724:b=Q.getParameter(35724);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=od(b);break;default:R||=1280}Tc[a]=b}return b},qd=(a,b)=>{if(2>A.version)return R||=1282,0;var c=Uc[a];if(c)return 0>b||b>=c.length?(R||=1281,0):c[b];switch(a){case 7939:return c=
jd().map(od),c=Uc[a]=c,0>b||b>=c.length?(R||=1281,0):c[b];default:return R||=1280,0}},rd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),sd=a=>{a-=5120;return 0==a?Ba:1==a?B:2==a?Ca:4==a?E:6==a?J:5==a||28922==a||28520==a||30779==a||30782==a?H:Da},td=(a,b,c,e,f)=>{a=sd(a);b=e*((Xc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Wc-1&-Wc);return a.subarray(f>>>31-Math.clz32(a.BYTES_PER_ELEMENT),f+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},V=a=>{var b=Q.Te;if(b){var c=
b.oe[a];"number"==typeof c&&(b.oe[a]=c=Q.getUniformLocation(b,b.Ke[a]+(0<c?`[${c}]`:"")));return c}R||=1282},ud=[],vd=[],wd={},yd=()=>{if(!xd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in wd)void 0===wd[b]?delete a[b]:a[b]=wd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);xd=c}return xd},xd,zd=[null,[],[]];
hb=r.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Ad=Array(256),Bd=0;256>Bd;++Bd)Ad[Bd]=String.fromCharCode(Bd);kb=Ad;L=r.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Bb.prototype,{isAliasOf:function(a){if(!(this instanceof Bb&&a instanceof Bb))return!1;var b=this.Pd.Vd.Td,c=this.Pd.Sd;a.Pd=a.Pd;var e=a.Pd.Vd.Td;for(a=a.Pd.Sd;b.Yd;)c=b.pe(c),b=b.Yd;for(;e.Yd;)a=e.pe(a),e=e.Yd;return b===e&&c===a},clone:function(){this.Pd.Sd||mb(this);if(this.Pd.ne)return this.Pd.count.value+=1,this;var a=yb,b=Object,c=b.create,e=Object.getPrototypeOf(this),f=this.Pd;a=a(c.call(b,e,{Pd:{value:{count:f.count,me:f.me,ne:f.ne,Sd:f.Sd,Vd:f.Vd,Wd:f.Wd,$d:f.$d}}}));a.Pd.count.value+=
1;a.Pd.me=!1;return a},["delete"](){this.Pd.Sd||mb(this);if(this.Pd.me&&!this.Pd.ne)throw new L("Object already scheduled for deletion");ob(this);var a=this.Pd;--a.count.value;0===a.count.value&&(a.Wd?a.$d.ee(a.Wd):a.Vd.Td.ee(a.Sd));this.Pd.ne||(this.Pd.Wd=void 0,this.Pd.Sd=void 0)},isDeleted:function(){return!this.Pd.Sd},deleteLater:function(){this.Pd.Sd||mb(this);if(this.Pd.me&&!this.Pd.ne)throw new L("Object already scheduled for deletion");Ab.push(this);this.Pd.me=!0;return this}});
Object.assign(Nb.prototype,{Ye(a){this.Je&&(a=this.Je(a));return a},Fe(a){this.ee?.(a)},ae:8,readValueFromPointer:db,fromWireType:function(a){function b(){return this.ue?zb(this.Td.je,{Vd:this.df,Sd:c,$d:this,Wd:a}):zb(this.Td.je,{Vd:this,Sd:a})}var c=this.Ye(a);if(!c)return this.Fe(a),null;var e=sb(this.Td,c);if(void 0!==e){if(0===e.Pd.count.value)return e.Pd.Sd=c,e.Pd.Wd=a,e.clone();e=e.clone();this.Fe(a);return e}e=this.Td.Xe(c);e=qb[e];if(!e)return b.call(this);e=this.te?e.Se:e.pointerType;var f=
pb(c,this.Td,e.Td);return null===f?b.call(this):this.ue?zb(e.Td.je,{Vd:e,Sd:f,$d:this,Wd:a}):zb(e.Td.je,{Vd:e,Sd:f})}});Sb=r.UnboundTypeError=((a,b)=>{var c=Cb(b,function(e){this.name=b;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
ic.push(0,1,void 0,1,null,1,!0,1,!1,1);r.count_emval_handles=()=>ic.length/2-5-hc.length;for(var Cd=0;32>Cd;++Cd)gd.push(Array(Cd));var Dd=new Float32Array(288);for(Cd=0;288>=Cd;++Cd)ud[Cd]=Dd.subarray(0,Cd);var Ed=new Int32Array(288);for(Cd=0;288>=Cd;++Cd)vd[Cd]=Ed.subarray(0,Cd);
var Rd={E:(a,b,c)=>{var e=new Va(a);H[e.Sd+16>>2]=0;H[e.Sd+4>>2]=b;H[e.Sd+8>>2]=c;Wa=a;Xa++;throw Wa;},T:function(){return 0},rd:()=>{},qd:function(){return 0},pd:()=>{},od:function(){},nd:()=>{},jd:()=>{Oa("")},y:a=>{var b=bb[a];delete bb[a];var c=b.Ce,e=b.ee,f=b.He,k=f.map(n=>n.af).concat(f.map(n=>n.hf));jb([a],k,n=>{var l={};f.forEach((q,v)=>{var w=n[v],z=q.Ze,D=q.$e,I=n[v+f.length],P=q.gf,O=q.jf;l[q.We]={read:Z=>w.fromWireType(z(D,Z)),write:(Z,la)=>{var X=[];P(O,Z,I.toWireType(X,la));cb(X)}}});
return[{name:b.name,fromWireType:q=>{var v={},w;for(w in l)v[w]=l[w].read(q);e(q);return v},toWireType:(q,v)=>{for(var w in l)if(!(w in v))throw new TypeError(`Missing field: "${w}"`);var z=c();for(w in l)l[w].write(z,v[w]);null!==q&&q.push(e,z);return z},ae:8,readValueFromPointer:db,be:e}]})},W:()=>{},id:(a,b,c,e)=>{b=K(b);ib(a,{name:b,fromWireType:function(f){return!!f},toWireType:function(f,k){return k?c:e},ae:8,readValueFromPointer:function(f){return this.fromWireType(B[f])},be:null})},j:(a,b,
c,e,f,k,n,l,q,v,w,z,D)=>{w=K(w);k=N(f,k);l&&=N(n,l);v&&=N(q,v);D=N(z,D);var I=Fb(w);Eb(I,function(){cc(`Cannot construct ${w} due to unbound types`,[e])});jb([a,b,c],e?[e]:[],P=>{P=P[0];if(e){var O=P.Td;var Z=O.je}else Z=Bb.prototype;P=Cb(w,function(...Ea){if(Object.getPrototypeOf(this)!==la)throw new L("Use 'new' to construct "+w);if(void 0===X.ge)throw new L(w+" has no accessible constructor");var aa=X.ge[Ea.length];if(void 0===aa)throw new L(`Tried to invoke ctor of ${w} with invalid number of parameters (${Ea.length}) - expected (${Object.keys(X.ge).toString()}) parameters instead!`);
return aa.apply(this,Ea)});var la=Object.create(Z,{constructor:{value:P}});P.prototype=la;var X=new Gb(w,P,la,D,O,k,l,v);if(X.Yd){var da;(da=X.Yd).qe??(da.qe=[]);X.Yd.qe.push(X)}O=new Nb(w,X,!0,!1,!1);da=new Nb(w+"*",X,!1,!1,!1);Z=new Nb(w+" const*",X,!1,!0,!1);qb[a]={pointerType:da,Se:Z};Ob(I,P);return[O,da,Z]})},e:(a,b,c,e,f,k,n)=>{var l=fc(c,e);b=K(b);b=gc(b);k=N(f,k);jb([],[a],q=>{function v(){cc(`Cannot call ${w} due to unbound types`,l)}q=q[0];var w=`${q.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
var z=q.Td.constructor;void 0===z[b]?(v.fe=c-1,z[b]=v):(Db(z,b,w),z[b].Xd[c-1]=v);jb([],l,D=>{D=[D[0],null].concat(D.slice(1));D=ec(w,D,null,k,n);void 0===z[b].Xd?(D.fe=c-1,z[b]=D):z[b].Xd[c-1]=D;if(q.Td.qe)for(const I of q.Td.qe)I.constructor.hasOwnProperty(b)||(I.constructor[b]=D);return[]});return[]})},s:(a,b,c,e,f,k)=>{var n=fc(b,c);f=N(e,f);jb([],[a],l=>{l=l[0];var q=`constructor ${l.name}`;void 0===l.Td.ge&&(l.Td.ge=[]);if(void 0!==l.Td.ge[b-1])throw new L(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${l.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);l.Td.ge[b-1]=()=>{cc(`Cannot construct ${l.name} due to unbound types`,n)};jb([],n,v=>{v.splice(1,0,null);l.Td.ge[b-1]=ec(q,v,null,f,k);return[]});return[]})},a:(a,b,c,e,f,k,n,l)=>{var q=fc(c,e);b=K(b);b=gc(b);k=N(f,k);jb([],[a],v=>{function w(){cc(`Cannot call ${z} due to unbound types`,q)}v=v[0];var z=`${v.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&v.Td.ef.push(b);
var D=v.Td.je,I=D[b];void 0===I||void 0===I.Xd&&I.className!==v.name&&I.fe===c-2?(w.fe=c-2,w.className=v.name,D[b]=w):(Db(D,b,z),D[b].Xd[c-2]=w);jb([],q,P=>{P=ec(z,P,v,k,n);void 0===D[b].Xd?(P.fe=c-2,D[b]=P):D[b].Xd[c-2]=P;return[]});return[]})},o:(a,b,c)=>{a=K(a);jb([],[b],e=>{e=e[0];r[a]=e.fromWireType(c);return[]})},hd:a=>ib(a,lc),i:(a,b,c,e)=>{function f(){}b=K(b);f.values={};ib(a,{name:b,constructor:f,fromWireType:function(k){return this.constructor.values[k]},toWireType:(k,n)=>n.value,ae:8,
readValueFromPointer:mc(b,c,e),be:null});Eb(b,f)},b:(a,b,c)=>{var e=nc(a,"enum");b=K(b);a=e.constructor;e=Object.create(e.constructor.prototype,{value:{value:c},constructor:{value:Cb(`${e.name}_${b}`,function(){})}});a.values[c]=e;a[b]=e},Q:(a,b,c)=>{b=K(b);ib(a,{name:b,fromWireType:e=>e,toWireType:(e,f)=>f,ae:8,readValueFromPointer:oc(b,c),be:null})},q:(a,b,c,e,f,k)=>{var n=fc(b,c);a=K(a);a=gc(a);f=N(e,f);Eb(a,function(){cc(`Cannot call ${a} due to unbound types`,n)},b-1);jb([],n,l=>{l=[l[0],null].concat(l.slice(1));
Ob(a,ec(a,l,null,f,k),b-1);return[]})},z:(a,b,c,e,f)=>{b=K(b);-1===f&&(f=4294967295);f=l=>l;if(0===e){var k=32-8*c;f=l=>l<<k>>>k}var n=b.includes("unsigned")?function(l,q){return q>>>0}:function(l,q){return q};ib(a,{name:b,fromWireType:f,toWireType:n,ae:8,readValueFromPointer:pc(b,c,0!==e),be:null})},n:(a,b,c)=>{function e(k){return new f(Ba.buffer,H[k+4>>2],H[k>>2])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=K(c);ib(a,{name:c,fromWireType:e,
ae:8,readValueFromPointer:e},{bf:!0})},m:(a,b,c,e,f,k,n,l,q,v,w,z)=>{c=K(c);k=N(f,k);l=N(n,l);v=N(q,v);z=N(w,z);jb([a],[b],D=>{D=D[0];return[new Nb(c,D.Td,!1,!1,!0,D,e,k,l,v,z)]})},P:(a,b)=>{b=K(b);var c="std::string"===b;ib(a,{name:b,fromWireType:function(e){var f=H[e>>2],k=e+4;if(c)for(var n=k,l=0;l<=f;++l){var q=k+l;if(l==f||0==B[q]){n=n?Za(B,n,q-n):"";if(void 0===v)var v=n;else v+=String.fromCharCode(0),v+=n;n=q+1}}else{v=Array(f);for(l=0;l<f;++l)v[l]=String.fromCharCode(B[k+l]);v=v.join("")}ac(e);
return v},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var k="string"==typeof f;if(!(k||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array))throw new L("Cannot pass non-string to std::string");var n=c&&k?pa(f):f.length;var l=nd(4+n+1),q=l+4;H[l>>2]=n;if(c&&k)qa(f,q,n+1);else if(k)for(k=0;k<n;++k){var v=f.charCodeAt(k);if(255<v)throw ac(q),new L("String has UTF-16 code units that do not fit in 8 bits");B[q+k]=v}else for(k=0;k<n;++k)B[q+k]=f[k];
null!==e&&e.push(ac,l);return l},ae:8,readValueFromPointer:db,be(e){ac(e)}})},L:(a,b,c)=>{c=K(c);if(2===b){var e=rc;var f=sc;var k=tc;var n=l=>Da[l>>1]}else 4===b&&(e=uc,f=vc,k=wc,n=l=>H[l>>2]);ib(a,{name:c,fromWireType:l=>{for(var q=H[l>>2],v,w=l+4,z=0;z<=q;++z){var D=l+4+z*b;if(z==q||0==n(D))w=e(w,D-w),void 0===v?v=w:(v+=String.fromCharCode(0),v+=w),w=D+b}ac(l);return v},toWireType:(l,q)=>{if("string"!=typeof q)throw new L(`Cannot pass non-string to C++ string type ${c}`);var v=k(q),w=nd(4+v+b);
H[w>>2]=v/b;f(q,w+4,v+b);null!==l&&l.push(ac,w);return w},ae:8,readValueFromPointer:db,be(l){ac(l)}})},x:(a,b,c,e,f,k)=>{bb[a]={name:K(b),Ce:N(c,e),ee:N(f,k),He:[]}},d:(a,b,c,e,f,k,n,l,q,v)=>{bb[a].He.push({We:K(b),af:c,Ze:N(e,f),$e:k,hf:n,gf:N(l,q),jf:v})},gd:(a,b)=>{b=K(b);ib(a,{pf:!0,name:b,ae:0,fromWireType:()=>{},toWireType:()=>{}})},fd:()=>1,ed:()=>{throw Infinity;},D:(a,b,c)=>{a=kc(a);b=nc(b,"emval::as");return xc(b,c,a)},K:(a,b,c,e)=>{a=yc[a];b=kc(b);return a(null,b,c,e)},p:(a,b,c,e,f)=>{a=
yc[a];b=kc(b);c=Ac(c);return a(b,b[c],e,f)},c:jc,J:a=>{if(0===a)return Lb(Bc());a=Ac(a);return Lb(Bc()[a])},l:(a,b,c)=>{var e=Dc(a,b),f=e.shift();a--;var k=Array(a);b=`methodCaller<(${e.map(n=>n.name).join(", ")}) => ${f.name}>`;return Cc(Cb(b,(n,l,q,v)=>{for(var w=0,z=0;z<a;++z)k[z]=e[z].readValueFromPointer(v+w),w+=e[z].ae;n=1===c?Ec(l,k):l.apply(n,k);return xc(f,q,n)}))},t:(a,b)=>{a=kc(a);b=kc(b);return Lb(a[b])},H:a=>{9<a&&(ic[a+1]+=1)},G:()=>Lb([]),f:a=>Lb(Ac(a)),C:()=>Lb({}),dd:a=>{a=kc(a);
return!a},k:a=>{var b=kc(a);cb(b);jc(a)},h:(a,b,c)=>{a=kc(a);b=kc(b);c=kc(c);a[b]=c},g:(a,b)=>{a=nc(a,"_emval_take_value");a=a.readValueFromPointer(b);return Lb(a)},V:function(){return-52},U:function(){},cd:(a,b,c,e)=>{var f=(new Date).getFullYear(),k=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();H[a>>2]=60*Math.max(k,f);E[b>>2]=Number(k!=f);b=n=>{var l=Math.abs(n);return`UTC${0<=n?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};
a=b(k);b=b(f);f<k?(qa(a,c,17),qa(b,e,17)):(qa(a,e,17),qa(b,c,17))},bd:()=>performance.now(),ad:a=>Q.activeTexture(a),$c:(a,b)=>{Q.attachShader(Lc[a],Oc[b])},_c:(a,b)=>{Q.beginQuery(a,Qc[b])},Zc:(a,b)=>{Q.de.beginQueryEXT(a,Qc[b])},Yc:(a,b,c)=>{Q.bindAttribLocation(Lc[a],b,c?Za(B,c):"")},Xc:(a,b)=>{35051==a?Q.ze=b:35052==a&&(Q.ie=b);Q.bindBuffer(a,Kc[b])},Wc:ad,Vc:(a,b)=>{Q.bindRenderbuffer(a,Nc[b])},Uc:(a,b)=>{Q.bindSampler(a,Rc[b])},Tc:(a,b)=>{Q.bindTexture(a,ja[b])},Sc:bd,Rc:bd,Qc:(a,b,c,e)=>Q.blendColor(a,
b,c,e),Pc:a=>Q.blendEquation(a),Oc:(a,b)=>Q.blendFunc(a,b),Nc:(a,b,c,e,f,k,n,l,q,v)=>Q.blitFramebuffer(a,b,c,e,f,k,n,l,q,v),Mc:(a,b,c,e)=>{2<=A.version?c&&b?Q.bufferData(a,B,e,c,b):Q.bufferData(a,b,e):Q.bufferData(a,c?B.subarray(c,c+b):b,e)},Lc:(a,b,c,e)=>{2<=A.version?c&&Q.bufferSubData(a,b,B,e,c):Q.bufferSubData(a,b,B.subarray(e,e+c))},Kc:a=>Q.checkFramebufferStatus(a),Jc:cd,Ic:dd,Hc:ed,Gc:(a,b,c,e)=>Q.clientWaitSync(Sc[a],b,(c>>>0)+4294967296*e),Fc:(a,b,c,e)=>{Q.colorMask(!!a,!!b,!!c,!!e)},Ec:a=>
{Q.compileShader(Oc[a])},Dc:(a,b,c,e,f,k,n,l)=>{2<=A.version?Q.ie||!n?Q.compressedTexImage2D(a,b,c,e,f,k,n,l):Q.compressedTexImage2D(a,b,c,e,f,k,B,l,n):Q.compressedTexImage2D(a,b,c,e,f,k,B.subarray(l,l+n))},Cc:(a,b,c,e,f,k,n,l,q)=>{2<=A.version?Q.ie||!l?Q.compressedTexSubImage2D(a,b,c,e,f,k,n,l,q):Q.compressedTexSubImage2D(a,b,c,e,f,k,n,B,q,l):Q.compressedTexSubImage2D(a,b,c,e,f,k,n,B.subarray(q,q+l))},Bc:(a,b,c,e,f)=>Q.copyBufferSubData(a,b,c,e,f),Ac:(a,b,c,e,f,k,n,l)=>Q.copyTexSubImage2D(a,b,c,
e,f,k,n,l),zc:()=>{var a=ia(Lc),b=Q.createProgram();b.name=a;b.xe=b.ve=b.we=0;b.De=1;Lc[a]=b;return a},yc:a=>{var b=ia(Oc);Oc[b]=Q.createShader(a);return b},xc:a=>Q.cullFace(a),wc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Kc[e];f&&(Q.deleteBuffer(f),f.name=0,Kc[e]=null,e==Q.ze&&(Q.ze=0),e==Q.ie&&(Q.ie=0))}},vc:(a,b)=>{for(var c=0;c<a;++c){var e=E[b+4*c>>2],f=Mc[e];f&&(Q.deleteFramebuffer(f),f.name=0,Mc[e]=null)}},uc:a=>{if(a){var b=Lc[a];b?(Q.deleteProgram(b),b.name=0,Lc[a]=null):R||=1281}},
tc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Qc[e];f&&(Q.deleteQuery(f),Qc[e]=null)}},sc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Qc[e];f&&(Q.de.deleteQueryEXT(f),Qc[e]=null)}},rc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Nc[e];f&&(Q.deleteRenderbuffer(f),f.name=0,Nc[e]=null)}},qc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=Rc[e];f&&(Q.deleteSampler(f),f.name=0,Rc[e]=null)}},pc:a=>{if(a){var b=Oc[a];b?(Q.deleteShader(b),Oc[a]=null):R||=1281}},oc:a=>{if(a){var b=Sc[a];b?
(Q.deleteSync(b),b.name=0,Sc[a]=null):R||=1281}},nc:(a,b)=>{for(var c=0;c<a;c++){var e=E[b+4*c>>2],f=ja[e];f&&(Q.deleteTexture(f),f.name=0,ja[e]=null)}},mc:fd,lc:fd,kc:a=>{Q.depthMask(!!a)},jc:a=>Q.disable(a),ic:a=>{Q.disableVertexAttribArray(a)},hc:(a,b,c)=>{Q.drawArrays(a,b,c)},gc:(a,b,c,e)=>{Q.drawArraysInstanced(a,b,c,e)},fc:(a,b,c,e,f)=>{Q.Ge.drawArraysInstancedBaseInstanceWEBGL(a,b,c,e,f)},ec:(a,b)=>{for(var c=gd[a],e=0;e<a;e++)c[e]=E[b+4*e>>2];Q.drawBuffers(c)},dc:(a,b,c,e)=>{Q.drawElements(a,
b,c,e)},cc:(a,b,c,e,f)=>{Q.drawElementsInstanced(a,b,c,e,f)},bc:(a,b,c,e,f,k,n)=>{Q.Ge.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,e,f,k,n)},ac:(a,b,c,e,f,k)=>{Q.drawElements(a,e,f,k)},$b:a=>Q.enable(a),_b:a=>{Q.enableVertexAttribArray(a)},Zb:a=>Q.endQuery(a),Yb:a=>{Q.de.endQueryEXT(a)},Xb:(a,b)=>(a=Q.fenceSync(a,b))?(b=ia(Sc),a.name=b,Sc[b]=a,b):0,Wb:()=>Q.finish(),Vb:()=>Q.flush(),Ub:(a,b,c,e)=>{Q.framebufferRenderbuffer(a,b,c,Nc[e])},Tb:(a,b,c,e,f)=>{Q.framebufferTexture2D(a,b,c,ja[e],
f)},Sb:a=>Q.frontFace(a),Rb:(a,b)=>{Yc(a,b,"createBuffer",Kc)},Qb:(a,b)=>{Yc(a,b,"createFramebuffer",Mc)},Pb:(a,b)=>{Yc(a,b,"createQuery",Qc)},Ob:(a,b)=>{for(var c=0;c<a;c++){var e=Q.de.createQueryEXT();if(!e){for(R||=1282;c<a;)E[b+4*c++>>2]=0;break}var f=ia(Qc);e.name=f;Qc[f]=e;E[b+4*c>>2]=f}},Nb:(a,b)=>{Yc(a,b,"createRenderbuffer",Nc)},Mb:(a,b)=>{Yc(a,b,"createSampler",Rc)},Lb:(a,b)=>{Yc(a,b,"createTexture",ja)},Kb:hd,Jb:hd,Ib:a=>Q.generateMipmap(a),Hb:(a,b,c)=>{c?E[c>>2]=Q.getBufferParameter(a,
b):R||=1281},Gb:()=>{var a=Q.getError()||R;R=0;return a},Fb:(a,b)=>kd(a,b,2),Eb:(a,b,c,e)=>{a=Q.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;E[e>>2]=a},Db:ld,Cb:(a,b,c,e)=>{a=Q.getProgramInfoLog(Lc[a]);null===a&&(a="(unknown error)");b=0<b&&e?qa(a,e,b):0;c&&(E[c>>2]=b)},Bb:(a,b,c)=>{if(c)if(a>=Jc)R||=1281;else if(a=Lc[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.xe){var e=
Q.getProgramParameter(a,35718);for(b=0;b<e;++b)a.xe=Math.max(a.xe,Q.getActiveUniform(a,b).name.length+1)}E[c>>2]=a.xe}else if(35722==b){if(!a.ve)for(e=Q.getProgramParameter(a,35721),b=0;b<e;++b)a.ve=Math.max(a.ve,Q.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.ve}else if(35381==b){if(!a.we)for(e=Q.getProgramParameter(a,35382),b=0;b<e;++b)a.we=Math.max(a.we,Q.getActiveUniformBlockName(a,b).length+1);E[c>>2]=a.we}else E[c>>2]=Q.getProgramParameter(a,b);else R||=1281},Ab:md,zb:md,yb:(a,b,c)=>{if(c){a=
Q.getQueryParameter(Qc[a],b);var e;"boolean"==typeof a?e=a?1:0:e=a;E[c>>2]=e}else R||=1281},xb:(a,b,c)=>{if(c){a=Q.de.getQueryObjectEXT(Qc[a],b);var e;"boolean"==typeof a?e=a?1:0:e=a;E[c>>2]=e}else R||=1281},wb:(a,b,c)=>{c?E[c>>2]=Q.getQuery(a,b):R||=1281},vb:(a,b,c)=>{c?E[c>>2]=Q.de.getQueryEXT(a,b):R||=1281},ub:(a,b,c)=>{c?E[c>>2]=Q.getRenderbufferParameter(a,b):R||=1281},tb:(a,b,c,e)=>{a=Q.getShaderInfoLog(Oc[a]);null===a&&(a="(unknown error)");b=0<b&&e?qa(a,e,b):0;c&&(E[c>>2]=b)},sb:(a,b,c,e)=>
{a=Q.getShaderPrecisionFormat(a,b);E[c>>2]=a.rangeMin;E[c+4>>2]=a.rangeMax;E[e>>2]=a.precision},rb:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(Oc[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(Oc[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=Q.getShaderParameter(Oc[a],b):R||=1281},qb:pd,pb:qd,ob:(a,b)=>{b=b?Za(B,b):"";if(a=Lc[a]){var c=a,e=c.oe,f=c.Le,k;if(!e){c.oe=e={};c.Ke={};var n=Q.getProgramParameter(c,35718);for(k=0;k<n;++k){var l=Q.getActiveUniform(c,k);var q=
l.name;l=l.size;var v=rd(q);v=0<v?q.slice(0,v):q;var w=c.De;c.De+=l;f[v]=[l,w];for(q=0;q<l;++q)e[w]=q,c.Ke[w++]=v}}c=a.oe;e=0;f=b;k=rd(b);0<k&&(e=parseInt(b.slice(k+1))>>>0,f=b.slice(0,k));if((f=a.Le[f])&&e<f[0]&&(e+=f[1],c[e]=c[e]||Q.getUniformLocation(a,b)))return e}else R||=1281;return-1},nb:(a,b,c)=>{for(var e=gd[b],f=0;f<b;f++)e[f]=E[c+4*f>>2];Q.invalidateFramebuffer(a,e)},mb:(a,b,c,e,f,k,n)=>{for(var l=gd[b],q=0;q<b;q++)l[q]=E[c+4*q>>2];Q.invalidateSubFramebuffer(a,l,e,f,k,n)},lb:a=>Q.isSync(Sc[a]),
kb:a=>(a=ja[a])?Q.isTexture(a):0,jb:a=>Q.lineWidth(a),ib:a=>{a=Lc[a];Q.linkProgram(a);a.oe=0;a.Le={}},hb:(a,b,c,e,f,k)=>{Q.Ie.multiDrawArraysInstancedBaseInstanceWEBGL(a,E,b>>2,E,c>>2,E,e>>2,H,f>>2,k)},gb:(a,b,c,e,f,k,n,l)=>{Q.Ie.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,E,b>>2,c,E,e>>2,E,f>>2,E,k>>2,H,n>>2,l)},fb:(a,b)=>{3317==a?Wc=b:3314==a&&(Xc=b);Q.pixelStorei(a,b)},eb:(a,b)=>{Q.de.queryCounterEXT(Qc[a],b)},db:a=>Q.readBuffer(a),cb:(a,b,c,e,f,k,n)=>{if(2<=A.version)if(Q.ze)Q.readPixels(a,
b,c,e,f,k,n);else{var l=sd(k);n>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);Q.readPixels(a,b,c,e,f,k,l,n)}else(l=td(k,f,c,e,n))?Q.readPixels(a,b,c,e,f,k,l):R||=1280},bb:(a,b,c,e)=>Q.renderbufferStorage(a,b,c,e),ab:(a,b,c,e,f)=>Q.renderbufferStorageMultisample(a,b,c,e,f),$a:(a,b,c)=>{Q.samplerParameterf(Rc[a],b,c)},_a:(a,b,c)=>{Q.samplerParameteri(Rc[a],b,c)},Za:(a,b,c)=>{Q.samplerParameteri(Rc[a],b,E[c>>2])},Ya:(a,b,c,e)=>Q.scissor(a,b,c,e),Xa:(a,b,c,e)=>{for(var f="",k=0;k<b;++k){var n=(n=H[c+4*k>>2])?
Za(B,n,e?H[e+4*k>>2]:void 0):"";f+=n}Q.shaderSource(Oc[a],f)},Wa:(a,b,c)=>Q.stencilFunc(a,b,c),Va:(a,b,c,e)=>Q.stencilFuncSeparate(a,b,c,e),Ua:a=>Q.stencilMask(a),Ta:(a,b)=>Q.stencilMaskSeparate(a,b),Sa:(a,b,c)=>Q.stencilOp(a,b,c),Ra:(a,b,c,e)=>Q.stencilOpSeparate(a,b,c,e),Qa:(a,b,c,e,f,k,n,l,q)=>{if(2<=A.version){if(Q.ie){Q.texImage2D(a,b,c,e,f,k,n,l,q);return}if(q){var v=sd(l);q>>>=31-Math.clz32(v.BYTES_PER_ELEMENT);Q.texImage2D(a,b,c,e,f,k,n,l,v,q);return}}v=q?td(l,n,e,f,q):null;Q.texImage2D(a,
b,c,e,f,k,n,l,v)},Pa:(a,b,c)=>Q.texParameterf(a,b,c),Oa:(a,b,c)=>{Q.texParameterf(a,b,J[c>>2])},Na:(a,b,c)=>Q.texParameteri(a,b,c),Ma:(a,b,c)=>{Q.texParameteri(a,b,E[c>>2])},La:(a,b,c,e,f)=>Q.texStorage2D(a,b,c,e,f),Ka:(a,b,c,e,f,k,n,l,q)=>{if(2<=A.version){if(Q.ie){Q.texSubImage2D(a,b,c,e,f,k,n,l,q);return}if(q){var v=sd(l);Q.texSubImage2D(a,b,c,e,f,k,n,l,v,q>>>31-Math.clz32(v.BYTES_PER_ELEMENT));return}}q=q?td(l,n,f,k,q):null;Q.texSubImage2D(a,b,c,e,f,k,n,l,q)},Ja:(a,b)=>{Q.uniform1f(V(a),b)},Ia:(a,
b,c)=>{if(2<=A.version)b&&Q.uniform1fv(V(a),J,c>>2,b);else{if(288>=b)for(var e=ud[b],f=0;f<b;++f)e[f]=J[c+4*f>>2];else e=J.subarray(c>>2,c+4*b>>2);Q.uniform1fv(V(a),e)}},Ha:(a,b)=>{Q.uniform1i(V(a),b)},Ga:(a,b,c)=>{if(2<=A.version)b&&Q.uniform1iv(V(a),E,c>>2,b);else{if(288>=b)for(var e=vd[b],f=0;f<b;++f)e[f]=E[c+4*f>>2];else e=E.subarray(c>>2,c+4*b>>2);Q.uniform1iv(V(a),e)}},Fa:(a,b,c)=>{Q.uniform2f(V(a),b,c)},Ea:(a,b,c)=>{if(2<=A.version)b&&Q.uniform2fv(V(a),J,c>>2,2*b);else{if(144>=b){b*=2;for(var e=
ud[b],f=0;f<b;f+=2)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2]}else e=J.subarray(c>>2,c+8*b>>2);Q.uniform2fv(V(a),e)}},Da:(a,b,c)=>{Q.uniform2i(V(a),b,c)},Ca:(a,b,c)=>{if(2<=A.version)b&&Q.uniform2iv(V(a),E,c>>2,2*b);else{if(144>=b){b*=2;for(var e=vd[b],f=0;f<b;f+=2)e[f]=E[c+4*f>>2],e[f+1]=E[c+(4*f+4)>>2]}else e=E.subarray(c>>2,c+8*b>>2);Q.uniform2iv(V(a),e)}},Ba:(a,b,c,e)=>{Q.uniform3f(V(a),b,c,e)},Aa:(a,b,c)=>{if(2<=A.version)b&&Q.uniform3fv(V(a),J,c>>2,3*b);else{if(96>=b){b*=3;for(var e=ud[b],f=0;f<
b;f+=3)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2],e[f+2]=J[c+(4*f+8)>>2]}else e=J.subarray(c>>2,c+12*b>>2);Q.uniform3fv(V(a),e)}},za:(a,b,c,e)=>{Q.uniform3i(V(a),b,c,e)},ya:(a,b,c)=>{if(2<=A.version)b&&Q.uniform3iv(V(a),E,c>>2,3*b);else{if(96>=b){b*=3;for(var e=vd[b],f=0;f<b;f+=3)e[f]=E[c+4*f>>2],e[f+1]=E[c+(4*f+4)>>2],e[f+2]=E[c+(4*f+8)>>2]}else e=E.subarray(c>>2,c+12*b>>2);Q.uniform3iv(V(a),e)}},xa:(a,b,c,e,f)=>{Q.uniform4f(V(a),b,c,e,f)},wa:(a,b,c)=>{if(2<=A.version)b&&Q.uniform4fv(V(a),J,c>>2,4*
b);else{if(72>=b){var e=ud[4*b],f=J;c>>=2;b*=4;for(var k=0;k<b;k+=4){var n=c+k;e[k]=f[n];e[k+1]=f[n+1];e[k+2]=f[n+2];e[k+3]=f[n+3]}}else e=J.subarray(c>>2,c+16*b>>2);Q.uniform4fv(V(a),e)}},va:(a,b,c,e,f)=>{Q.uniform4i(V(a),b,c,e,f)},ua:(a,b,c)=>{if(2<=A.version)b&&Q.uniform4iv(V(a),E,c>>2,4*b);else{if(72>=b){b*=4;for(var e=vd[b],f=0;f<b;f+=4)e[f]=E[c+4*f>>2],e[f+1]=E[c+(4*f+4)>>2],e[f+2]=E[c+(4*f+8)>>2],e[f+3]=E[c+(4*f+12)>>2]}else e=E.subarray(c>>2,c+16*b>>2);Q.uniform4iv(V(a),e)}},ta:(a,b,c,e)=>
{if(2<=A.version)b&&Q.uniformMatrix2fv(V(a),!!c,J,e>>2,4*b);else{if(72>=b){b*=4;for(var f=ud[b],k=0;k<b;k+=4)f[k]=J[e+4*k>>2],f[k+1]=J[e+(4*k+4)>>2],f[k+2]=J[e+(4*k+8)>>2],f[k+3]=J[e+(4*k+12)>>2]}else f=J.subarray(e>>2,e+16*b>>2);Q.uniformMatrix2fv(V(a),!!c,f)}},sa:(a,b,c,e)=>{if(2<=A.version)b&&Q.uniformMatrix3fv(V(a),!!c,J,e>>2,9*b);else{if(32>=b){b*=9;for(var f=ud[b],k=0;k<b;k+=9)f[k]=J[e+4*k>>2],f[k+1]=J[e+(4*k+4)>>2],f[k+2]=J[e+(4*k+8)>>2],f[k+3]=J[e+(4*k+12)>>2],f[k+4]=J[e+(4*k+16)>>2],f[k+
5]=J[e+(4*k+20)>>2],f[k+6]=J[e+(4*k+24)>>2],f[k+7]=J[e+(4*k+28)>>2],f[k+8]=J[e+(4*k+32)>>2]}else f=J.subarray(e>>2,e+36*b>>2);Q.uniformMatrix3fv(V(a),!!c,f)}},ra:(a,b,c,e)=>{if(2<=A.version)b&&Q.uniformMatrix4fv(V(a),!!c,J,e>>2,16*b);else{if(18>=b){var f=ud[16*b],k=J;e>>=2;b*=16;for(var n=0;n<b;n+=16){var l=e+n;f[n]=k[l];f[n+1]=k[l+1];f[n+2]=k[l+2];f[n+3]=k[l+3];f[n+4]=k[l+4];f[n+5]=k[l+5];f[n+6]=k[l+6];f[n+7]=k[l+7];f[n+8]=k[l+8];f[n+9]=k[l+9];f[n+10]=k[l+10];f[n+11]=k[l+11];f[n+12]=k[l+12];f[n+
13]=k[l+13];f[n+14]=k[l+14];f[n+15]=k[l+15]}}else f=J.subarray(e>>2,e+64*b>>2);Q.uniformMatrix4fv(V(a),!!c,f)}},qa:a=>{a=Lc[a];Q.useProgram(a);Q.Te=a},pa:(a,b)=>Q.vertexAttrib1f(a,b),oa:(a,b)=>{Q.vertexAttrib2f(a,J[b>>2],J[b+4>>2])},na:(a,b)=>{Q.vertexAttrib3f(a,J[b>>2],J[b+4>>2],J[b+8>>2])},ma:(a,b)=>{Q.vertexAttrib4f(a,J[b>>2],J[b+4>>2],J[b+8>>2],J[b+12>>2])},la:(a,b)=>{Q.vertexAttribDivisor(a,b)},ka:(a,b,c,e,f)=>{Q.vertexAttribIPointer(a,b,c,e,f)},ja:(a,b,c,e,f,k)=>{Q.vertexAttribPointer(a,b,c,
!!e,f,k)},ia:(a,b,c,e)=>Q.viewport(a,b,c,e),ha:(a,b,c,e)=>{Q.waitSync(Sc[a],b,(c>>>0)+4294967296*e)},ga:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+1/c);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-ya.buffer.byteLength+65535)/65536|0;try{ya.grow(e);Ga();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},fa:()=>A?A.handle:0,md:(a,b)=>{var c=0;yd().forEach((e,f)=>{var k=b+c;f=H[a+4*f>>2]=k;for(k=0;k<e.length;++k)Ba[f++]=
e.charCodeAt(k);Ba[f]=0;c+=e.length+1});return 0},ld:(a,b)=>{var c=yd();H[a>>2]=c.length;var e=0;c.forEach(f=>e+=f.length+1);H[b>>2]=e;return 0},S:()=>52,Y:function(){return 52},kd:()=>52,X:function(){return 70},R:(a,b,c,e)=>{for(var f=0,k=0;k<c;k++){var n=H[b>>2],l=H[b+4>>2];b+=8;for(var q=0;q<l;q++){var v=B[n+q],w=zd[a];0===v||10===v?((1===a?va:xa)(Za(w)),w.length=0):w.push(v)}f+=l}H[e>>2]=f;return 0},ea:ad,da:cd,ca:dd,ba:ed,I:ld,O:pd,aa:qd,w:Fd,F:Gd,v:Hd,N:Id,$:Jd,M:Kd,u:Ld,r:Md,B:Nd,A:Od,_:Pd,
Z:Qd},Y=function(){function a(c){Y=c.exports;ya=Y.sd;Ga();Pb=Y.vd;Ia.unshift(Y.td);Ka--;0==Ka&&(null!==La&&(clearInterval(La),La=null),Na&&(c=Na,Na=null,c()));return Y}var b={a:Rd};Ka++;if(r.instantiateWasm)try{return r.instantiateWasm(b,a)}catch(c){xa(`Module.instantiateWasm callback failed with error: ${c}`),ca(c)}Qa??=r.locateFile?Pa("canvaskit.wasm")?"canvaskit.wasm":sa+"canvaskit.wasm":(new URL("canvaskit.wasm",import.meta.url)).href;Ta(b,function(c){a(c.instance)}).catch(ca);return{}}(),
$b=a=>($b=Y.ud)(a),nd=r._malloc=a=>(nd=r._malloc=Y.wd)(a),ac=r._free=a=>(ac=r._free=Y.xd)(a),Sd=(a,b)=>(Sd=Y.yd)(a,b),Td=a=>(Td=Y.zd)(a),Ud=()=>(Ud=Y.Ad)();r.dynCall_viji=(a,b,c,e,f)=>(r.dynCall_viji=Y.Bd)(a,b,c,e,f);r.dynCall_vijiii=(a,b,c,e,f,k,n)=>(r.dynCall_vijiii=Y.Cd)(a,b,c,e,f,k,n);r.dynCall_viiiiij=(a,b,c,e,f,k,n,l)=>(r.dynCall_viiiiij=Y.Dd)(a,b,c,e,f,k,n,l);r.dynCall_vij=(a,b,c,e)=>(r.dynCall_vij=Y.Ed)(a,b,c,e);r.dynCall_jii=(a,b,c)=>(r.dynCall_jii=Y.Fd)(a,b,c);
r.dynCall_jiiiiii=(a,b,c,e,f,k,n)=>(r.dynCall_jiiiiii=Y.Gd)(a,b,c,e,f,k,n);r.dynCall_jiiiiji=(a,b,c,e,f,k,n,l)=>(r.dynCall_jiiiiji=Y.Hd)(a,b,c,e,f,k,n,l);r.dynCall_ji=(a,b)=>(r.dynCall_ji=Y.Id)(a,b);r.dynCall_iijj=(a,b,c,e,f,k)=>(r.dynCall_iijj=Y.Jd)(a,b,c,e,f,k);r.dynCall_jiji=(a,b,c,e,f)=>(r.dynCall_jiji=Y.Kd)(a,b,c,e,f);r.dynCall_viijii=(a,b,c,e,f,k,n)=>(r.dynCall_viijii=Y.Ld)(a,b,c,e,f,k,n);r.dynCall_iiiiij=(a,b,c,e,f,k,n)=>(r.dynCall_iiiiij=Y.Md)(a,b,c,e,f,k,n);
r.dynCall_iiiiijj=(a,b,c,e,f,k,n,l,q)=>(r.dynCall_iiiiijj=Y.Nd)(a,b,c,e,f,k,n,l,q);r.dynCall_iiiiiijj=(a,b,c,e,f,k,n,l,q,v)=>(r.dynCall_iiiiiijj=Y.Od)(a,b,c,e,f,k,n,l,q,v);function Od(a,b,c,e,f){var k=Ud();try{Pb.get(a)(b,c,e,f)}catch(n){Td(k);if(n!==n+0)throw n;Sd(1,0)}}function Gd(a,b,c){var e=Ud();try{return Pb.get(a)(b,c)}catch(f){Td(e);if(f!==f+0)throw f;Sd(1,0)}}function Md(a,b,c){var e=Ud();try{Pb.get(a)(b,c)}catch(f){Td(e);if(f!==f+0)throw f;Sd(1,0)}}
function Fd(a,b){var c=Ud();try{return Pb.get(a)(b)}catch(e){Td(c);if(e!==e+0)throw e;Sd(1,0)}}function Ld(a,b){var c=Ud();try{Pb.get(a)(b)}catch(e){Td(c);if(e!==e+0)throw e;Sd(1,0)}}function Hd(a,b,c,e){var f=Ud();try{return Pb.get(a)(b,c,e)}catch(k){Td(f);if(k!==k+0)throw k;Sd(1,0)}}function Qd(a,b,c,e,f,k,n,l,q,v){var w=Ud();try{Pb.get(a)(b,c,e,f,k,n,l,q,v)}catch(z){Td(w);if(z!==z+0)throw z;Sd(1,0)}}
function Nd(a,b,c,e){var f=Ud();try{Pb.get(a)(b,c,e)}catch(k){Td(f);if(k!==k+0)throw k;Sd(1,0)}}function Pd(a,b,c,e,f,k,n){var l=Ud();try{Pb.get(a)(b,c,e,f,k,n)}catch(q){Td(l);if(q!==q+0)throw q;Sd(1,0)}}function Id(a,b,c,e,f){var k=Ud();try{return Pb.get(a)(b,c,e,f)}catch(n){Td(k);if(n!==n+0)throw n;Sd(1,0)}}function Kd(a,b,c,e,f,k,n,l,q,v){var w=Ud();try{return Pb.get(a)(b,c,e,f,k,n,l,q,v)}catch(z){Td(w);if(z!==z+0)throw z;Sd(1,0)}}
function Jd(a,b,c,e,f,k,n){var l=Ud();try{return Pb.get(a)(b,c,e,f,k,n)}catch(q){Td(l);if(q!==q+0)throw q;Sd(1,0)}}var Vd,Wd;Na=function Xd(){Vd||Yd();Vd||(Na=Xd)};function Yd(){if(!(0<Ka)){if(!Wd&&(Wd=1,Ua(Ha),0<Ka))return;Vd||(Vd=1,r.calledRun=1,za||(Ua(Ia),ba(r),r.onRuntimeInitialized?.(),Ua(Ja)))}}Yd();moduleRtn=ea;


  return moduleRtn;
}
);
})();
export default CanvasKitInit;
