name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # Every Sunday at midnight
    - cron: "0 0 * * 0"

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@1e34f2e2acaa766b7efacb8c26352e6abbb023f9 # 2026.09.13.1

      - name: Install FVM
        run: |
          brew tap leoafarias/fvm
          brew install fvm
          echo "$HOME/fvm/default/bin" >> $GITHUB_PATH

      - name: Build stable 🔧
        run: tool/build.sh stable
      
      - name: Build beta 🔧
        run: tool/build.sh beta
      
      - name: Build master 🔧
        run: tool/build.sh master

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: built
